// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simargl.Trials.Aurora.Aurora01.Storage;

#nullable disable

namespace Simargl.Trials.Aurora.Aurora01.Storage.Migrations
{
    [DbContext(typeof(Aurora01StorageContext))]
    [Migration("20250214141237_Add_RawFrameChannels_Table")]
    partial class Add_RawFrameChannels_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlChannelData", b =>
                {
                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("AdxlAddress")
                        .HasColumnType("integer");

                    b.Property<byte>("Index")
                        .HasColumnType("smallint");

                    b.Property<double>("Frequency")
                        .HasColumnType("double precision");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<double>("SquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision");

                    b.HasKey("Timestamp", "AdxlAddress", "Index", "Frequency");

                    b.HasIndex("AdxlAddress");

                    b.ToTable("AdxlChannels");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlData", b =>
                {
                    b.Property<int>("Address")
                        .HasColumnType("integer");

                    b.HasKey("Address");

                    b.ToTable("Adxls");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlFileData", b =>
                {
                    b.Property<int>("AdxlAddress")
                        .HasColumnType("integer");

                    b.Property<int>("HourDirectoryTimestamp")
                        .HasColumnType("integer");

                    b.Property<int>("Timestamp")
                        .HasColumnType("integer");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("AdxlAddress", "HourDirectoryTimestamp", "Timestamp");

                    b.HasIndex("HourDirectoryTimestamp");

                    b.ToTable("AdxlFiles");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.HourDirectoryData", b =>
                {
                    b.Property<int>("Timestamp")
                        .HasColumnType("integer");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Timestamp");

                    b.ToTable("HourDirectories");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.NmeaData", b =>
                {
                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Timestamp");

                    b.ToTable("Nmeas");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.NmeaFileData", b =>
                {
                    b.Property<int>("HourDirectoryTimestamp")
                        .HasColumnType("integer");

                    b.Property<byte>("Minute")
                        .HasColumnType("smallint");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("HourDirectoryTimestamp", "Minute");

                    b.ToTable("NmeaFiles");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.RawFrameChannelData", b =>
                {
                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<double>("Frequency")
                        .HasColumnType("double precision");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<double>("SquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision");

                    b.HasKey("Timestamp", "Index", "Frequency");

                    b.ToTable("RawFrameChannels");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.RawFrameFileData", b =>
                {
                    b.Property<int>("HourDirectoryTimestamp")
                        .HasColumnType("integer");

                    b.Property<int>("Timestamp")
                        .HasColumnType("integer");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("HourDirectoryTimestamp", "Timestamp");

                    b.ToTable("RawFrameFiles");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlChannelData", b =>
                {
                    b.HasOne("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlData", "Adxl")
                        .WithMany("AdxlChannels")
                        .HasForeignKey("AdxlAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adxls_AdxlChannels");

                    b.Navigation("Adxl");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlFileData", b =>
                {
                    b.HasOne("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlData", "Adxl")
                        .WithMany("AdxlFiles")
                        .HasForeignKey("AdxlAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adxls_AdxlFiles");

                    b.HasOne("Simargl.Trials.Aurora.Aurora01.Storage.Entities.HourDirectoryData", "HourDirectory")
                        .WithMany("AdxlFiles")
                        .HasForeignKey("HourDirectoryTimestamp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HourDirectories_AdxlFiles");

                    b.Navigation("Adxl");

                    b.Navigation("HourDirectory");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.NmeaFileData", b =>
                {
                    b.HasOne("Simargl.Trials.Aurora.Aurora01.Storage.Entities.HourDirectoryData", "HourDirectory")
                        .WithMany("NmeaFiles")
                        .HasForeignKey("HourDirectoryTimestamp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HourDirectories_NmeaFiles");

                    b.Navigation("HourDirectory");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.RawFrameFileData", b =>
                {
                    b.HasOne("Simargl.Trials.Aurora.Aurora01.Storage.Entities.HourDirectoryData", "HourDirectory")
                        .WithMany("RawFrameFiles")
                        .HasForeignKey("HourDirectoryTimestamp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HourDirectories_RawFrameFiles");

                    b.Navigation("HourDirectory");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.AdxlData", b =>
                {
                    b.Navigation("AdxlChannels");

                    b.Navigation("AdxlFiles");
                });

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.HourDirectoryData", b =>
                {
                    b.Navigation("AdxlFiles");

                    b.Navigation("NmeaFiles");

                    b.Navigation("RawFrameFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
