// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simargl.Trials.Aurora.Aurora01.Storage;

#nullable disable

namespace Simargl.Trials.Aurora.Aurora01.Storage.Migrations
{
    [DbContext(typeof(Aurora01StorageContext))]
    [Migration("20250212145746_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simargl.Trials.Aurora.Aurora01.Storage.Entities.HourDirectoryData", b =>
                {
                    b.Property<int>("Timestamp")
                        .HasColumnType("integer");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Timestamp");

                    b.ToTable("HourDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
