// <auto-generated />
using System;
using Apeiron.Platform.Databases.Ape90Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations.Ape90DatabasePostgres
{
    [DbContext(typeof(Ape90DatabasePostgresContext))]
    [Migration("20220324140912_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.ChannelInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Cutoff")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Sampling")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("ChannelInfos");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.Fragment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<long>("ChannelInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<double>("Deviation")
                        .HasColumnType("double precision");

                    b.Property<long>("FrameInfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDataValid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGpsValid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoadedIntoLongFrame")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedZero")
                        .HasColumnType("double precision");

                    b.Property<double>("SquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChannelInfoId", "FrameInfoId", "Index");

                    b.HasIndex("Altitude");

                    b.HasIndex("Average");

                    b.HasIndex("Deviation");

                    b.HasIndex("FrameInfoId");

                    b.HasIndex("IsDataValid");

                    b.HasIndex("IsGpsValid");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("Max");

                    b.HasIndex("Min");

                    b.HasIndex("Speed");

                    b.HasIndex("SpeedZero");

                    b.HasIndex("Sum");

                    b.HasIndex("Time");

                    b.ToTable("Fragments");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.FrameInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasAlternateKey("BeginTime", "EndTime");

                    b.HasIndex("BeginTime");

                    b.HasIndex("EndTime");

                    b.ToTable("FrameInfos");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.Geolocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Age")
                        .HasColumnType("double precision");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Geoidal")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("GpsTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Hdop")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Knots")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("double precision");

                    b.Property<int?>("Mode")
                        .HasColumnType("integer");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Satellites")
                        .HasColumnType("integer");

                    b.Property<int?>("Solution")
                        .HasColumnType("integer");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<int?>("Station")
                        .HasColumnType("integer");

                    b.Property<bool?>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasAlternateKey("RecTime");

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.GgaMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Age")
                        .HasColumnType("double precision");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Geoidal")
                        .HasColumnType("double precision");

                    b.Property<double?>("Hdop")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<long>("RawGeolocationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Satellites")
                        .HasColumnType("integer");

                    b.Property<int?>("Solution")
                        .HasColumnType("integer");

                    b.Property<int?>("Station")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasAlternateKey("RawGeolocationId", "Index");

                    b.ToTable("GgaMessages");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("FrameDuration")
                        .HasColumnType("double precision");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RawDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNormalizedTime")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("BeginTime");

                    b.HasIndex("EndTime");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawFrames");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawGeolocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawGeolocations");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawPower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawPowers");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RmcMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Knots")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("double precision");

                    b.Property<int?>("Mode")
                        .HasColumnType("integer");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("double precision");

                    b.Property<long>("RawGeolocationId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("interval");

                    b.Property<bool?>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasAlternateKey("RawGeolocationId", "Index");

                    b.ToTable("RmcMessages");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.VtgMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<double?>("Knots")
                        .HasColumnType("double precision");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("double precision");

                    b.Property<int?>("Mode")
                        .HasColumnType("integer");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("double precision");

                    b.Property<long>("RawGeolocationId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasAlternateKey("RawGeolocationId", "Index");

                    b.ToTable("VtgMessages");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.Fragment", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.ChannelInfo", "ChannelInfo")
                        .WithMany("Fragments")
                        .HasForeignKey("ChannelInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fragments_ChannelInfos");

                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.FrameInfo", "FrameInfo")
                        .WithMany("Fragments")
                        .HasForeignKey("FrameInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fragments_FrameInfos");

                    b.Navigation("ChannelInfo");

                    b.Navigation("FrameInfo");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.GgaMessage", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.RawGeolocation", "RawGeolocation")
                        .WithMany("GgaMessages")
                        .HasForeignKey("RawGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GgaMessages_RawGeolocations");

                    b.Navigation("RawGeolocation");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawFrame", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.RawDirectory", "RawDirectory")
                        .WithMany("RawFrames")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawFrames_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawGeolocation", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.RawDirectory", "RawDirectory")
                        .WithMany("RawGeolocations")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawGeolocations_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawPower", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.RawDirectory", "RawDirectory")
                        .WithMany("RawPowers")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawPowers_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RmcMessage", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.RawGeolocation", "RawGeolocation")
                        .WithMany("RmcMessages")
                        .HasForeignKey("RawGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RmcMessages_RawGeolocations");

                    b.Navigation("RawGeolocation");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.VtgMessage", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.Ape90Database.Entities.RawGeolocation", "RawGeolocation")
                        .WithMany("VtgMessages")
                        .HasForeignKey("RawGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VtgMessages_RawGeolocations");

                    b.Navigation("RawGeolocation");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.ChannelInfo", b =>
                {
                    b.Navigation("Fragments");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.FrameInfo", b =>
                {
                    b.Navigation("Fragments");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawDirectory", b =>
                {
                    b.Navigation("RawFrames");

                    b.Navigation("RawGeolocations");

                    b.Navigation("RawPowers");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.Ape90Database.Entities.RawGeolocation", b =>
                {
                    b.Navigation("GgaMessages");

                    b.Navigation("RmcMessages");

                    b.Navigation("VtgMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
