// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simargl.Projects.Oriole.Oriole01Storage;

#nullable disable

namespace Simargl.Projects.Oriole.Oriole01Storage.Migrations
{
    [DbContext(typeof(Oriole01StorageContext))]
    [Migration("20250204163348_Add_HourDirectories_Table")]
    partial class Add_HourDirectories_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.HourDirectoryData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("HourDirectories");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.PathData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("Paths");
                });
#pragma warning restore 612, 618
        }
    }
}
