// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simargl.Projects.Oriole.Oriole01Storage;

#nullable disable

namespace Simargl.Projects.Oriole.Oriole01Storage.Migrations
{
    [DbContext(typeof(Oriole01StorageContext))]
    [Migration("20250411082915_Add_ChannelNames_Table")]
    partial class Add_ChannelNames_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.AdxlData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<int>("Address")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Adxls");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.AdxlFileData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<long>("AdxlKey")
                        .HasColumnType("bigint");

                    b.Property<long>("HourDirectoryKey")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasAlternateKey("Timestamp", "AdxlKey");

                    b.HasIndex("AdxlKey");

                    b.HasIndex("HourDirectoryKey");

                    b.ToTable("AdxlFiles");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.ChannelData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<long>("AdxlKey")
                        .HasColumnType("bigint");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<double>("Frequency")
                        .HasColumnType("double precision");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<double>("Max")
                        .HasColumnType("double precision");

                    b.Property<double>("Min")
                        .HasColumnType("double precision");

                    b.Property<double>("SquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("Sum")
                        .HasColumnType("double precision");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasAlternateKey("Timestamp", "AdxlKey", "Index", "Frequency");

                    b.HasIndex("AdxlKey");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.ChannelNameData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<int>("Axis")
                        .HasColumnType("integer");

                    b.Property<double>("Direct")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasAlternateKey("Serial", "Axis");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChannelNames");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.DeviceData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("IPAddress")
                        .IsUnique();

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.HourDirectoryData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("HourDirectories");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.NmeaData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("Nmeas");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.NmeaFileData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<long>("HourDirectoryKey")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("HourDirectoryKey");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("NmeaFiles");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.PathData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.RecordPathData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.ToTable("RecordPaths");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.AdxlFileData", b =>
                {
                    b.HasOne("Simargl.Projects.Oriole.Oriole01Storage.Entities.AdxlData", "Adxl")
                        .WithMany("AdxlFiles")
                        .HasForeignKey("AdxlKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adxls_AdxlFiles");

                    b.HasOne("Simargl.Projects.Oriole.Oriole01Storage.Entities.HourDirectoryData", "HourDirectory")
                        .WithMany("AdxlFiles")
                        .HasForeignKey("HourDirectoryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HourDirectories_AdxlFiles");

                    b.Navigation("Adxl");

                    b.Navigation("HourDirectory");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.ChannelData", b =>
                {
                    b.HasOne("Simargl.Projects.Oriole.Oriole01Storage.Entities.AdxlData", "Adxl")
                        .WithMany("Channels")
                        .HasForeignKey("AdxlKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adxls_Channels");

                    b.Navigation("Adxl");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.NmeaFileData", b =>
                {
                    b.HasOne("Simargl.Projects.Oriole.Oriole01Storage.Entities.HourDirectoryData", "HourDirectory")
                        .WithMany("NmeaFiles")
                        .HasForeignKey("HourDirectoryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HourDirectories_NmeaFiles");

                    b.Navigation("HourDirectory");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.AdxlData", b =>
                {
                    b.Navigation("AdxlFiles");

                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Simargl.Projects.Oriole.Oriole01Storage.Entities.HourDirectoryData", b =>
                {
                    b.Navigation("AdxlFiles");

                    b.Navigation("NmeaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
