// <auto-generated />
using Apeiron.Platform.Databases.OsmDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OsmDatabaseContext))]
    [Migration("20220216141806_Add_Table_OsmNodes")]
    partial class Add_Table_OsmNodes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Maps.Database.Entities.OsmFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNodesLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTagsLoad")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("IsEmpty");

                    b.HasIndex("IsNodesLoad");

                    b.HasIndex("IsTagsLoad");

                    b.ToTable("OsmFiles");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Maps.Database.Entities.OsmNode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<long>("OsmFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("OsmFileId");

                    b.ToTable("OsmNodes");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Maps.Database.Entities.OsmNode", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Maps.Database.Entities.OsmFile", "OsmFile")
                        .WithMany("OsmNodes")
                        .HasForeignKey("OsmFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OsmNodes_OsmFile");

                    b.Navigation("OsmFile");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Maps.Database.Entities.OsmFile", b =>
                {
                    b.Navigation("OsmNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
