// <auto-generated />
using System;
using Apeiron.Platform.Databases.GlobalIdentityDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(GlobalIdentityDatabaseContext))]
    [Migration("20211204104133_Add_ReceiptTime_Field_In_IdentityMessages_Table")]
    partial class Add_ReceiptTime_Field_In_IdentityMessages_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Services.GlobalIdentity.Database.GlobalIdentifier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("GlobalIdentifiers");
                });

            modelBuilder.Entity("Apeiron.Services.GlobalIdentity.Database.IdentityMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GlobalIdentifierId")
                        .HasColumnType("bigint");

                    b.Property<long>("PacketIdentifier")
                        .HasColumnType("bigint");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceiptTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalIdentifierId");

                    b.ToTable("IdentityMessages");
                });

            modelBuilder.Entity("Apeiron.Services.GlobalIdentity.Database.IdentityMessage", b =>
                {
                    b.HasOne("Apeiron.Services.GlobalIdentity.Database.GlobalIdentifier", "GlobalIdentifier")
                        .WithMany("IdentityMessages")
                        .HasForeignKey("GlobalIdentifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalIdentifier");
                });

            modelBuilder.Entity("Apeiron.Services.GlobalIdentity.Database.GlobalIdentifier", b =>
                {
                    b.Navigation("IdentityMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
