// <auto-generated />
using System;
using Apeiron.Platform.Databases.Ra2Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(Ra2DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApeironApeiron.Platform.Databases.Ra2Database.Entities.ChannelResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<double>("Min")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Offset")
                        .HasColumnType("float");

                    b.Property<long>("RawFileId")
                        .HasColumnType("bigint");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<double>("Scale")
                        .HasColumnType("float");

                    b.Property<double>("SquaresSum")
                        .HasColumnType("float");

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RawFileId");

                    b.ToTable("ChannelResults");
                });

            modelBuilder.Entity("ApeironApeiron.Platform.Databases.Ra2Database.Entities.RawFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("IsAnalyzed");

                    b.ToTable("RawFiles");
                });

            modelBuilder.Entity("ApeironApeiron.Platform.Databases.Ra2Database.Entities.ChannelResult", b =>
                {
                    b.HasOne("ApeironApeiron.Platform.Databases.Ra2Database.Entities.RawFile", "RawFile")
                        .WithMany("ChannelResults")
                        .HasForeignKey("RawFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChannelResults_RawFiles_RawFileId");

                    b.Navigation("RawFile");
                });

            modelBuilder.Entity("ApeironApeiron.Platform.Databases.Ra2Database.Entities.RawFile", b =>
                {
                    b.Navigation("ChannelResults");
                });
#pragma warning restore 612, 618
        }
    }
}
