hmLoadTopic({
hmKeywords:"",
hmTitle:"OnKgPaint - Окончание отрисовки в окне",
hmDescription:"Синтаксис Automation: void OnKgPaint ([in]PaintObject* paintObj); Входные параметры: paintObj - интерфейс для создания графических объектов. Примечание: После завершения от",
hmPrevLink:"_dkgaxevents_onkgcreate.html",
hmNextLink:"_dkgaxevents_oncreategllist.html",
hmParentLink:"_dkgaxeventscommon.html",
hmBreadCrumbs:"<a href=\"kgax.html\">KGAX - ActiveX компонент<\/a> &gt; <a href=\"co1725258.html\">Интерфейсы<\/a> &gt; <a href=\"_dkgax.html\">Интерфейс _DKGAX&nbsp;<\/a> &gt; <a href=\"_dkgaxeventscommon.html\">Интерфейс _DKGAX - События&nbsp;<\/a>",
hmTitlePath:"KGAX - ActiveX компонент > Интерфейсы > Интерфейс _DKGAX  > Интерфейс _DKGAX - События  > OnKgPaint - Окончание отрисовки в окне ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">OnKgPaint - Окончание отрисовки в окне <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xco1735106\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\"> <\/span><span class=\"f_bodytext\" style=\"font-weight: bold;\">Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">void OnKgPaint ([in]PaintObject* paintObj);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">paintObj<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- интерфейс для создания графических объектов.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">После завершения отрисовки документа можно отрисовать свои объекты.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
