hmLoadTopic({
hmKeywords:"",
hmTitle:"Структуры параметров текста",
hmDescription:"Подразделы: ParagraphParam - Структура параметров параграфа  TextDocumentParam - Структура параметров текстового документа  TextDocumentParamW - Структура параметров текстового",
hmPrevLink:"structspctuningstyleparamw.html",
hmNextLink:"structparagraphparam.html",
hmParentLink:"3d_define.html",
hmBreadCrumbs:"<a href=\"3d_define.html\">Структуры параметров и константы<\/a>",
hmTitlePath:"Структуры параметров и константы > Структуры параметров текста ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Структуры параметров текста <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structparagraphparam.html\" class=\"topiclink hmlinklistitem\">ParagraphParam - Структура параметров параграфа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextdocumentparam.html\" class=\"topiclink hmlinklistitem\">TextDocumentParam - Структура параметров текстового документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextdocumentparamw.html\" class=\"topiclink hmlinklistitem\">TextDocumentParamW - Структура параметров текстового документа (Unicode) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextlineparam.html\" class=\"topiclink hmlinklistitem\">TextLineParam - Структура параметров строки текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextitemfont.html\" class=\"topiclink hmlinklistitem\">TextItemFont - Структура параметров шрифта компоненты строки текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextitemfontw.html\" class=\"topiclink hmlinklistitem\">TextItemFontW - Структура параметров шрифта компоненты строки текста (Unicode) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextitemparam.html\" class=\"topiclink hmlinklistitem\">TextItemParam - Структура параметров компоненты строки текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextitemparamw.html\" class=\"topiclink hmlinklistitem\">TextItemParamW - Структура параметров компоненты строки текста (Unicode) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextparam.html\" class=\"topiclink hmlinklistitem\">TextParam - Структура параметров текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextstyleparam.html\" class=\"topiclink hmlinklistitem\">TextStyleParam - Структура параметров стиля текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"structtextstyleparamw.html\" class=\"topiclink hmlinklistitem\">TextStyleParamW - Структура параметров стиля текста (Unicode) <\/a><\/span><\/p>\n\r"
})
