hmLoadTopic({
hmKeywords:"",
hmTitle:"Константы графических объектов",
hmDescription:"Подразделы: ksContourFormEnum – форма контура обозначения узла  Константы типов интерфейсов параметров для COM в 2D  Типы отрисовки стрелок для линии-выноски  Системные стили о",
hmPrevLink:"end_type.html",
hmNextLink:"kscontourformenum.html",
hmParentLink:"bk1803360.html",
hmBreadCrumbs:"<a href=\"3d_define.html\">Структуры параметров и константы<\/a> &gt; <a href=\"bk1803360.html\">Константы&nbsp;<\/a>",
hmTitlePath:"Структуры параметров и константы > Константы  > Константы графических объектов ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Константы графических объектов <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscontourformenum.html\" class=\"topiclink hmlinklistitem\">ksContourFormEnum – форма контура обозначения узла <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"interfaceparamtypeenum.html\" class=\"topiclink hmlinklistitem\">Константы типов интерфейсов параметров для COM в 2D <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"a1styles.html\" class=\"topiclink hmlinklistitem\">Типы отрисовки стрелок для линии-выноски <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"pstyles.html\" class=\"topiclink hmlinklistitem\">Системные стили отрисовки точек <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"lstyles.html\" class=\"topiclink hmlinklistitem\">Системные стили линий <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"thicknesstypes.html\" class=\"topiclink hmlinklistitem\">Параметры пера пользовательского стиля линии <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"hstyles.html\" class=\"topiclink hmlinklistitem\">Системные стили штриховок <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"marktypes.html\" class=\"topiclink hmlinklistitem\">Системные типы значков <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ptypes.html\" class=\"topiclink hmlinklistitem\">Типы фантомов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"phantomtypes.html\" class=\"topiclink hmlinklistitem\">Типы фантомов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"paramtypes.html\" class=\"topiclink hmlinklistitem\">Типы параметров объектов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdrawingobjectparamtypeenum.html\" class=\"topiclink hmlinklistitem\">ksDrawingObjectParamTypeEnum – тип параметров объекта <\/a><\/span><\/p>\n\r"
})
