hmLoadTopic({
hmKeywords:"",
hmTitle:"Аннотационные объекты",
hmDescription:"Подразделы: ksAnnArcByPoint - Создать аннотационную дугу по точкам  ksAnnCircle - Создать объект \"Аннотационная окружность\"  ksAnnEllipse - Создать объект \"Аннотационный эллипс\"",
hmPrevLink:"ksdocument2d_saveastouncompressedrasterformat.html",
hmNextLink:"ksdocument2d_ksannarcbypoint.html",
hmParentLink:"ksdocument2d_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ksdocument2d_methods.html\">ksDocument2D - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > ksDocument2D - методы  > Аннотационные объекты ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Аннотационные объекты <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannarcbypoint.html\" class=\"topiclink hmlinklistitem\">ksAnnArcByPoint - Создать аннотационную дугу по точкам <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksanncircle.html\" class=\"topiclink hmlinklistitem\">ksAnnCircle - Создать объект &quot;Аннотационная окружность&quot; <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannellipse.html\" class=\"topiclink hmlinklistitem\">ksAnnEllipse - Создать объект &quot;Аннотационный эллипс&quot; <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannellipsearc.html\" class=\"topiclink hmlinklistitem\">ksAnnEllipseArc - Создать объект &quot;Аннотационная дуга эллипса&quot; <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannlineseg.html\" class=\"topiclink hmlinklistitem\">ksAnnLineSeg - Создать аннотационный отрезок <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannparellipsearc.html\" class=\"topiclink hmlinklistitem\">ksAnnParEllipseArc - Создать объект &quot;Аннотационная дуга эллипса&quot; <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannpoint.html\" class=\"topiclink hmlinklistitem\">ksAnnPoint - Создать объект &quot;точка&quot; c аннотационной точкой привязки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannpolyline.html\" class=\"topiclink hmlinklistitem\">ksAnnPolyline - Создать аннотационную ломаную линию <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksannpolylineex.html\" class=\"topiclink hmlinklistitem\">ksAnnPolylineEx - Создать объект &quot;Аннотационная ломаная линия&quot; по интерфейсу параметров <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdocument2d_ksanntextex.html\" class=\"topiclink hmlinklistitem\">ksAnnTextEx - Создать объект &quot;Текст с аннотационной точкой привязки&quot; <\/a><\/span><\/p>\n\r"
})
