hmLoadTopic({
hmKeywords:"",
hmTitle:"Оформление прикладных библиотек типа ActiveX",
hmDescription:"В Компас v20 появилась возможность наследования от интерфейсов прикладной библиотеки.",
hmPrevLink:"libraryhinttipsbeginid.html",
hmNextLink:"ikompaslibrary.html",
hmParentLink:"libraries_create.html",
hmBreadCrumbs:"<a href=\"libraries_create.html\">Создание прикладных библиотек&nbsp;<\/a>",
hmTitlePath:"Создание прикладных библиотек  > Оформление прикладных библиотек типа ActiveX ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Оформление прикладных библиотек типа ActiveX <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\">В Компас v20 появилась возможность наследования от интерфейсов прикладной библиотеки.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Добавлена библиотека типов интерфейсов KompasLibrary.tlb с описанием нового дуального интерфейса прикладной ActiveX библиотеки <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompaslibrary.html\" class=\"topiclink\">IKompasLibrary<\/a><\/span><span class=\"f_bodytext\"> и интерфейса <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kskompaslibrary.html\" class=\"topiclink\">ksKompasLibrary<\/a><\/span><span class=\"f_bodytext\">, который соответствует старому описанию функций для ActiveX библиотек.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">В библиотеке можно реализовать наследование от нового или старого варианта интерфейсов.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompaslibrary.html\" class=\"topiclink hmlinklistitem\">Интерфейс IKompasLibrary <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompaslibrarymenu.html\" class=\"topiclink hmlinklistitem\">Интерфейс IKompasLibraryMenu <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kskompaslibrary.html\" class=\"topiclink hmlinklistitem\">Интерфейс ksKompasLibrary <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"lib_actx_common.html\" class=\"topiclink hmlinklistitem\">Функции оформления библиотек типа ActiveX <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"simple_sample_ax.html\" class=\"topiclink hmlinklistitem\">Пример простейшей программы в среде VB, оформленной в виде ActiveX библиотеки КОМПАС <\/a><\/span><\/p>\n\r"
})
