hmLoadTopic({
hmKeywords:"",
hmTitle:"EditMacroMode - Получить режим работы функции библиотеки (создание нового или редактирование существующего макроэлемента)",
hmDescription:"Пример... Аналог данной функции при использовании Automation - метод ksDocument2D::ksEditMacroMode. Синтаксис: reference EditMacroMode(); Возвращаемое значение: указатель на",
hmPrevLink:"lib_macro_object_def.html",
hmNextLink:"getmacroparam.html",
hmParentLink:"lib_macro_object_def.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"cm1726661.html\">Функции работы с графическим документом&nbsp;<\/a> &gt; <a href=\"cm1732355.html\">Создание графических объектов&nbsp;<\/a> &gt; <a href=\"cm1919792.html\">Работа с макроэлементами и библиотечными макроэлементами&nbsp;<\/a> &gt; <a href=\"lib_macro_object_def.html\">Функции работы с макроэлементами и библиотечными макроэлементами&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Функции работы с графическим документом  > Создание графических объектов  > Работа с макроэлементами и библиотечными макроэлементами  > Функции работы с макроэлементами и библиотечными макроэлементами  > EditMacroMode - Получить режим работы функции библиотеки (создание нового или редактирование существующего макроэлемента) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">EditMacroMode - Получить режим работы функции библиотеки (создание нового или редактирование существующего макроэлемента) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcn2036014\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"setmacroparam_example.html\" class=\"topiclink\">Пример...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данной функции при использовании Automation - метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2d_kseditmacromode.html\" class=\"topiclink\">ksDocument2D::ksEditMacroMode<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">reference EditMacroMode();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">указатель на редактируемый макроэлемент<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- при редактировании макроэлемента,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">0<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- при создании макроэлемента.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
