hmLoadTopic({
hmKeywords:"",
hmTitle:"ExternalGetResourceModule - Задать модуль с ресурсами библиотеки",
hmDescription:"VARIANT ExternalGetResourceModule(); Возвращаемое значение: HINSTANCE (тип VT_I4), либо имя файла (тип VT_BSTR) dll, в котором находятся ресурсы библиотеки.TRUE   Примечание:",
hmPrevLink:"isonapplication7.html",
hmNextLink:"cr90777.html",
hmParentLink:"cr154576.html",
hmBreadCrumbs:"<a href=\"libraries_create.html\">Создание прикладных библиотек&nbsp;<\/a> &gt; <a href=\"cr119224.html\">Оформление прикладных библиотек типа ActiveX&nbsp;<\/a> &gt; <a href=\"simple_sample_ax.html\">Пример простейшей программы в среде VB, оформленной в виде ActiveX библиотеки КОМПАС&nbsp;<\/a> &gt; <a href=\"cr154576.html\">Функции&nbsp;<\/a>",
hmTitlePath:"Создание прикладных библиотек  > Оформление прикладных библиотек типа ActiveX  > Пример простейшей программы в среде VB, оформленной в виде ActiveX библиотеки КОМПАС  > Функции  > ExternalGetResourceModule - Задать модуль с ресурсами библиотеки ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ExternalGetResourceModule - Задать модуль с ресурсами библиотеки <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcr93793\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">VARIANT ExternalGetResourceModule();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">HINSTANCE (тип VT_I4), либо имя файла (тип VT_BSTR) dll, в котором находятся ресурсы библиотеки.TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Добавлена возможность указания произвольного dll-файла с ресурсами.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
