hmLoadTopic({
hmKeywords:"",
hmTitle:"AddGabarit - Добавить дополнительный габарит к габариту документа",
hmDescription:"Интерфейс... Синтаксис: VARIANT_BOOL AddGabarit ([in]double p1X, [in]double p1Y, [in]double p1Z, [in]double p2X, [in]double p2Y, [in]double p2Z ); Входные параметры: p1X",
hmPrevLink:"gabaritobject_methods.html",
hmNextLink:"globject.html",
hmParentLink:"gabaritobject_methods.html",
hmBreadCrumbs:"<a href=\"kgax.html\">KGAX - ActiveX компонент<\/a> &gt; <a href=\"co1725258.html\">Интерфейсы<\/a> &gt; <a href=\"gabaritobject.html\">Интерфейс GabaritObject&nbsp;<\/a> &gt; <a href=\"gabaritobject_methods.html\">Интерфейс GabaritObject - методы&nbsp;<\/a>",
hmTitlePath:"KGAX - ActiveX компонент > Интерфейсы > Интерфейс GabaritObject  > Интерфейс GabaritObject - методы  > AddGabarit - Добавить дополнительный габарит к габариту документа ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">AddGabarit - Добавить дополнительный габарит к габариту документа <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xco1735066\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"gabaritobject.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">VARIANT_BOOL AddGabarit ([in]double p1X,<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">[in]double p1Y,<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">[in]double p1Z,<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">[in]double p2X,<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">[in]double p2Y,<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">[in]double p2Z );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">p1X, p1Y, p1Z<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- координаты первой точки габарита,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">p2X, p2Y, p2Z<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- координаты второй точки габарита.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
