hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IAdditionalBlockStyle",
hmDescription:"Интерфейс стиля блока дополнительных (вложенных) разделов спецификации.",
hmPrevLink:"iadditionalblocksectiontuning_use.html",
hmNextLink:"iadditionalblockstyle_props.html",
hmParentLink:"spec_work.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"spec_work.html\">Работа со спецификацией&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Работа со спецификацией  > Интерфейс IAdditionalBlockStyle ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IAdditionalBlockStyle <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbf1809907\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс стиля блока дополнительных (вложенных) разделов спецификации.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"iadditionalblockstyle.html\" class=\"topiclink\">IAdditionalBlockStyle<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Вложенные разделы располагаются внутри раздела, после всех объектов этого раздела.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Дополнительные разделы располагаются в конце спецификации, после всех ее разделов.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Блок состоит из тех же разделов, что и сама спецификация.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить от интерфейса коллекции стилей дополнительных (вложенных) разделов спецификации <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iadditionalblockstyles.html\" class=\"topiclink\">IAdditionalBlockStyles<\/a><\/span><span class=\"f_bodytext\">, <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iadditionalblockstyles_item.html\" class=\"topiclink\">IAdditionalBlockStyles::Item<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iadditionalblockstyle_props.html\" class=\"topiclink hmlinklistitem\">IAdditionalBlockStyle - свойства <\/a><\/span><\/p>\n\r"
})
