hmLoadTopic({
hmKeywords:"",
hmTitle:"RegisterLibraryNumber - Зарегистрировать номер продукта на сервере лицензий Компас",
hmDescription:"Интерфейс... Синтаксис Automation: long RegisterLibraryNumber( long ProductNumber ); Синтаксис COM: HRESULT RegisterLibraryNumber( long ProductNumber, long * ProductNumbUnicu",
hmPrevLink:"iapplicationlicensemanager_enablekompasinvisible.html",
hmNextLink:"iapplicationlicensemanager_unregisterlibrarynumber.html",
hmParentLink:"iapplicationlicensemanager_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap1981077.html\">Менеджер лицензий&nbsp;<\/a> &gt; <a href=\"iapplicationlicensemanager.html\">Интерфейс IApplicationLicenseManager&nbsp;<\/a> &gt; <a href=\"iapplicationlicensemanager_methods.html\">IApplicationLicenseManager - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Менеджер лицензий  > Интерфейс IApplicationLicenseManager  > IApplicationLicenseManager - методы  > RegisterLibraryNumber - Зарегистрировать номер продукта на сервере лицензий Компас ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">RegisterLibraryNumber - Зарегистрировать номер продукта на сервере лицензий Компас <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xap1983000\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iapplicationlicensemanager.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">long RegisterLibraryNumber( long ProductNumber );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT RegisterLibraryNumber( long ProductNumber, long * ProductNumbUnicueId );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Уникальный идентификатор продукта.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">long ProductNumber<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- номер продукта.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Уникальный идентификатор продукта используется для разрегистрации продукта функцией <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iapplicationlicensemanager_unregisterlibrarynumber.html\" class=\"topiclink\">IApplicationLicenseManager::UnRegisterLibraryNumber<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
