hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IApplicationLicenseManager",
hmDescription:"Менеджер лицензий Иерархия: IDispatch IApplicationLicenseManager Примечание: Интерфейс является дополнительным к интерфейсу приложения IApplication. Интерфейс можно получить",
hmPrevLink:"ap1981077.html",
hmNextLink:"iapplicationlicensemanager_propers.html",
hmParentLink:"ap1981077.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap1981077.html\">Менеджер лицензий&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Менеджер лицензий  > Интерфейс IApplicationLicenseManager ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IApplicationLicenseManager <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xap1983050\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Менеджер лицензий<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"iapplicationlicensemanager.html\" class=\"topiclink\">IApplicationLicenseManager<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс является дополнительным к интерфейсу приложения <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iapplication.html\" class=\"topiclink\">IApplication<\/a><\/span><span class=\"f_bodytext\">. Интерфейс можно получить посредством вызова метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"recomendation.html\" class=\"topiclink\">IUnknown::QueryInterface (const GUID far&amp; iid, void** pif)<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия: Компас v19<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iapplicationlicensemanager_propers.html\" class=\"topiclink hmlinklistitem\">IApplicationLicenseManager - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iapplicationlicensemanager_methods.html\" class=\"topiclink hmlinklistitem\">IApplicationLicenseManager - методы <\/a><\/span><\/p>\n\r"
})
