hmLoadTopic({
hmKeywords:"",
hmTitle:"IAttribute - методы",
hmDescription:"Подразделы: AddRow - Добавить строку к табличному атрибуту неопределенной длины  Delete - Удалить атрибут  DeleteRow - Удалить строку табличного атрибута неопределенной длины",
hmPrevLink:"iattribute_values.html",
hmNextLink:"iattribute_addrow.html",
hmParentLink:"iattribute.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"doc.html\">Документ&nbsp;<\/a> &gt; <a href=\"attribute.html\">Атрибуты&nbsp;<\/a> &gt; <a href=\"iattribute.html\">Интерфейс IAttribute&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ  > Атрибуты  > Интерфейс IAttribute  > IAttribute - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IAttribute - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_addrow.html\" class=\"topiclink hmlinklistitem\">AddRow - Добавить строку к табличному атрибуту неопределенной длины <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_delete.html\" class=\"topiclink hmlinklistitem\">Delete - Удалить атрибут <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_deleterow.html\" class=\"topiclink hmlinklistitem\">DeleteRow - Удалить строку табличного атрибута неопределенной длины <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_getkeysinfo.html\" class=\"topiclink hmlinklistitem\">GetKeysInfo - Выдать информацию о ключах атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setcolumnkey.html\" class=\"topiclink hmlinklistitem\">SetColumnKey - Установить ключи колонок <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setflagvisible.html\" class=\"topiclink hmlinklistitem\">SetFlagVisible - Установить значения видимости колонок в виде массива SAFEARRAY VT_ARRAY | VT_BOOL <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setkeysinfo.html\" class=\"topiclink hmlinklistitem\">SetKeysInfo - Установить информацию о ключах атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setpassword.html\" class=\"topiclink hmlinklistitem\">SetPassword - Установить новый пароль на изменение данных атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setrecordflagvisible.html\" class=\"topiclink hmlinklistitem\">SetRecordFlagVisible - Установить значения видимости колонок внутри записи в виде массива SAFEARRAY VT_ARRAY | VT_BOOL <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setvalue.html\" class=\"topiclink hmlinklistitem\">SetValue - Установить значение ячейки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_setvalues.html\" class=\"topiclink hmlinklistitem\">SetValues - Установить значения всех ячеек таблицы атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iattribute_viewedit.html\" class=\"topiclink hmlinklistitem\">ViewEdit - Открыть диалог для просмотра и редактирования атрибута <\/a><\/span><\/p>\n\r"
})
