hmLoadTopic({
hmKeywords:"",
hmTitle:"Add - Создать новый элемент и добавить его в коллекцию",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH Add; Синтаксис COM: HRESULT Add( IBase3D ** Result); Возвращаемое значение:  - Указатель на интерфейс базы 3D IBase3D. Подразд",
hmPrevLink:"ibases3d_methods.html",
hmNextLink:"ileaders3d.html",
hmParentLink:"ibases3d_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2273863.html\">Оформление&nbsp;<\/a> &gt; <a href=\"bc2275772.html\">Обозначения&nbsp;<\/a> &gt; <a href=\"ibases3d.html\">Интерфейс IBases3D&nbsp;<\/a> &gt; <a href=\"ibases3d_methods.html\">IBases3D - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Оформление  > Обозначения  > Интерфейс IBases3D  > IBases3D - методы  > Add - Создать новый элемент и добавить его в коллекцию ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Add - Создать новый элемент и добавить его в коллекцию <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ibases3d.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH Add;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Add( IBase3D ** Result);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Указатель на интерфейс базы 3D <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ibase3d.html\" class=\"topiclink\">IBase3D<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
