hmLoadTopic({
hmKeywords:"",
hmTitle:"Add - Создать фигурную скобку",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATH Add( ); Синтаксис COM: HRESULT Add( IBrace** Result); Возвращаемое значение: Result - Указатель на интерфейс фигурной скобки IBr",
hmPrevLink:"ibraces_methods.html",
hmNextLink:"ibuildingaxes.html",
hmParentLink:"ibraces_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2362006.html\">Обозначения для строительства&nbsp;<\/a> &gt; <a href=\"ibraces.html\">Интерфейс IBraces&nbsp;<\/a> &gt; <a href=\"ibraces_methods.html\">IBraces - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Обозначения для строительства  > Интерфейс IBraces  > IBraces - методы  > Add - Создать фигурную скобку ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Add - Создать фигурную скобку <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ibraces.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATH Add( );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Add( IBrace** Result);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Result<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Указатель на интерфейс фигурной скобки <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ibrace.html\" class=\"topiclink\">IBrace<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Метод позволяет создать новый интерфейс фигурной скобки. После получения нового интерфейса нужно задать параметры фигурной скобки и вызвать метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"idrawingobject_update.html\" class=\"topiclink\">IDrawingObject::Update<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
