hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IChooseBodies7",
hmDescription:"Интерфейс области применения для тел документа в операции.",
hmPrevLink:"ithreaddialogparam_standart.html",
hmNextLink:"ichoosebodies7_props.html",
hmParentLink:"bc2279073.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2278808.html\">Операции, массивы, эскизы, точки&nbsp;<\/a> &gt; <a href=\"bc2279073.html\">Операции&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Операции, массивы, эскизы, точки  > Операции  > Интерфейс IChooseBodies7 ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IChooseBodies7 <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс области применения для тел документа в операции<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ichoosebodies7.html\" class=\"topiclink\">IChooseBodies7<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Позволяет получить интерфейс области применения для тел документа в операции.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить у операции выдавливание <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iextrusion.html\" class=\"topiclink\">IExtrusion<\/a><\/span><span class=\"f_bodytext\"> и интерфейса твердого тела <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ibody7.html\" class=\"topiclink\">IBody7<\/a><\/span><span class=\"f_bodytext\"> посредством вызова метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"recomendation.html\" class=\"topiclink\">IUnknown::QueryInterface (const GUID far&amp; iid, void** pif)<\/a><\/span><span class=\"f_bodytext\">;<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ichoosebodies7_props.html\" class=\"topiclink hmlinklistitem\">IChooseBodies7 - свойства <\/a><\/span><\/p>\n\r"
})
