hmLoadTopic({
hmKeywords:"",
hmTitle:"ICircularCopyObjectParam - свойства",
hmDescription:"Подразделы: Angle2 - Начальный угол  Count1 - Количество копий в радиальном направлении  Count2 - Количество копий в кольцевом направлении  Radius - Начальный радиус  SaveCent",
hmPrevLink:"icircularcopyobjectparam.html",
hmNextLink:"icircularcopyobjectparam_angle2.html",
hmParentLink:"icircularcopyobjectparam.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2370796.html\">Параметры&nbsp;<\/a> &gt; <a href=\"icopyobjectparam.html\">Интерфейс ICopyObjectParam&nbsp;<\/a> &gt; <a href=\"icopyobjectparam_props.html\">ICopyObjectParam - свойства&nbsp;<\/a> &gt; <a href=\"icopyobjectparam_ynew.html\">YNew - Координата новой точки привязки объекта по оси Y&nbsp;<\/a> &gt; <a href=\"icircularcopyobjectparam.html\">Интерфейс ICircularCopyObjectParam&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Параметры  > Интерфейс ICopyObjectParam  > ICopyObjectParam - свойства  > YNew - Координата новой точки привязки объекта по оси Y  > Интерфейс ICircularCopyObjectParam  > ICircularCopyObjectParam - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ICircularCopyObjectParam - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_angle2.html\" class=\"topiclink hmlinklistitem\">Angle2 - Начальный угол <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_count1.html\" class=\"topiclink hmlinklistitem\">Count1 - Количество копий в радиальном направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_count2.html\" class=\"topiclink hmlinklistitem\">Count2 - Количество копий в кольцевом направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_radius.html\" class=\"topiclink hmlinklistitem\">Radius - Начальный радиус <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_savecentrecopy.html\" class=\"topiclink hmlinklistitem\">SaveCentreCopy - Признак наличия копии в центре сетки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_step1.html\" class=\"topiclink hmlinklistitem\">Step1 - Шаг копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_step2.html\" class=\"topiclink hmlinklistitem\">Step2 - Угловой шаг (градусы) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_stepfactor1.html\" class=\"topiclink hmlinklistitem\">StepFactor1 - Интерпретация шага в радиальном направлении: расстояние между соседними копиями или между крайними <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_stepfactor2.html\" class=\"topiclink hmlinklistitem\">StepFactor2 - Интерпретация шага в кольцевом направлении: угол между соседними копиями или между крайними <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icircularcopyobjectparam_turnobject.html\" class=\"topiclink hmlinklistitem\">TurnObject - Признак доворота копий до радиального направления <\/a><\/span><\/p>\n\r"
})
