hmLoadTopic({
hmKeywords:"",
hmTitle:"IComponentPositioner7 - методы",
hmDescription:"Подразделы: Finish - Завершить перемещение InitAxis - Установить ось InitAxisByPoints - Установить ось по точкам InitPlane - Установить плоскость InitPlaneByPlacement - Устано",
hmPrevLink:"icomponentpositioner7.html",
hmNextLink:"icomponentpositioner7_finish.html",
hmParentLink:"icomponentpositioner7.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2609111.html\">Компоненты&nbsp;<\/a> &gt; <a href=\"icomponentpositioner7.html\">Интерфейс IComponentPositioner7<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Компоненты  > Интерфейс IComponentPositioner7 > IComponentPositioner7 - методы",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IComponentPositioner7 - методы<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_finish.html\" class=\"topiclink hmlinklistitem\">Finish - Завершить перемещение<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_initaxis.html\" class=\"topiclink hmlinklistitem\">InitAxis - Установить ось<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_initaxisbypoints.html\" class=\"topiclink hmlinklistitem\">InitAxisByPoints - Установить ось по точкам<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_initplane.html\" class=\"topiclink hmlinklistitem\">InitPlane - Установить плоскость<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_initplanebyplacement.html\" class=\"topiclink hmlinklistitem\">InitPlaneByPlacement - Установить плоскость по СК<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_initplanebypoints.html\" class=\"topiclink hmlinklistitem\">InitPlaneByPoints - Установить плоскость по точкам<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_movecomponent.html\" class=\"topiclink hmlinklistitem\">MoveComponent - Перемещение компонента<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_prepare.html\" class=\"topiclink hmlinklistitem\">Prepare - Подготовиться к перемещению компонента<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_rotatecomponent.html\" class=\"topiclink hmlinklistitem\">RotateComponent - Подготовиться к повороту компонента<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icomponentpositioner7_setdragpoint.html\" class=\"topiclink hmlinklistitem\">SetDragPoint - Установить точку захвата ( ручка)<\/a><\/span><\/p>\n\r"
})
