hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IСonverter",
hmDescription:"Конвертер файлов КОМПАС. Иерархия: IKompasAPIObject IConverter Примечание: 1. Интерфейс позволяет управлять конвертером системы КОМПАС, задавать параметры конвертирования, п",
hmPrevLink:"conv.html",
hmNextLink:"iconverter_methods.html",
hmParentLink:"conv.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"conv.html\">Конвертер файлов КОМПАС&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Конвертер файлов КОМПАС  > Интерфейс IСonverter ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IСonverter <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbg1711273\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Конвертер файлов КОМПАС<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"iconverter.html\" class=\"topiclink\">IConverter<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Интерфейс позволяет управлять конвертером системы КОМПАС, задавать параметры конвертирования, получать фильтр и выполнять конвертацию документа системы КОМПАС.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Данный интерфейс может быть получен от интерфейса приложения <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iapplication.html\" class=\"topiclink\">IApplication<\/a><\/span><span class=\"f_Numbered\"> с помощью свойства <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iapplication_converter.html\" class=\"topiclink\">IApplication::Converter<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iconverter_methods.html\" class=\"topiclink hmlinklistitem\">IConverter - методы <\/a><\/span><\/p>\n\r"
})
