hmLoadTopic({
hmKeywords:"",
hmTitle:"Add - Создает новый элемент и добавляет его в коллекцию",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH Add(); Синтаксис COM: HRESULT Add( IConicCurve * * Result ); Возвращаемое значение:  - Указатель на интерфейс IConicCurve. При",
hmPrevLink:"iconiccurves_methods.html",
hmNextLink:"idrawingcontours.html",
hmParentLink:"iconiccurves_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2333035.html\">Геометрия&nbsp;<\/a> &gt; <a href=\"iconiccurves.html\">Интерфейс IConicCurves&nbsp;<\/a> &gt; <a href=\"iconiccurves_methods.html\">IConicCurves - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Геометрия  > Интерфейс IConicCurves  > IConicCurves - методы  > Add - Создает новый элемент и добавляет его в коллекцию ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Add - Создает новый элемент и добавляет его в коллекцию <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iconiccurves.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH Add();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Add( IConicCurve * * Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Указатель на интерфейс <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"iconiccurve.html\" class=\"topiclink\">IConicCurve<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечания<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Метод позволяет создать новый интерфейс конической кривой.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. После получения нового интерфейса нужно задать параметры операции и вызвать метод <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"imodelobject_update.html\" class=\"topiclink\">IModelObject::Update<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
