hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ICopiesGeometry",
hmDescription:"Коллекция копий геометрии Иерархия: IDispatch IKompasAPIObject IKompasCollection IModelObjects ICopiesGeometry Интерфейс можно получить у интерфейса контейнера 3D объектов",
hmPrevLink:"icontours3d_add.html",
hmNextLink:"icopiesgeometry_props.html",
hmParentLink:"imodelobjects_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс ICopiesGeometry ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ICopiesGeometry <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2396662\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Коллекция копий геометрии<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"imodelobjects.html\" class=\"topiclink\">IModelObjects<\/a><\/span><\/p>\n\r<p class=\"p_Hier_4_BLUE\"><span class=\"f_Hier_4_BLUE\"><a href=\"icopiesgeometry.html\" class=\"topiclink\">ICopiesGeometry<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить у интерфейса контейнера 3D объектов <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelcontainer.html\" class=\"topiclink\">IModelContainer<\/a><\/span><span class=\"f_bodytext\"> с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelcontainer_copiesgeometry.html\" class=\"topiclink\">IModelContainer::CopiesGeometry<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icopiesgeometry_props.html\" class=\"topiclink hmlinklistitem\">ICopiesGeometry - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icopiesgeometry_methods.html\" class=\"topiclink hmlinklistitem\">ICopiesGeometry - методы <\/a><\/span><\/p>\n\r"
})
