hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ICurveStyle",
hmDescription:"Интерфейс стиля линии. Иерархия: IDispatch IKompasAPIObject IStyle ICurveStyle Примечание: Интерфейс можно получить с помощью методов коллекции стилей линий, полученной с",
hmPrevLink:"istyle_update.html",
hmNextLink:"icurvestyle_propers.html",
hmParentLink:"be1729661.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"be1729661.html\">Работа со стилями&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Работа со стилями  > Интерфейс ICurveStyle ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ICurveStyle <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbe1745804\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс стиля линии<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"istyle.html\" class=\"topiclink\">IStyle<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"icurvestyle.html\" class=\"topiclink\">ICurveStyle<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить с помощью методов коллекции стилей линий, полученной с помощью<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\">метода <\/span><span class=\"f_bulleted\" style=\"text-decoration: underline;\"><a href=\"istylesmanager_curvesstyles.html\" class=\"topiclink\">IStylesManager::CurvesStyles<\/a><\/span><span class=\"f_bulleted\">,<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\">коллекции стилей библиотеки стилей линий (*.lcs) <\/span><span class=\"f_bulleted\" style=\"text-decoration: underline;\"><a href=\"iapplication_librarystyles.html\" class=\"topiclink\">IApplication::LibraryStyles<\/a><\/span><span class=\"f_bulleted\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия: KOMPAS v19<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icurvestyle_propers.html\" class=\"topiclink hmlinklistitem\">ICurveStyle - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icurvestyle_methods.html\" class=\"topiclink hmlinklistitem\">ICurveStyle - методы <\/a><\/span><\/p>\n\r"
})
