hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ICuts",
hmDescription:"Интерфейс коллекции операций Сечение. Иерархия: IDispatch IKompasAPIObject IKompasCollection IModelObjects ICuts Данный интерфейс можно получить, используя свойство контей",
hmPrevLink:"icurveoutlines_add.html",
hmNextLink:"icuts_propers.html",
hmParentLink:"imodelobjects_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс ICuts ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ICuts <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2878142\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции операций Сечение.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"imodelobjects.html\" class=\"topiclink\">IModelObjects<\/a><\/span><\/p>\n\r<p class=\"p_Hier_4_BLUE\"><span class=\"f_Hier_4_BLUE\"><a href=\"icuts.html\" class=\"topiclink\">ICuts<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить, используя свойство контейнера трехмерных объектов <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelcontainer_cuts.html\" class=\"topiclink\">IModelContainer::Cuts<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">КОМПАС версияv18<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icuts_propers.html\" class=\"topiclink hmlinklistitem\">ICuts - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"icuts_methods.html\" class=\"topiclink hmlinklistitem\">ICuts - методы <\/a><\/span><\/p>\n\r"
})
