hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IDismantleParameters",
hmDescription:"Интерфейс параметров разнесения сборки. Иерархия: IDispatch IDismantleParameters Примечание: Интерфейс может быть получен в качестве дополнительного для интерфейса IAssemblyDo",
hmPrevLink:"bc3308967.html",
hmNextLink:"idismantleparameters_props.html",
hmParentLink:"bc3308967.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc3308967.html\">Сборка&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Сборка  > Интерфейс IDismantleParameters ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IDismantleParameters <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc3310039\" class=\"hmanchor\"><\/a><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров разнесения сборки<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"idismantleparameters.html\" class=\"topiclink\">IDismantleParameters<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс может быть получен в качестве дополнительного для интерфейса <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iassemblydocument.html\" class=\"topiclink\">IAssemblyDocument<\/a><\/span><span class=\"f_bodytext\"> посредством вызова метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"recomendation.html\" class=\"topiclink\">IUnknown::QueryInterface (const GUID far&amp; IID, void** pif)<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия: Компас v20<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idismantleparameters_props.html\" class=\"topiclink hmlinklistitem\">IDismantleParameters - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idismantleparameters_methods.html\" class=\"topiclink hmlinklistitem\">IDismantleParameters - методы <\/a><\/span><\/p>\n\r"
})
