hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IDocumentFrame",
hmDescription:"Интерфейс событий... Интерфейс окна документа. IKompasAPIObject IDocumentFrame IFrameTreesManager Примечание: 1. Данный интерфейс может быть получен от интерфейса окон доку",
hmPrevLink:"ba1782194.html",
hmNextLink:"idocumentframe_props.html",
hmParentLink:"ba1782194.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"doc.html\">Документ&nbsp;<\/a> &gt; <a href=\"ba1782194.html\">Окна документа&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ  > Окна документа  > Интерфейс IDocumentFrame ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IDocumentFrame <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xba1812599\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocumentframenotify.html\" class=\"topiclink\">Интерфейс событий...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс окна документа<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"idocumentframe.html\" class=\"topiclink\">IDocumentFrame<\/a><\/span><\/p>\n\r<p class=\"p_Hier_ADD\"><span class=\"f_Hier_ADD\"><a href=\"iframetreesmanager.html\" class=\"topiclink\">IFrameTreesManager<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Данный интерфейс может быть получен от интерфейса окон документа <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"idocumentframes.html\" class=\"topiclink\">IDocumentFrames<\/a><\/span><span class=\"f_Numbered\"> с помощью свойства <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"idocumentframes_item.html\" class=\"topiclink\">IDocumentFrames::Item<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. У данного интерфейса посредством вызова метода <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"recomendation.html\" class=\"topiclink\">IUnknown::QueryInterface (const GUID far&amp; IID, void** pif)<\/a><\/span><span class=\"f_Numbered\"> можно получить дополнительный интерфейс <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iframetreesmanager.html\" class=\"topiclink\">IFrameTreesManager<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idocumentframe_props.html\" class=\"topiclink hmlinklistitem\">IDocumentFrame - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idocumentframe_methods.html\" class=\"topiclink hmlinklistitem\">IDocumentFrame - методы <\/a><\/span><\/p>\n\r"
})
