hmLoadTopic({
hmKeywords:"",
hmTitle:"IDrawingObject1 - свойства",
hmDescription:"Подразделы: AutoTransparentBackground - Включение\/отключение управления очисткой фона под объектом через настройку документа  Constraints - Массив SAFEARRAY ограничений для...",
hmPrevLink:"idrawingobject1.html",
hmNextLink:"idrawingobject1_autotransparentbackground.html",
hmParentLink:"idrawingobject1.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2391397.html\">Ограничения&nbsp;<\/a> &gt; <a href=\"idrawingobject1.html\">Интерфейс IDrawingObject1&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Ограничения  > Интерфейс IDrawingObject1  > IDrawingObject1 - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IDrawingObject1 - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_autotransparentbackground.html\" class=\"topiclink hmlinklistitem\">AutoTransparentBackground - Включение\/отключение управления очисткой фона под объектом через настройку документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_constraints.html\" class=\"topiclink hmlinklistitem\">Constraints - Массив SAFEARRAY ограничений для данного объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"constraintsstate.html\" class=\"topiclink hmlinklistitem\">ConstraintsState - Параметрическое состояние эскиза<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_id.html\" class=\"topiclink hmlinklistitem\">Id - Идентификатор объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_isannotativeobject.html\" class=\"topiclink hmlinklistitem\">IsAnnotativeObject - Признак аннотационного объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_iscurve.html\" class=\"topiclink hmlinklistitem\">IsCurve - Объект является кривой <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_isgeometryobject.html\" class=\"topiclink hmlinklistitem\">IsGeometryObject - Признак геометрического объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_isinassociationview.html\" class=\"topiclink hmlinklistitem\">IsInAssociationView - Объект является ассоциативным <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_isvisibleinassociationview.html\" class=\"topiclink hmlinklistitem\">IsVisibleInAssociationView - Получить признак видимости ассоциативного объекта на ассоциативном виде <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobject1_transparentbackground.html\" class=\"topiclink hmlinklistitem\">TransparentBackground - Включение\/отключение очистки фона под аннотационным объектом <\/a><\/span><\/p>\n\r"
})
