hmLoadTopic({
hmKeywords:"",
hmTitle:"IDrawingObjects",
hmDescription:"Базовый интерфейс для коллекций графических объектов.",
hmPrevLink:"ilayerfilterconditions_add.html",
hmNextLink:"idrawingobjects_props.html",
hmParentLink:"view_layers.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"view_layers.html\">Виды и слои&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Виды и слои  > IDrawingObjects ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IDrawingObjects <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2326735\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Базовый интерфейс для коллекций графических объектов.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"idrawingobjects.html\" class=\"topiclink\">IDrawingObjects<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Данный интерфейс является базовым для коллекций графических объектов.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Интерфейс может быть получен с помощью метода IUnknown:: QueryInterface от интерфейса коллекции конкретных объектов, например, от интерфейса видов <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iviews.html\" class=\"topiclink\">IViews<\/a><\/span><span class=\"f_Numbered\">, слоев <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"ilayers.html\" class=\"topiclink\">ILayers<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingobjects_props.html\" class=\"topiclink hmlinklistitem\">IDrawingObjects - свойства <\/a><\/span><\/p>\n\r"
})
