hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IDrawingDocumentSettings",
hmDescription:"Настройки чертежа. Иерархия: IDispatch IDrawingDocumentSettings Описание: Настройки могут быть для текущего документа (можно получить у документа) и для новых документов (мо",
hmPrevLink:"adjstment.html",
hmNextLink:"idrawingdocumentsettings_props.html",
hmParentLink:"adjstment.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"adjstment.html\">Работа с настройками&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Работа с настройками  > Интерфейс IDrawingDocumentSettings ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IDrawingDocumentSettings <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbe1720754\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Настройки чертежа.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"idrawingdocumentsettings.html\" class=\"topiclink\">IDrawingDocumentSettings<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Настройки могут быть для текущего документа (можно получить у документа) и для новых документов (можно получить у приложения).<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить от интерфейса документа <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument.html\" class=\"topiclink\">IKompasDocument<\/a><\/span><span class=\"f_bodytext\"> с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument_documentsettings.html\" class=\"topiclink\">IKompasDocument::DocumentSettings<\/a><\/span><span class=\"f_bodytext\"> с последующим использованием метода IUnknown QueryInterface для преобразования от интерфейса <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"idocumentsettings.html\" class=\"topiclink\">IDocumentSettings<\/a><\/span><span class=\"f_bodytext\"> к данному интерфейсу.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idrawingdocumentsettings_props.html\" class=\"topiclink hmlinklistitem\">IDrawingDocumentSettings - свойства <\/a><\/span><\/p>\n\r"
})
