hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IDynamicCrossSectionStepParametersByOffsetPlane",
hmDescription:"Интерфейс параметров шага динамического сечения по смещенной плоскости.",
hmPrevLink:"idynamiccrosssectionstepparametersbyfreeplane_reversedirection.html",
hmNextLink:"idynamiccrosssectionstepparametersbyoffsetplane_props.html",
hmParentLink:"cu1734180.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"service.html\">Сервисные функции&nbsp;<\/a> &gt; <a href=\"cu1734180.html\">Динамическое сечение&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Сервисные функции  > Динамическое сечение  > Интерфейс IDynamicCrossSectionStepParametersByOffsetPlane ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IDynamicCrossSectionStepParametersByOffsetPlane <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcu1734698\" class=\"hmanchor\"><\/a><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс <\/span><span class=\"f_bodytext\">п<\/span><span class=\"f_bodytext\" style=\"font-weight: bold;\">араметров шага динамического сечения по смещенной плоскости.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"idynamiccrosssectionstepparametersbyoffsetplane.html\" class=\"topiclink\">IDynamicCrossSectionStepParametersByOffsetPlane<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить с помощью метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"idynamiccrosssectionstep_parameters.html\" class=\"topiclink\">IDynamicCrossSectionStep::Parameters<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия Компас v18.1<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idynamiccrosssectionstepparametersbyoffsetplane_props.html\" class=\"topiclink hmlinklistitem\">IDynamicCrossSectionStepParametersByOffsetPlane - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"idynamiccrosssectionstepparametersbyoffsetplane_methods.html\" class=\"topiclink hmlinklistitem\">IDynamicCrossSectionStepParametersByOffsetPlane - методы <\/a><\/span><\/p>\n\r"
})
