hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IEllipses",
hmDescription:"Интерфейс коллекции эллипсов. Иерархия: IKompasAPIObject IKompasCollection IDrawingObjects IEllipses Описание: Позволяет создавать и получать эллипсы на чертеже. Примечан",
hmPrevLink:"iellipsearcs_add.html",
hmNextLink:"iellipses_props.html",
hmParentLink:"bb2333035.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2333035.html\">Геометрия&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Геометрия  > Интерфейс IEllipses ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IEllipses <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2334307\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции эллипсов.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"idrawingobjects.html\" class=\"topiclink\">IDrawingObjects<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"iellipses.html\" class=\"topiclink\">IEllipses<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Позволяет создавать и получать эллипсы на чертеже.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Получить интерфейс можно, используя метод контейнера графических объектов <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"idrawingcontainer_ellipses.html\" class=\"topiclink\">IDrawingContainer::Ellipses<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipses_props.html\" class=\"topiclink hmlinklistitem\">IEllipses - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipses_methods.html\" class=\"topiclink hmlinklistitem\">IEllipses - методы <\/a><\/span><\/p>\n\r"
})
