hmLoadTopic({
hmKeywords:"",
hmTitle:"IEllipse - свойства",
hmDescription:"Подразделы: Angle - Угол наклона первой полуоси  SemiAxisA - Длина первой полуоси  SemiAxisB - Длина второй полуоси  Style - Cтиль линии  Xc - Координата центра эллипса по оси",
hmPrevLink:"iellipse.html",
hmNextLink:"iellipse_angle.html",
hmParentLink:"iellipse.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2333035.html\">Геометрия&nbsp;<\/a> &gt; <a href=\"iellipse.html\">Интерфейс IEllipse&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Геометрия  > Интерфейс IEllipse  > IEllipse - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IEllipse - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_angle.html\" class=\"topiclink hmlinklistitem\">Angle - Угол наклона первой полуоси <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_semiaxisa.html\" class=\"topiclink hmlinklistitem\">SemiAxisA - Длина первой полуоси <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_semiaxisb.html\" class=\"topiclink hmlinklistitem\">SemiAxisB - Длина второй полуоси <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_style.html\" class=\"topiclink hmlinklistitem\">Style - Cтиль линии <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_xc.html\" class=\"topiclink hmlinklistitem\">Xc - Координата центра эллипса по оси X <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_x1.html\" class=\"topiclink hmlinklistitem\">X1 - Координата конечной точки первой полуоси по оси X <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_x2.html\" class=\"topiclink hmlinklistitem\">X2 - Координата конечной точки второй полуоси по оси X <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_yc.html\" class=\"topiclink hmlinklistitem\">Yc - Координата центра эллипса по оси Y <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_y1.html\" class=\"topiclink hmlinklistitem\">Y1 - Координата конечной точки первой полуоси по оси Y <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iellipse_y2.html\" class=\"topiclink hmlinklistitem\">Y2 - Координата конечной точки второй полуоси по оси Y <\/a><\/span><\/p>\n\r"
})
