hmLoadTopic({
hmKeywords:"",
hmTitle:"IEmbodimentsManager - свойства",
hmDescription:"Подразделы: CurrentEmbodiment - Текущее исполнение  CurrentEmbodimentIndex - Индекс текущего исполнения  Embodiment - Получить исполнение по индексу или обозначению  Embodiment",
hmPrevLink:"iembodimentsmanager.html",
hmNextLink:"iembodimentsmanager_currentembodiment.html",
hmParentLink:"iembodimentsmanager.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2609111.html\">Компоненты&nbsp;<\/a> &gt; <a href=\"iembodimentsmanager.html\">Интерфейс IEmbodimentsManager&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Компоненты  > Интерфейс IEmbodimentsManager  > IEmbodimentsManager - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IEmbodimentsManager - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iembodimentsmanager_currentembodiment.html\" class=\"topiclink hmlinklistitem\">CurrentEmbodiment - Текущее исполнение <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iembodimentsmanager_currentembodimentindex.html\" class=\"topiclink hmlinklistitem\">CurrentEmbodimentIndex - Индекс текущего исполнения <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iembodimentsmanager_embodiment.html\" class=\"topiclink hmlinklistitem\">Embodiment - Получить исполнение по индексу или обозначению <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iembodimentsmanager_embodimentadditionalnumber.html\" class=\"topiclink hmlinklistitem\">EmbodimentAdditionalNumber - Дополнительный номер исполнения модели, использованного для вставки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iembodimentsmanager_embodimentcount.html\" class=\"topiclink hmlinklistitem\">EmbodimentCount - Количество исполнений <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iembodimentsmanager_topembodiment.html\" class=\"topiclink hmlinklistitem\">TopEmbodiment - Основное исполнение <\/a><\/span><\/p>\n\r"
})
