hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IEquidistants3D",
hmDescription:"Коллекция 3D-эквидистант. Иерархия IKompasAPIObject IKompasCollection IModelObjects IEquidistants3D Описание: Позволяет создавать и получать эквидистанты в 3D документе.",
hmPrevLink:"idraftsfromedges_add.html",
hmNextLink:"iequidistants3d_props.html",
hmParentLink:"imodelobjects_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс IEquidistants3D ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IEquidistants3D <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2108756\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Коллекция 3D-эквидистант.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"imodelobjects.html\" class=\"topiclink\">IModelObjects<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"iequidistants3d.html\" class=\"topiclink\">IEquidistants3D<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Позволяет создавать и получать эквидистанты в 3D документе.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить у контейнера вспомогательной геометрии <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iauxiliarygeomcontainer_equidistants3d.html\" class=\"topiclink\">IAuxiliaryGeomContainer::Equidistants3D<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iequidistants3d_props.html\" class=\"topiclink hmlinklistitem\">IEquidistants3D - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iequidistants3d_methods.html\" class=\"topiclink hmlinklistitem\">IEquidistants3D - методы <\/a><\/span><\/p>\n\r"
})
