hmLoadTopic({
hmKeywords:"",
hmTitle:"IExternalTessellationManager - методы",
hmDescription:"Подразделы: Add - Добавить объект с внешней триангуляцией  AddGDIObject - Добавить внешний GDI- объект  Clear - Удалить все объекты  CreateTextureImage - Создать изображение те",
hmPrevLink:"iexternaltessellationmanager_tessellationobject.html",
hmNextLink:"iexternaltessellationmanager_add.html",
hmParentLink:"iexternaltessellationmanager.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"doc.html\">Документ&nbsp;<\/a> &gt; <a href=\"ba1782194.html\">Окна документа&nbsp;<\/a> &gt; <a href=\"ba1848735.html\">OpenGL&nbsp;<\/a> &gt; <a href=\"iexternaltessellationmanager.html\">Интерфейс IExternalTessellationManager&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ  > Окна документа  > OpenGL  > Интерфейс IExternalTessellationManager  > IExternalTessellationManager - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IExternalTessellationManager - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_add.html\" class=\"topiclink hmlinklistitem\">Add - Добавить объект с внешней триангуляцией <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_addgdiobject.html\" class=\"topiclink hmlinklistitem\">AddGDIObject - Добавить внешний GDI- объект <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_clear.html\" class=\"topiclink hmlinklistitem\">Clear - Удалить все объекты <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_createtextureimage.html\" class=\"topiclink hmlinklistitem\">CreateTextureImage - Создать изображение текстуры <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_disablemodeldrawing.html\" class=\"topiclink hmlinklistitem\">DisableModelDrawing - Запретить отрисовку модели для указанных элементов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_ismodeldrawingenabled.html\" class=\"topiclink hmlinklistitem\">IsModelDrawingEnabled - Проверить, разрешена ли отрисовка для указанных элементов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_enablemodeldrawing.html\" class=\"topiclink hmlinklistitem\">EnableModelDrawing - Отменить последний запрет на отрисовку элементов модели <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_deleteobjects.html\" class=\"topiclink hmlinklistitem\">DeleteObjects - Удалить объекты <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_deletetextureimage.html\" class=\"topiclink hmlinklistitem\">DeleteTextureImage - Удалить изображение текстуры <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iexternaltessellationmanager_pickobjects.html\" class=\"topiclink hmlinklistitem\">PickObjects - Собрать объекты по лучу <\/a><\/span><\/p>\n\r"
})
