hmLoadTopic({
hmKeywords:"",
hmTitle:"IExtensionSurface - свойства",
hmDescription:"Подразделы: BuildingVectorParameters - Параметры вектора  DirObject - Объект, определяющий направление для типа построения По направлению  Edges - Массив ребер в виде SAFEARRAY",
hmPrevLink:"iextensionsurface.html",
hmNextLink:"iextensionsurface_buildingvectorparameters.html",
hmParentLink:"iextensionsurface.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2288197.html\">Поверхности&nbsp;<\/a> &gt; <a href=\"isurfacecontainer.html\">Интерфейс ISurfaceContainer&nbsp;<\/a> &gt; <a href=\"isurfacecontainer_props.html\">ISurfaceContainer - свойства&nbsp;<\/a> &gt; <a href=\"iextensionsurface.html\">Интерфейс IExtensionSurface&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Поверхности  > Интерфейс ISurfaceContainer  > ISurfaceContainer - свойства  > Интерфейс IExtensionSurface  > IExtensionSurface - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IExtensionSurface - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_buildingvectorparameters.html\" class=\"topiclink hmlinklistitem\">BuildingVectorParameters - Параметры вектора <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_dirobject.html\" class=\"topiclink hmlinklistitem\">DirObject - Объект, определяющий направление для типа построения По направлению <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_edges.html\" class=\"topiclink hmlinklistitem\">Edges - Массив ребер в виде SAFEARRAY DISPATCH - VT_ARRAY | VT_DISPATCH <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_extensionlimittype.html\" class=\"topiclink hmlinklistitem\">ExtensionLimitType - Способ ограничения <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_extensiontype.html\" class=\"topiclink hmlinklistitem\">ExtensionType - Тип продления поверхности <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_length.html\" class=\"topiclink hmlinklistitem\">Length - Длина (расстояние удлинения поверхности) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_sense.html\" class=\"topiclink hmlinklistitem\">Sense - Сменить направление <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_sideedges.html\" class=\"topiclink hmlinklistitem\">SideEdges - Боковые ребра <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iextensionsurface_targetobject.html\" class=\"topiclink hmlinklistitem\">TargetObject - Объект, до которого производится удлинение при способе построения До вершины <\/a><\/span><\/p>\n\r"
})
