hmLoadTopic({
hmKeywords:"",
hmTitle:"Edit - Редактировать элемент",
hmDescription:"Функция не поддерживается Интерфейс... Синтаксис Automation: IKompasDocument* Edit(); Синтаксис COM: HRESULT Edit ([out, retval] IKompasDocument** pVal); Возвращаемое значе",
hmPrevLink:"iinsert_delete.html",
hmNextLink:"ichecksum.html",
hmParentLink:"iinsert_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"library_maneger.html\">Менеджер библиотек&nbsp;<\/a> &gt; <a href=\"iinsert.html\">Интерфейс IInsert&nbsp;<\/a> &gt; <a href=\"iinsert_methods.html\">IInsert - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Менеджер библиотек  > Интерфейс IInsert  > IInsert - методы  > Edit - Редактировать элемент ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Edit - Редактировать элемент <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbd1748535\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Функция не поддерживается<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iinsert.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">IKompasDocument* Edit();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Edit ([out, retval] IKompasDocument** pVal);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Указатель на интерфейс <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument.html\" class=\"topiclink\">IKompasDocument<\/a><\/span><span class=\"f_Table_Cell\"> созданной вставки.<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Метод позволяет создать и добавить в библиотеку документ-вставку определенного типа. В библиотеки фрагментов можно вставлять фрагменты, в библиотеки моделей, как 3D модели, так и сборки. Имя вставки и папки в имени вставки отделяются символом &quot;|&quot;.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Пример &quot;детали|литье|фланец&quot;.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
