hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IInserts",
hmDescription:"Интерфейс коллекции элементов(документов) библиотеки.",
hmPrevLink:"ichecksum_clear.html",
hmNextLink:"iinserts_props.html",
hmParentLink:"library_maneger.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"library_maneger.html\">Менеджер библиотек&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Менеджер библиотек  > Интерфейс IInserts ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IInserts <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbd1736830\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции элементов(документов) библиотеки.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"iinserts.html\" class=\"topiclink\">IInserts<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет получить документы, входящие в библиотеку. Интерфейс можно получить при помощи свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iinsertslibrary_inserts.html\" class=\"topiclink\">IInsertsLibrary::Inserts<\/a><\/span><span class=\"f_bodytext\"> от интерфейса библиотеки элементов <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iinsertslibrary.html\" class=\"topiclink\">IInsertsLibrary<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iinserts_props.html\" class=\"topiclink hmlinklistitem\">IInserts - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iinserts_methods.html\" class=\"topiclink hmlinklistitem\">IInserts - методы <\/a><\/span><\/p>\n\r"
})
