hmLoadTopic({
hmKeywords:"",
hmTitle:"IKompasDocument - свойства",
hmDescription:"Подразделы: Active - Активность документа  Changed - Документ изменен  DocumentFrames - Интерфейс коллекции окон документа  DocumentSettings - Настройки документа  DocumentTyp",
hmPrevLink:"ikompasdocument.html",
hmNextLink:"ikompasdocument_active.html",
hmParentLink:"ikompasdocument.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"doc.html\">Документ&nbsp;<\/a> &gt; <a href=\"ba1711015.html\">Базовые интерфейсы&nbsp;<\/a> &gt; <a href=\"ikompasdocument.html\">Интерфейс IKompasDocument&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ  > Базовые интерфейсы  > Интерфейс IKompasDocument  > IKompasDocument - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IKompasDocument - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_active.html\" class=\"topiclink hmlinklistitem\">Active - Активность документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_changed.html\" class=\"topiclink hmlinklistitem\">Changed - Документ изменен <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_documentframes.html\" class=\"topiclink hmlinklistitem\">DocumentFrames - Интерфейс коллекции окон документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_documentsettings.html\" class=\"topiclink hmlinklistitem\">DocumentSettings - Настройки документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_documenttype.html\" class=\"topiclink hmlinklistitem\">DocumentType - Тип документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_layoutsheets.html\" class=\"topiclink hmlinklistitem\">LayoutSheets - Листы оформления <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_name.html\" class=\"topiclink hmlinklistitem\">Name - Имя документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_path.html\" class=\"topiclink hmlinklistitem\">Path - Путь к файлу документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_pathname.html\" class=\"topiclink hmlinklistitem\">PathName - Полное имя документа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_readonly.html\" class=\"topiclink hmlinklistitem\">ReadOnly - Только для чтения <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_specificationdescriptions.html\" class=\"topiclink hmlinklistitem\">SpecificationDescriptions - Описания спецификации <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ikompasdocument_visible.html\" class=\"topiclink hmlinklistitem\">Visible - Видимость документа <\/a><\/span><\/p>\n\r"
})
