hmLoadTopic({
hmKeywords:"",
hmTitle:"AddVariable - Создать переменную",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH AddVariable(); Синтаксис COM: HRESULT AddVariable( IVariable7 ** Result); Возвращаемое значение:  - указатель на интерфейс па",
hmPrevLink:"ikompasdocument2d1_adduserfuncvariable.html",
hmNextLink:"ikompasdocument2d1_changeobjectsorder.html",
hmParentLink:"ikompasdocument2d1_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"doc.html\">Документ&nbsp;<\/a> &gt; <a href=\"ba1711015.html\">Базовые интерфейсы&nbsp;<\/a> &gt; <a href=\"ikompasdocument2d1.html\">Интерфейс IKompasDocument2D1&nbsp;<\/a> &gt; <a href=\"ikompasdocument2d1_methods.html\">IKompasDocument2D1 - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ  > Базовые интерфейсы  > Интерфейс IKompasDocument2D1  > IKompasDocument2D1 - методы  > AddVariable - Создать переменную ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">AddVariable - Создать переменную <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xba1874921\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument2d1.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH AddVariable();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT AddVariable( IVariable7 ** Result);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс параметрической переменной <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ivariable7.html\" class=\"topiclink\">IVariable7<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Метод позволяет создать переменную (добавить переменную в массив переменных и документ).<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
