hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ILayerFilterConditions",
hmDescription:"Интерфейс коллекции условий фильтрации слоев. Иерархия: IKompasAPIObject IKompasCollection ILayerFilterConditions Описание: 1. Условия фильтрации используются для формирова",
hmPrevLink:"ilayergroups_detach.html",
hmNextLink:"ilayerfilterconditions_props.html",
hmParentLink:"view_layers.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"view_layers.html\">Виды и слои&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Виды и слои  > Интерфейс ILayerFilterConditions ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ILayerFilterConditions <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2326658\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции условий фильтрации слоев.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ilayerfilterconditions.html\" class=\"topiclink\">ILayerFilterConditions<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Условия фильтрации используются для формирования состава динамической группы слоев.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Слой автоматически будет включен в состав группы если его свойства удовлетворяют хотя бы одному из условий.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить через группу слоев <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ilayergroup.html\" class=\"topiclink\">ILayerGroup<\/a><\/span><span class=\"f_bodytext\"> с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ilayergroup_layerfilterconditions.html\" class=\"topiclink\">ILayerGroup::LayerFilterConditions<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilayerfilterconditions_props.html\" class=\"topiclink hmlinklistitem\">ILayerFilterConditions - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilayerfilterconditions_methods.html\" class=\"topiclink hmlinklistitem\">ILayerFilterConditions - методы <\/a><\/span><\/p>\n\r"
})
