hmLoadTopic({
hmKeywords:"",
hmTitle:"Attach - Добавить существующий слой",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL Attach( ILayer3D * PVal ); Синтаксис COM: HRESULT Attach( ILayer3D * PVal, BOOL * Result ); Возвращаемое значение: TRUE - в случае",
hmPrevLink:"ilayers3d_add.html",
hmNextLink:"ilayers3d_detach.html",
hmParentLink:"ilayers3d_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"service.html\">Сервисные функции&nbsp;<\/a> &gt; <a href=\"cu1735361.html\">Слои&nbsp;<\/a> &gt; <a href=\"ilayers3d.html\">Интерфейс ILayers3D&nbsp;<\/a> &gt; <a href=\"ilayers3d_methods.html\">ILayers3D - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Сервисные функции  > Слои  > Интерфейс ILayers3D  > ILayers3D - методы  > Attach - Добавить существующий слой ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Attach - Добавить существующий слой <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcu1735591\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ilayers3d.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL Attach( ILayer3D * PVal );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Attach( ILayer3D * PVal, BOOL * Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае успешного завершения,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">FALSE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае неудачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
