hmLoadTopic({
hmKeywords:"",
hmTitle:"ILibraryManager - свойства",
hmDescription:"Подразделы: ActiveFolder - Активная папка в окне Менеджера библиотек  ActiveFolderComment - Комментарий активной папки  CurrentLibrary - Текущая прикладная библиотека  Document",
hmPrevLink:"ilibrarymanager.html",
hmNextLink:"ilibrarymanager_activefolder.html",
hmParentLink:"ilibrarymanager.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"library_maneger.html\">Менеджер библиотек&nbsp;<\/a> &gt; <a href=\"ilibrarymanager.html\">Интерфейс ILibraryManager&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Менеджер библиотек  > Интерфейс ILibraryManager  > ILibraryManager - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ILibraryManager - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_activefolder.html\" class=\"topiclink hmlinklistitem\">ActiveFolder - Активная папка в окне Менеджера библиотек <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_activefoldercomment.html\" class=\"topiclink hmlinklistitem\">ActiveFolderComment - Комментарий активной папки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_currentlibrary.html\" class=\"topiclink hmlinklistitem\">CurrentLibrary - Текущая прикладная библиотека <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_documentslibraries.html\" class=\"topiclink hmlinklistitem\">DocumentsLibraries - Коллекция библиотек документов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_fragmentslibraries.html\" class=\"topiclink hmlinklistitem\">FragmentsLibraries - Коллекция библиотек фрагментов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_layout.html\" class=\"topiclink hmlinklistitem\">Layout - Положение Менеджера библиотек (вверху, внизу, слева, справа, плавающий) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_modelslibraries.html\" class=\"topiclink hmlinklistitem\">ModelsLibraries - Коллекция библиотек моделей <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_procedureslibraries.html\" class=\"topiclink hmlinklistitem\">ProceduresLibraries - Коллекция прикладных библиотек <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_systemcontrolstartlibrary.html\" class=\"topiclink hmlinklistitem\">SystemControlStartLibrary - Получить прикладную библиотеку, которая запустила SystemControlStart <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_systemcontrolstartresult.html\" class=\"topiclink hmlinklistitem\">SystemControlStartResult - Получить результат работы SystemControlStart <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilibrarymanager_visible.html\" class=\"topiclink hmlinklistitem\">Visible - Свойство видимости Менеджера библиотек <\/a><\/span><\/p>\n\r"
})
