hmLoadTopic({
hmKeywords:"",
hmTitle:"Centres - Координаты центров осевых линий",
hmDescription:"Интерфейс... Тип данных: VARIANT Синтаксис Automation: Centres = Object.Centres Получить свойство(* ) Centres = Object.GetCentres() Получить свойство (**) Синтаксис COM:",
hmPrevLink:"ilinearcentres_baseobjects.html",
hmNextLink:"ilinearcentres_hasbreaks.html",
hmParentLink:"ilinearcentres_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"obozn_razm.html\">Обозначения и размеры&nbsp;<\/a> &gt; <a href=\"bb3219840.html\">Обозначения&nbsp;<\/a> &gt; <a href=\"ilinearcentres.html\">Интерфейс ILinearCentres&nbsp;<\/a> &gt; <a href=\"ilinearcentres_props.html\">ILinearCentres - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Обозначения и размеры  > Обозначения  > Интерфейс ILinearCentres  > ILinearCentres - свойства  > Centres - Координаты центров осевых линий ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Centres - Координаты центров осевых линий <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2837649\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ilinearcentres.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Тип данных: VARIANT<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Centres = Object.Centres<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство(<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Centres = Object.GetCentres()<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Object.get_Centres( &amp;Centres )<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Свойство доступно только для чтения.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
