hmLoadTopic({
hmKeywords:"",
hmTitle:"ILocalCoordinateSystem - методы",
hmDescription:"Подразделы: GetVector - Получить вектора направлений главных осей  InitByMatrix3D - Установить систему координат по матрице  ReadFromFile - Прочитать файл с данными  SetAssocia",
hmPrevLink:"ilocalcoordinatesystem_z.html",
hmNextLink:"ilocalcoordinatesystem_getvector.html",
hmParentLink:"ilocalcoordinatesystem.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2278808.html\">Операции, массивы, эскизы, точки&nbsp;<\/a> &gt; <a href=\"bc2284065.html\">Точки&nbsp;<\/a> &gt; <a href=\"ipoint3d.html\">Интерфейс IPoint3D&nbsp;<\/a> &gt; <a href=\"bc2284488.html\">Наследники - вспомогательные объекты&nbsp;<\/a> &gt; <a href=\"ilocalcoordinatesystem.html\">Интерфейс ILocalCoordinateSystem&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Операции, массивы, эскизы, точки  > Точки  > Интерфейс IPoint3D  > Наследники - вспомогательные объекты  > Интерфейс ILocalCoordinateSystem  > ILocalCoordinateSystem - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ILocalCoordinateSystem - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_getvector.html\" class=\"topiclink hmlinklistitem\">GetVector - Получить вектора направлений главных осей <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_initbymatrix3d.html\" class=\"topiclink hmlinklistitem\">InitByMatrix3D - Установить систему координат по матрице <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_readfromfile.html\" class=\"topiclink hmlinklistitem\">ReadFromFile - Прочитать файл с данными <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_setassociationobject.html\" class=\"topiclink hmlinklistitem\">SetAssociationObject - Установить опорный объект <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_setdisplacementbyaxis.html\" class=\"topiclink hmlinklistitem\">SetDisplacementByAxis - Установить смещение по оси <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_setstartingorientation.html\" class=\"topiclink hmlinklistitem\">SetStartingOrientation - Установить исходное положение ЛСК <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_update.html\" class=\"topiclink hmlinklistitem\">Update - Изменить свойства объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ilocalcoordinatesystem_writetofile.html\" class=\"topiclink hmlinklistitem\">WriteToFile - Записать файл с данными <\/a><\/span><\/p>\n\r"
})
