hmLoadTopic({
hmKeywords:"",
hmTitle:"IMacroObject - свойства",
hmDescription:"Подразделы: AttachedLeaders - Присоединенные линии выноски  BreakObjectsEnabled - Учитывать разрыв вида  Command - Номер команды редактирования  CreateSpcObjects - Создавать об",
hmPrevLink:"imacroobject.html",
hmNextLink:"imacroobject_attachedleaders.html",
hmParentLink:"imacroobject.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2346750.html\">Макрообъекты&nbsp;<\/a> &gt; <a href=\"imacroobject.html\">Интерфейс IMacroObject&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Макрообъекты  > Интерфейс IMacroObject  > IMacroObject - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IMacroObject - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_attachedleaders.html\" class=\"topiclink hmlinklistitem\">AttachedLeaders - Присоединенные линии выноски <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_breakobjectsenabled.html\" class=\"topiclink hmlinklistitem\">BreakObjectsEnabled - Учитывать разрыв вида <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_command.html\" class=\"topiclink hmlinklistitem\">Command - Номер команды редактирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_createspcobjects.html\" class=\"topiclink hmlinklistitem\">CreateSpcObjects - Создавать объекты спецификации <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_doubleclickeditable.html\" class=\"topiclink hmlinklistitem\">DoubleClickEditable - Редактирование по двойному клику поддерживается <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_hotpointseditable.html\" class=\"topiclink hmlinklistitem\">HotPointsEditable - Редактирование при помощи характерных точек поддерживается <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_externaleditable.html\" class=\"topiclink hmlinklistitem\">ExternalEditable - Поддерживается интерфейс внешнего управления <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_label.html\" class=\"topiclink hmlinklistitem\">Label - Отображаемое имя объекта в дереве <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_libraryfilename.html\" class=\"topiclink hmlinklistitem\">LibraryFileName - Имя файла библиотеки, в которой находится функция редактирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_libraryname.html\" class=\"topiclink hmlinklistitem\">LibraryName - Имя библиотеки, в которой находится функция редактирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_name.html\" class=\"topiclink hmlinklistitem\">IName - Имя макроэлемента в Дереве чертежа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_propertyobjecteditable.html\" class=\"topiclink hmlinklistitem\">PropertyObjectEditable - Поддерживается интерфейс внешних свойств объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imacroobject_userparams.html\" class=\"topiclink hmlinklistitem\">UserParams - Массив SAFEARRAY байтов пользовательских параметров объекта <\/a><\/span><\/p>\n\r"
})
