hmLoadTopic({
hmKeywords:"",
hmTitle:"IMate3DTransmission - свойства",
hmDescription:"Подразделы: Direction1 - Направление движения компонента 1. TRUE - направление 1, FALSE - направление 2  Direction2 - Направление движения компонента 2. TRUE - направление 1,...",
hmPrevLink:"imate3dtransmission.html",
hmNextLink:"imate3dtransmission_direction1.html",
hmParentLink:"imate3dtransmission.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2609111.html\">Компоненты&nbsp;<\/a> &gt; <a href=\"imateconstraint3d.html\">Интерфейс IMateConstraint3D&nbsp;<\/a> &gt; <a href=\"imateconstraint3d_methods.html\">IMateConstraint3D - методы&nbsp;<\/a> &gt; <a href=\"imate3dtransmission.html\">Интерфейс IMate3DTransmission&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Компоненты  > Интерфейс IMateConstraint3D  > IMateConstraint3D - методы  > Интерфейс IMate3DTransmission  > IMate3DTransmission - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IMate3DTransmission - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_direction1.html\" class=\"topiclink hmlinklistitem\">Direction1 - Направление движения компонента 1. TRUE - направление 1, FALSE - направление 2 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_direction2.html\" class=\"topiclink hmlinklistitem\">Direction2 - Направление движения компонента 2. TRUE - направление 1, FALSE - направление 2 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_motiontype1.html\" class=\"topiclink hmlinklistitem\">MotionType1 - Тип движения компонента 1 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_motiontype2.html\" class=\"topiclink hmlinklistitem\">MotionType2 - Тип движения компонента 2 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_rotationaxis1.html\" class=\"topiclink hmlinklistitem\">RotationAxis1 - Ось вращения компонента 1 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_rotationaxis2.html\" class=\"topiclink hmlinklistitem\">RotationAxis2 - Ось вращения компонента 2 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_scale1.html\" class=\"topiclink hmlinklistitem\">Scale1 - Коэффициент соотношения для 1-го компонента <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_scale2.html\" class=\"topiclink hmlinklistitem\">Scale2 - Коэффициент соотношения для 2-го компонента <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_trajectory1.html\" class=\"topiclink hmlinklistitem\">Trajectory1 - Траектория перемещения компонента 1 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imate3dtransmission_trajectory2.html\" class=\"topiclink hmlinklistitem\">Trajectory2 - Траектория перемещения компонента 2 <\/a><\/span><\/p>\n\r"
})
