hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IModelContainer",
hmDescription:"Интерфейс контейнера трехмерных объектов. Иерархия: IDispatch IModelContainer Описание. Интерфейс позволяет работать с коллекциями 3D-объектов, входящих в состав 3D-объекта.",
hmPrevLink:"bc2278809.html",
hmNextLink:"imodelcontainer_props.html",
hmParentLink:"bc2278809.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2278808.html\">Операции, массивы, эскизы, точки&nbsp;<\/a> &gt; <a href=\"bc2278809.html\">Контейнер&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Операции, массивы, эскизы, точки  > Контейнер  > Интерфейс IModelContainer ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IModelContainer <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2278811\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс контейнера трехмерных объектов<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"imodelcontainer.html\" class=\"topiclink\">IModelContainer<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет работать с коллекциями 3D-объектов, входящих в состав 3D-объекта.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс контейнера является дополнительным к интерфейсу <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ipart7.html\" class=\"topiclink\">IPart7<\/a><\/span><span class=\"f_bodytext\">. Данный интерфейс можно получить от IPart7 посредством вызова метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"recomendation.html\" class=\"topiclink\">IUnknown::QueryInterface (const GUID far&amp; iid, void** pif)<\/a><\/span><span class=\"f_bodytext\">;<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imodelcontainer_props.html\" class=\"topiclink hmlinklistitem\">IModelContainer - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imodelcontainer_methods.html\" class=\"topiclink hmlinklistitem\">IModelContainer - методы <\/a><\/span><\/p>\n\r"
})
