hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IMoldCavity",
hmDescription:"Интерфейс операции вычитания компонентов. Иерархия: IDispatch IKompasAPIObject IModelObject IMoldCavity Данный интерфейс можно получить с помощью метода коллекции операций",
hmPrevLink:"imate3dtransmission_setscale.html",
hmNextLink:"imoldcavity_propers.html",
hmParentLink:"imateconstraint3d_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2609111.html\">Компоненты&nbsp;<\/a> &gt; <a href=\"imateconstraint3d.html\">Интерфейс IMateConstraint3D&nbsp;<\/a> &gt; <a href=\"imateconstraint3d_methods.html\">IMateConstraint3D - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Компоненты  > Интерфейс IMateConstraint3D  > IMateConstraint3D - методы  > Интерфейс IMoldCavity ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IMoldCavity <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2753591\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс операции вычитания компонентов<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"imodelobject.html\" class=\"topiclink\">IModelObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"imoldcavity.html\" class=\"topiclink\">IMoldCavity<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить с помощью метода коллекции операций по сечениям <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imoldcavities_add.html\" class=\"topiclink\">IMoldCavities::Add<\/a><\/span><span class=\"f_bodytext\"> или свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imoldcavities_moldcavity.html\" class=\"topiclink\">IMoldCavities::MoldCavity<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">КОМПАС версия v18<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"imoldcavity_propers.html\" class=\"topiclink hmlinklistitem\">IMoldCavity - свойства <\/a><\/span><\/p>\n\r"
})
