hmLoadTopic({
hmKeywords:"",
hmTitle:"Symbol - Символ, отображаемый в поле документа, при наведении на контрол",
hmDescription:"Интерфейс... Тип данных: long Синтаксис Automation: Symbol = Object.Symbol Получить свойство (* ) Object.Symbol = Symbol Установить свойство (* ) Symbol = Object.GetSymbol",
hmPrevLink:"imouseenterleaveparameters_offsetangle.html",
hmNextLink:"imouseenterleaveparameters_symbolcolor.html",
hmParentLink:"imouseenterleaveparameters_propers.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"imouseenterleaveparameters.html\">Параметры отображения точки, позволяющей определить место применения контрола (Интерфейс IMouseEnterLeaveParameters)&nbsp;<\/a> &gt; <a href=\"imouseenterleaveparameters_propers.html\">IMouseEnterLeaveParameters - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Параметры отображения точки, позволяющей определить место применения контрола (Интерфейс IMouseEnterLeaveParameters)  > IMouseEnterLeaveParameters - свойства  > Symbol - Символ, отображаемый в поле документа, при наведении на контрол ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Symbol - Символ, отображаемый в поле документа, при наведении на контрол <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcb1789755\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imouseenterleaveparameters.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Тип данных: long<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Symbol = Object.Symbol<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Object.Symbol = Symbol<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Установить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Symbol = Object.GetSymbol()<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство(<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Object.SetSymbol( Symbol )<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Установить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
