hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс INurbs",
hmDescription:"Интерфейс NURBS-кривой. Иерархия: IDispatch IKompasAPIObject IDrawingObject INurbs Описание: Интерфейс позволяет задавать параметры NURBS-кривой. Примечание: 1. Интерфей",
hmPrevLink:"imultiline_findline.html",
hmNextLink:"inurbs_props.html",
hmParentLink:"bb2333035.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2333035.html\">Геометрия&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Геометрия  > Интерфейс INurbs ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс INurbs <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2340420\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс NURBS-кривой.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"idrawingobject.html\" class=\"topiclink\">IDrawingObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"inurbs.html\" class=\"topiclink\">INurbs<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет задавать параметры NURBS-кривой.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Интерфейс можно получить у коллекции NURBS-кривых, используя свойство <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"inurbses_nurbs.html\" class=\"topiclink\">INurbses::Nurbs<\/a><\/span><span class=\"f_Numbered\"> или метод <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"inurbses_add.html\" class=\"topiclink\">INurbses::Add<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. После задания параметров NURBS-кривой требуется вызвать метод <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"idrawingobject_update.html\" class=\"topiclink\">IDrawingObject::Update<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"inurbs_props.html\" class=\"topiclink hmlinklistitem\">INurbs - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"inurbs_methods.html\" class=\"topiclink hmlinklistitem\">INurbs - методы <\/a><\/span><\/p>\n\r"
})
