hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IPlane3DTangentToFaceInPoint",
hmDescription:"Плоскость касательная к грани в точке 3D. Иерархия: IDispatch IKompasAPIObject IModelObject IPlane3D IPlane3DTangentToFaceInPoint Подразделы: IPlane3DTangentToFaceInPoint",
hmPrevLink:"iplane3dbyplanecurve_curve.html",
hmNextLink:"iplane3dtangenttofaceinpoint_props.html",
hmParentLink:"iplane3d_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2288197.html\">Поверхности&nbsp;<\/a> &gt; <a href=\"isurfacecontainer.html\">Интерфейс ISurfaceContainer&nbsp;<\/a> &gt; <a href=\"isurfacecontainer_props.html\">ISurfaceContainer - свойства&nbsp;<\/a> &gt; <a href=\"iplane3d.html\">Интерфейс IPlane3D&nbsp;<\/a> &gt; <a href=\"iplane3d_props.html\">IPlane3D - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Поверхности  > Интерфейс ISurfaceContainer  > ISurfaceContainer - свойства  > Интерфейс IPlane3D  > IPlane3D - свойства  > Интерфейс IPlane3DTangentToFaceInPoint ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IPlane3DTangentToFaceInPoint <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2292486\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Плоскость касательная к грани в точке 3D.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"imodelobject.html\" class=\"topiclink\">IModelObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"iplane3d.html\" class=\"topiclink\">IPlane3D<\/a><\/span><\/p>\n\r<p class=\"p_Hier_4_BLUE\"><span class=\"f_Hier_4_BLUE\"><a href=\"iplane3dtangenttofaceinpoint.html\" class=\"topiclink\">IPlane3DTangentToFaceInPoint<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iplane3dtangenttofaceinpoint_props.html\" class=\"topiclink hmlinklistitem\">IPlane3DTangentToFaceInPoint - свойства <\/a><\/span><\/p>\n\r"
})
