hmLoadTopic({
hmKeywords:"",
hmTitle:"IPolyLine - методы",
hmDescription:"Подразделы: AddVertex - Создать новую вершину  DeleteVertex - Удалить вершину с указанным индексом  ErrorIndexes - Массив не скругленных вершин SAFEARRAY - VT_ARRAY | VT_I4  Fl",
hmPrevLink:"ipolyline_vertexvisible.html",
hmNextLink:"ipolyline_addvertex.html",
hmParentLink:"ipolyline.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a> &gt; <a href=\"ipolyline.html\">Интерфейс IPolyLine&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс IPolyLine  > IPolyLine - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IPolyLine - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_addvertex.html\" class=\"topiclink hmlinklistitem\">AddVertex - Создать новую вершину <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_deletevertex.html\" class=\"topiclink hmlinklistitem\">DeleteVertex - Удалить вершину с указанным индексом <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_errorindexes.html\" class=\"topiclink hmlinklistitem\">ErrorIndexes - Массив не скругленных вершин SAFEARRAY - VT_ARRAY | VT_I4 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_flush.html\" class=\"topiclink hmlinklistitem\">Flush - Очистить массив вершин <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_getvertexcoordinatesarray.html\" class=\"topiclink hmlinklistitem\">GetVertexCoordinatesArray - Получить массив координати радиусов вершин в виде SAFEARRAY double - VT_ARRAY | VT_R8 <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_readfromfile.html\" class=\"topiclink hmlinklistitem\">ReadFromFile - Прочитать параметры вершин из текстового файла <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipolyline_writetofile.html\" class=\"topiclink hmlinklistitem\">WriteToFile - Записать параметры вершин в текстовый файл <\/a><\/span><\/p>\n\r"
})
