hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IProcess",
hmDescription:"Интерфейс процесса. Иерархия: IDispatch IKompasAPIObject IProcess Примечание: Интерфейс можно получить с помощью методов: IKompasDocument2D1::LibProcess IKompasDocument3D",
hmPrevLink:"iprocessparam_setsetupmenucommandstate.html",
hmNextLink:"iprocess_propers.html",
hmParentLink:"ap1803662.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap1803662.html\">Параметры процесса&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Параметры процесса  > Интерфейс IProcess ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IProcess <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xap1849690\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс процесса.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"iprocess.html\" class=\"topiclink\">IProcess<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить с помощью методов:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument2d1_libprocess.html\" class=\"topiclink\">IKompasDocument2D1::LibProcess<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument3d1_libprocess.html\" class=\"topiclink\">IKompasDocument3D1::LibProcess<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iprocess_propers.html\" class=\"topiclink hmlinklistitem\">IProcess - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iprocess_methods.html\" class=\"topiclink hmlinklistitem\">IProcess - методы <\/a><\/span><\/p>\n\r"
})
