hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IProcessParam",
hmDescription:"Интерфейс событий... Интерфейс параметров процесса. Иерархия: IKompasAPIObject IProcessParam Примечание: 1. Интерфейс позволяет управлять параметрами процесса. 2. Данный и",
hmPrevLink:"ap1803662.html",
hmNextLink:"iprocessparam_props.html",
hmParentLink:"ap1803662.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap1803662.html\">Параметры процесса&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Параметры процесса  > Интерфейс IProcessParam ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IProcessParam <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xap1713530\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kspropertymanagernotify.html\" class=\"topiclink\">Интерфейс событий...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров процесса<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"iprocessparam.html\" class=\"topiclink\">IProcessParam<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Интерфейс позволяет управлять параметрами процесса.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Данный интерфейс может быть получен от интерфейса приложения <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iapplication.html\" class=\"topiclink\">IApplication<\/a><\/span><span class=\"f_Numbered\"> с помощью свойства <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iapplication_createprocessparam.html\" class=\"topiclink\">IApplication::CreateProcessParam<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iprocessparam_props.html\" class=\"topiclink hmlinklistitem\">IProcessParam - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iprocessparam_methods.html\" class=\"topiclink hmlinklistitem\">IProcessParam - методы <\/a><\/span><\/p>\n\r"
})
