hmLoadTopic({
hmKeywords:"",
hmTitle:"IPropertyEditList - свойства",
hmDescription:"Подразделы: AllowDelete - Разрешить удалять элементы из списка  CheckState - Состояние контрола. Текущий, Не текущий  ComputeUniqueNames - Генерация уникальных имен элементов",
hmPrevLink:"ipropertyeditlist.html",
hmNextLink:"ipropertyeditlist_allowdelete.html",
hmParentLink:"ipropertyeditlist.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap2037561.html\">Работа с Панелью свойств&nbsp;<\/a> &gt; <a href=\"ipropertycontrol.html\">Интерфейс IPropertyControl&nbsp;<\/a> &gt; <a href=\"ipropertycontrol_props.html\">IPropertyControl - свойства&nbsp;<\/a> &gt; <a href=\"ipropertyeditlist.html\">Интерфейс IPropertyEditList&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Работа с Панелью свойств  > Интерфейс IPropertyControl  > IPropertyControl - свойства  > Интерфейс IPropertyEditList  > IPropertyEditList - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IPropertyEditList - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_allowdelete.html\" class=\"topiclink hmlinklistitem\">AllowDelete - Разрешить удалять элементы из списка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_checkstate.html\" class=\"topiclink hmlinklistitem\">CheckState - Состояние контрола. Текущий, Не текущий <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_computeuniquenames.html\" class=\"topiclink hmlinklistitem\">ComputeUniqueNames - Генерация уникальных имен элементов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_defaultvalue.html\" class=\"topiclink hmlinklistitem\">DefaultValue - Значение по умолчанию <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_itemmissing.html\" class=\"topiclink hmlinklistitem\">ItemMissing - Потерянный объект <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_itemchecked.html\" class=\"topiclink hmlinklistitem\">ItemChecked - Состояние элемента списка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_itemscount.html\" class=\"topiclink hmlinklistitem\">ItemsCount - Количество элементов в списке <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_itemselected.html\" class=\"topiclink hmlinklistitem\">ItemSelected - Состояние выделенности элемента списка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_itemvalue.html\" class=\"topiclink hmlinklistitem\">ItemValue - Значение элемента списка по индексу <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_listtype.html\" class=\"topiclink hmlinklistitem\">ListType - Тип списка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_multyselect.html\" class=\"topiclink hmlinklistitem\">MultySelect - Возможность множественного выделения <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertyeditlist_sort.html\" class=\"topiclink hmlinklistitem\">Sort - Состояние сортированности списка <\/a><\/span><\/p>\n\r"
})
