hmLoadTopic({
hmKeywords:"",
hmTitle:"Add- Добавить значение в список",
hmDescription:"Интерфейс... Синтаксис Automation: void Add( BSTR NewStr, VARIANT NewBmp ); Синтаксис COM: HRESULT Add( BSTR NewStr, VARIANT NewBmp ); Входные параметры: NewStr - добавляемо",
hmPrevLink:"ipropertybmplist_methods.html",
hmNextLink:"ipropertybmplist_clearlist.html",
hmParentLink:"ipropertybmplist_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap2037561.html\">Работа с Панелью свойств&nbsp;<\/a> &gt; <a href=\"ipropertycontrol.html\">Интерфейс IPropertyControl&nbsp;<\/a> &gt; <a href=\"ipropertycontrol_props.html\">IPropertyControl - свойства&nbsp;<\/a> &gt; <a href=\"ipropertybmplist.html\">Интерфейс IPropertyBmpList&nbsp;<\/a> &gt; <a href=\"ipropertybmplist_methods.html\">IPropertyBmpList - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Работа с Панелью свойств  > Интерфейс IPropertyControl  > IPropertyControl - свойства  > Интерфейс IPropertyBmpList  > IPropertyBmpList - методы  > Add- Добавить значение в список ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Add- Добавить значение в список <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ipropertybmplist.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">void Add( BSTR NewStr, VARIANT NewBmp );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Add( BSTR NewStr, VARIANT NewBmp );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">NewStr<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- добавляемое значение,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">NewBmp<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- идентификатор значка в файле ресурсов (тип данных long) или полный путь к bmp-файлу значка (тип данных BSTR).<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
