hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IPropertyTabs",
hmDescription:"Интерфейс коллекции вкладок Панели свойств. Иерархия: IKompasAPIObject IKompasCollection IPropertyTabs Примечание: Данный интерфейс может быть получен от интерфейса парамет",
hmPrevLink:"ipropertycontrols_delete.html",
hmNextLink:"ipropertytabs_props.html",
hmParentLink:"ipropertytoolbar.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap2037561.html\">Работа с Панелью свойств&nbsp;<\/a> &gt; <a href=\"ipropertytoolbar.html\">Интерфейс IPropertyToolBar&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Работа с Панелью свойств  > Интерфейс IPropertyToolBar  > Интерфейс IPropertyTabs ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IPropertyTabs <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xap1763470\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции вкладок Панели свойств<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ipropertytabs.html\" class=\"topiclink\">IPropertyTabs<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс может быть получен от интерфейса параметров процесса <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iprocessparam.html\" class=\"topiclink\">IProcessParam<\/a><\/span><span class=\"f_bodytext\"> с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iprocessparam_propertytabs.html\" class=\"topiclink\">IProcessParam::PropertyTabs<\/a><\/span><span class=\"f_bodytext\"> или от интерфейса панели свойств <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ipropertymanager.html\" class=\"topiclink\">IPropertyManager<\/a><\/span><span class=\"f_bodytext\"> с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ipropertymanager_propertytabs.html\" class=\"topiclink\">IPropertyManager::PropertyTabs<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertytabs_props.html\" class=\"topiclink hmlinklistitem\">IPropertyTabs - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ipropertytabs_methods.html\" class=\"topiclink hmlinklistitem\">IPropertyTabs - методы <\/a><\/span><\/p>\n\r"
})
