hmLoadTopic({
hmKeywords:"",
hmTitle:"Add - Добавить массив стилей в список",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL Add( VARIANT Styles ); Синтаксис COM: HRESULT Add( VARIANT Styles, BOOL * Result ); Входные параметры: Styles - список стилей. Возвр",
hmPrevLink:"ipropertystylelist_methods.html",
hmNextLink:"ipropertystylelist_clearlist.html",
hmParentLink:"ipropertystylelist_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"ap1782828.html\">Приложение&nbsp;<\/a> &gt; <a href=\"ap2037561.html\">Работа с Панелью свойств&nbsp;<\/a> &gt; <a href=\"ipropertycontrol.html\">Интерфейс IPropertyControl&nbsp;<\/a> &gt; <a href=\"ipropertycontrol_props.html\">IPropertyControl - свойства&nbsp;<\/a> &gt; <a href=\"ipropertystylelist.html\">Интерфейс IPropertyStyleList&nbsp;<\/a> &gt; <a href=\"ipropertystylelist_methods.html\">IPropertyStyleList - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Приложение  > Работа с Панелью свойств  > Интерфейс IPropertyControl  > IPropertyControl - свойства  > Интерфейс IPropertyStyleList  > IPropertyStyleList - методы  > Add - Добавить массив стилей в список ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Add - Добавить массив стилей в список <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ipropertystylelist.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL Add( VARIANT Styles );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Add( VARIANT Styles, BOOL * Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Styles<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- список стилей.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае удачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Если добавляется один стиль, его можно передать как VT_I4.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Если требуется добавить несколько стилей, то нужно создать массив VT_ARRAY | VT_I4.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
