hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IRadialDimensions",
hmDescription:"Интерфейс коллекции радиальных размеров. Иерархия: IKompasAPIObject IKompasCollection IDrawingObjects IRadialDimensions Описание: Интерфейс позволяет получать и создавать",
hmPrevLink:"ilinedimensions_addlinesegmentandpointdimension.html",
hmNextLink:"iradialdimensions_props.html",
hmParentLink:"bb2356897.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"obozn_razm.html\">Обозначения и размеры&nbsp;<\/a> &gt; <a href=\"bb2356896.html\">Размеры&nbsp;<\/a> &gt; <a href=\"bb2356897.html\">Коллекции размеров&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Обозначения и размеры  > Размеры  > Коллекции размеров  > Интерфейс IRadialDimensions ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IRadialDimensions <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb3217842\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции радиальных размеров<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"idrawingobjects.html\" class=\"topiclink\">IDrawingObjects<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"iradialdimensions.html\" class=\"topiclink\">IRadialDimensions<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет получать и создавать радиальные размеры.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить у контейнера условных обозначений, используя свойство <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"isymbols2dcontainer_radialdimensions.html\" class=\"topiclink\">ISymbols2DContainer::RadialDimensions<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iradialdimensions_props.html\" class=\"topiclink hmlinklistitem\">IRadialDimensions - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iradialdimensions_methods.html\" class=\"topiclink hmlinklistitem\">IRadialDimensions - методы <\/a><\/span><\/p>\n\r"
})
