hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IRegularPolygon",
hmDescription:"Интерфейс многоугольника. Иерархия: IDispatch IKompasAPIObject IDrawingObject IRegularPolygon Описание: Интерфейс позволяет задавать параметры многоугольника. Примечание:",
hmPrevLink:"irectangle_setcorner.html",
hmNextLink:"iregularpolygon_props.html",
hmParentLink:"bb2333035.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2333035.html\">Геометрия&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Геометрия  > Интерфейс IRegularPolygon ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IRegularPolygon <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2341780\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс многоугольника.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"idrawingobject.html\" class=\"topiclink\">IDrawingObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"iregularpolygon.html\" class=\"topiclink\">IRegularPolygon<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет задавать параметры многоугольника.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Интерфейс можно получить у коллекции многоугольников, используя свойство <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iregularpolygons_regularpolygon.html\" class=\"topiclink\">IRegularPolygons::RegularPolygon<\/a><\/span><span class=\"f_Numbered\"> или метод <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"iregularpolygons_add.html\" class=\"topiclink\">IRegularPolygons::Add<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. После задания параметров многоугольника требуется вызвать метод <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"idrawingobject_update.html\" class=\"topiclink\">IDrawingObject::Update<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iregularpolygon_props.html\" class=\"topiclink hmlinklistitem\">IRegularPolygon - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iregularpolygon_methods.html\" class=\"topiclink hmlinklistitem\">IRegularPolygon - методы <\/a><\/span><\/p>\n\r"
})
