hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ISheetMetalSketchBends",
hmDescription:"Интерфейс коллекции элементов Сгиб по эскизу. Иерархия: IDispatch IKompasAPIObject IKompasCollection IModelObjects ISheetMetalSketchBends Данный интерфейс можно получить, ис",
hmPrevLink:"isheetmetalrib_initbendobjects.html",
hmNextLink:"isheetmetalsketchbends_propers.html",
hmParentLink:"isheetmetalcontainer_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2753655.html\">Листовое тело&nbsp;<\/a> &gt; <a href=\"isheetmetalcontainer.html\">Интерфейс ISheetMetalContainer&nbsp;<\/a> &gt; <a href=\"isheetmetalcontainer_props.html\">ISheetMetalContainer - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Листовое тело  > Интерфейс ISheetMetalContainer  > ISheetMetalContainer - свойства  > Интерфейс ISheetMetalSketchBends ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ISheetMetalSketchBends <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2760022\" class=\"hmanchor\"><\/a><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс коллекции элементов Сгиб по эскизу.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ikompascollection.html\" class=\"topiclink\">IKompasCollection<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"imodelobjects.html\" class=\"topiclink\">IModelObjects<\/a><\/span><\/p>\n\r<p class=\"p_Hier_4_BLUE\"><span class=\"f_Hier_4_BLUE\"><a href=\"isheetmetalsketchbends.html\" class=\"topiclink\">ISheetMetalSketchBends<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить, используя свойство контейнера объектов гибки <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"isheetmetalcontainer_sheetmetalsketchbends.html\" class=\"topiclink\">ISheetMetalContainer::SheetMetalSketchBends<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">КОМПА версия v18<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"isheetmetalsketchbends_propers.html\" class=\"topiclink hmlinklistitem\">ISheetMetalSketchBends - cвойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"isheetmetalsketchbends_methods.html\" class=\"topiclink hmlinklistitem\">ISheetMetalSketchBends - методы <\/a><\/span><\/p>\n\r"
})
