hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ISheetMetalBendedStraighten",
hmDescription:"Интерфейс операции Согнуть\/Разогнуть. Иерархия: IDispatch IKompasAPIObject IModelObject ISheetMetalBendedStraighten Данный интерфейс можно получить с помощью метода коллекции",
hmPrevLink:"isheetmetalbend_width.html",
hmNextLink:"isheetmetalbendedstraighten_propers.html",
hmParentLink:"isheetmetalcontainer_props.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2753655.html\">Листовое тело&nbsp;<\/a> &gt; <a href=\"isheetmetalcontainer.html\">Интерфейс ISheetMetalContainer&nbsp;<\/a> &gt; <a href=\"isheetmetalcontainer_props.html\">ISheetMetalContainer - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Листовое тело  > Интерфейс ISheetMetalContainer  > ISheetMetalContainer - свойства  > Интерфейс ISheetMetalBendedStraighten ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ISheetMetalBendedStraighten <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2878870\" class=\"hmanchor\"><\/a><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс операции Согнуть\/Разогнуть<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"imodelobject.html\" class=\"topiclink\">IModelObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"isheetmetalbendedstraighten.html\" class=\"topiclink\">ISheetMetalBendedStraighten<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить с помощью метода коллекции операций по сечениям <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"isheetmetalbendedstraightens_add.html\" class=\"topiclink\">ISheetMetalBendedStraightens::Add<\/a><\/span><span class=\"f_bodytext\"> или свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"isheetmetalbendedstraightens_sheetmetalbendedstraighten.html\" class=\"topiclink\">ISheetMetalBendedStraightens::SheetMetalBendedStraighten<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">КОМПАС версия v18<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"isheetmetalbendedstraighten_propers.html\" class=\"topiclink hmlinklistitem\">ISheetMetalBendedStraighten - свойства <\/a><\/span><\/p>\n\r"
})
