hmLoadTopic({
hmKeywords:"",
hmTitle:"GetPoint - Точка привязки",
hmDescription:"Интерфейс... Синтаксис COM: BOOL GetPoint( double * x, double * y ); Выходные параметры: x, y - координаты точки привязки. Подразделы: (отсутствуют)",
hmPrevLink:"isnapinfo_getobject2.html",
hmNextLink:"isnapinfo_getsnaptype1.html",
hmParentLink:"isnapinfo_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"isnapinfo.html\">ИнIтерфейс информации о текущей привязке (Интерфейс ISnapInfo)&nbsp;<\/a> &gt; <a href=\"isnapinfo_methods.html\">ISnapInfo - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > ИнIтерфейс информации о текущей привязке (Интерфейс ISnapInfo)  > ISnapInfo - методы  > GetPoint - Точка привязки ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetPoint - Точка привязки <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xch1800606\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"isnapinfo.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL GetPoint( double * x, double * y );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Выходные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">x, y<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- координаты точки привязки.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
