hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ISpecRough",
hmDescription:"Неуказанная шероховатость. Иерархия: IDispatch IKompasAPIObject ISpecRough Описание: Интерфейс позволяет задавать и получать параметры неуказанной шероховатости. Примечани",
hmPrevLink:"isheetformat_verticalorientation.html",
hmNextLink:"ispecrough_props.html",
hmParentLink:"bb2345331.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2345331.html\">Листы и оформление&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Листы и оформление  > Интерфейс ISpecRough ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ISpecRough <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2345919\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Неуказанная шероховатость.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ispecrough.html\" class=\"topiclink\">ISpecRough<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет задавать и получать параметры неуказанной шероховатости.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить у интерфейса чертежа с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"idrawingdocument_specrough.html\" class=\"topiclink\">IDrawingDocument::SpecRough<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispecrough_props.html\" class=\"topiclink hmlinklistitem\">ISpecRough - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispecrough_methods.html\" class=\"topiclink hmlinklistitem\">ISpecRough - методы <\/a><\/span><\/p>\n\r"
})
