hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ISpecificationColumnStyle",
hmDescription:"Интерфейс стиля колонки спецификации. Иерархия: IKompasAPIObject ISpecificationColumnStyle Примечание: Данный интерфейс можно получить от интерфейса стиля колонки спецификац",
hmPrevLink:"ispecificationcolumnitem_visible.html",
hmNextLink:"ispecificationcolumnstyle_props.html",
hmParentLink:"spec_work.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"spec_work.html\">Работа со спецификацией&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Работа со спецификацией  > Интерфейс ISpecificationColumnStyle ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ISpecificationColumnStyle <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbf1810725\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс стиля колонки спецификации.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"ispecificationcolumnstyle.html\" class=\"topiclink\">ISpecificationColumnStyle<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данный интерфейс можно получить от интерфейса стиля колонки спецификации <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ispecificationcolumnstyles.html\" class=\"topiclink\">ISpecificationColumnStyles<\/a><\/span><span class=\"f_bodytext\">, используя свойство <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ispecificationcolumnstyles_item.html\" class=\"topiclink\">ISpecificationColumnStyles::Item<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispecificationcolumnstyle_props.html\" class=\"topiclink hmlinklistitem\">ISpecificationColumnStyle - свойства <\/a><\/span><\/p>\n\r"
})
