hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ISpecRough3D",
hmDescription:"Интерфейс неуказанной шероховатости 3D. Иерархия: IDispatch IKompasAPIObject ISpecRough3D Интерфейс можно получить с помощью свойства IKompasDocument3D1::SpecRough. Подразд",
hmPrevLink:"bc2278536.html",
hmNextLink:"ispecrough3d_props.html",
hmParentLink:"bc2278536.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2273863.html\">Оформление&nbsp;<\/a> &gt; <a href=\"bc2278536.html\">Неуказанная шероховатость&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Оформление  > Неуказанная шероховатость  > Интерфейс ISpecRough3D ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ISpecRough3D <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2278538\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс неуказанной шероховатости 3D.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"ispecrough3d.html\" class=\"topiclink\">ISpecRough3D<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить с помощью свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument3d1_specrough.html\" class=\"topiclink\">IKompasDocument3D1::SpecRough<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispecrough3d_props.html\" class=\"topiclink hmlinklistitem\">ISpecRough3D - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispecrough3d_methods.html\" class=\"topiclink hmlinklistitem\">ISpecRough3D - методы <\/a><\/span><\/p>\n\r"
})
