hmLoadTopic({
hmKeywords:"",
hmTitle:"ISpline3DMetaSplineParam - свойства",
hmDescription:"Подразделы: ApproximationType - Способ аппроксимации DensityDegree - Уплотнение FairSmoothing - Сглаживание Elevate - Повышенный порядок кривой Безье Harmony - Гармонизация ра",
hmPrevLink:"ispline3dmetasplineparam.html",
hmNextLink:"ispline3dmetasplineparam_approximationtype.html",
hmParentLink:"ispline3dmetasplineparam.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a> &gt; <a href=\"ispline3dmetasplineparam.html\">Интерфейс ISpline3DMetaSplineParam<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс ISpline3DMetaSplineParam > ISpline3DMetaSplineParam - свойства",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ISpline3DMetaSplineParam - свойства<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_approximationtype.html\" class=\"topiclink hmlinklistitem\">ApproximationType - Способ аппроксимации<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_densitydegree.html\" class=\"topiclink hmlinklistitem\">DensityDegree - Уплотнение<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_fairsmoothing.html\" class=\"topiclink hmlinklistitem\">FairSmoothing - Сглаживание<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_elevate.html\" class=\"topiclink hmlinklistitem\">Elevate - Повышенный порядок кривой Безье<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_harmony.html\" class=\"topiclink hmlinklistitem\">Harmony - Гармонизация распределения точек по кривой<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_metasplinebuildingtype.html\" class=\"topiclink hmlinklistitem\">MetaSplineBuildingType - Способ построения кривой<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ispline3dmetasplineparam_smoothingmethod.html\" class=\"topiclink hmlinklistitem\">SmoothingMethod - Метод сглаживания<\/a><\/span><\/p>\n\r"
})
