hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IStylesManager",
hmDescription:"Менеджер стилей. Иерархия: IDispatch IStylesManager Примечание: Интерфейс является дополнительным для интерфейсов: IApplication - позволяет получать системные стили. IKomp",
hmPrevLink:"be1729661.html",
hmNextLink:"istylesmanager_propers.html",
hmParentLink:"be1729661.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"be1729661.html\">Работа со стилями&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Работа со стилями  > Интерфейс IStylesManager ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IStylesManager <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbe1741184\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Менеджер стилей<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"istylesmanager.html\" class=\"topiclink\">IStylesManager<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс является дополнительным для интерфейсов:<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\" style=\"text-decoration: underline;\"><a href=\"iapplication.html\" class=\"topiclink\">IApplication<\/a><\/span><span class=\"f_bulleted\"> - позволяет получать системные стили.<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\" style=\"text-decoration: underline;\"><a href=\"ikompasdocument.html\" class=\"topiclink\">IKompasDocument<\/a><\/span><span class=\"f_bulleted\"> - позволяет получать\\создавать пользовательские стили.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить посредством вызова метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"recomendation.html\" class=\"topiclink\">IUnknown::QueryInterface<\/a><\/span><span class=\"f_bodytext\"> (const GUID far&amp; iid, void** pif).<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия KOMPAS v19<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"istylesmanager_propers.html\" class=\"topiclink hmlinklistitem\">IStylesManager- свойства <\/a><\/span><\/p>\n\r"
})
