hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ISurfaceThickening",
hmDescription:"Интерфейс операции придания толщины поверхности. Иерархия: IDispatch IKompasAPIObject IModelObject ISurfaceThickening IThinParameters Интерфейс позволяет придать толщину г",
hmPrevLink:"iscaling3d_setcentrepoint.html",
hmNextLink:"isurfacethickening_props.html",
hmParentLink:"bc2279073.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2278808.html\">Операции, массивы, эскизы, точки&nbsp;<\/a> &gt; <a href=\"bc2279073.html\">Операции&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Операции, массивы, эскизы, точки  > Операции  > Интерфейс ISurfaceThickening ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ISurfaceThickening <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2280606\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс операции придания толщины поверхности<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_GREEN\"><span class=\"f_Hier_1_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"imodelobject.html\" class=\"topiclink\">IModelObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_3_BLUE\"><span class=\"f_Hier_3_BLUE\"><a href=\"isurfacethickening.html\" class=\"topiclink\">ISurfaceThickening<\/a><\/span><\/p>\n\r<p class=\"p_Hier_4_BLUE\"><span class=\"f_Hier_4_BLUE\"><a href=\"ithinparameters.html\" class=\"topiclink\">IThinParameters<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет придать толщину граням тела или поверхности, т.е. добавить слой материала на эти грани. Сформированный слой материала представляет собой заполненное материалом пространство между исходной и эквидистантной поверхностями или двумя эквидистантными поверхностями.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Имеет дополнительный интерфейс <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ithinparameters.html\" class=\"topiclink\">IThinParameters.<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"isurfacethickening_props.html\" class=\"topiclink hmlinklistitem\">ISurfaceThickening - свойства <\/a><\/span><\/p>\n\r"
})
