hmLoadTopic({
hmKeywords:"",
hmTitle:"Delete - Удалить раздел",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL Delete(); Синтаксис COM: HRESULT Delete( BOOL * Result ); Возвращаемое значение: TRUE - в случае успешного завершения. Подразделы:",
hmPrevLink:"itextdocumentsection_update.html",
hmNextLink:"library_maneger.html",
hmParentLink:"itextdocumentsection_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bd1748865.html\">Текстовый документ&nbsp;<\/a> &gt; <a href=\"itextdocumentsection.html\">Интерфейс ITextDocumentSection&nbsp;<\/a> &gt; <a href=\"itextdocumentsection_methods.html\">ITextDocumentSection - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Текстовый документ  > Интерфейс ITextDocumentSection  > ITextDocumentSection - методы  > Delete - Удалить раздел ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Delete - Удалить раздел <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbd1751652\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"itextdocumentsection.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL Delete();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Delete( BOOL * Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае успешного завершения.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
