hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ITexturesParam",
hmDescription:"Интерфейс параметров наложения текстур. Иерархия: IDispatch ITexturesParam Интерфейс является дополнительным для интерфейса IColorParam7 объектов IModelObject. IPart7, IBody7",
hmPrevLink:"icolorparam7_setadvancedcolor.html",
hmNextLink:"itexturesparam_propers.html",
hmParentLink:"bc2297422.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2297422.html\">Свойства цвета объекта&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Свойства цвета объекта  > Интерфейс ITexturesParam ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ITexturesParam <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc3079822\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров наложения текстур<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_BLANK\"><span class=\"f_Hier_0_BLANK\">IDispatch<\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"itexturesparam.html\" class=\"topiclink\">ITexturesParam<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс является дополнительным для интерфейса <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"icolorparam7.html\" class=\"topiclink\">IColorParam7<\/a><\/span><span class=\"f_bodytext\"> объектов <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelobject.html\" class=\"topiclink\">IModelObject<\/a><\/span><span class=\"f_bodytext\">. <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ipart7.html\" class=\"topiclink\">IPart7<\/a><\/span><span class=\"f_bodytext\">, <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ibody7.html\" class=\"topiclink\">IBody7<\/a><\/span><span class=\"f_bodytext\">,<\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ilayer3d.html\" class=\"topiclink\">ILayer3D<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Для установки параметров отображения текстур для объектов модели требуется, чтобы у объекта был установлен признак использования собственного цвета,<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">т.е. свойство <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"icolorparam7_usecolor.html\" class=\"topiclink\">IColorParam7::UseColor<\/a><\/span><span class=\"f_bodytext\"> требуется установить равным useColorOur.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия: KOMPAS v19<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"itexturesparam_propers.html\" class=\"topiclink hmlinklistitem\">ITexturesParam - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"itexturesparam_methods.html\" class=\"topiclink hmlinklistitem\">ITexturesParam - методы <\/a><\/span><\/p>\n\r"
})
