hmLoadTopic({
hmKeywords:"",
hmTitle:"GetRecalc - Получить пересчет размеров по имени или индексу",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH GetRecalc( VARIANT Index ); Синтаксис СОМ: HRESULT GetRecalc( VARIANT Index, IToleranceRecalc ** Result ); Возвращаемое значени",
hmPrevLink:"itolerancerecalcsmanager_addrecalccopy.html",
hmNextLink:"itolerancerecalcsmanager_saverecalcmodel.html",
hmParentLink:"itolerancerecalcsmanager_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc2273863.html\">Оформление&nbsp;<\/a> &gt; <a href=\"bc2277893.html\">Пересчет модели с учетом допусков&nbsp;<\/a> &gt; <a href=\"itolerancerecalcsmanager.html\">Интерфейс IToleranceRecalcsManager&nbsp;<\/a> &gt; <a href=\"itolerancerecalcsmanager_methods.html\">IToleranceRecalcsManager- методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Оформление  > Пересчет модели с учетом допусков  > Интерфейс IToleranceRecalcsManager  > IToleranceRecalcsManager- методы  > GetRecalc - Получить пересчет размеров по имени или индексу ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetRecalc - Получить пересчет размеров по имени или индексу <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2278052\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"itolerancerecalcsmanager.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH GetRecalc( VARIANT Index );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис СОМ<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT GetRecalc( VARIANT Index, IToleranceRecalc ** Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><br \/>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс пересчета размеров <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"itolerancerecalc.html\" class=\"topiclink\">IToleranceRecalc<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Index<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- имя или индекс пересчета.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
