hmLoadTopic({
hmKeywords:"",
hmTitle:"GetIntersectParameters - Получить массивы точек пересечения кривой с секущими объектами",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL GetIntersectParameters( VARIANT * CutPoints1, VARIANT * CutPoints2 ); Синтаксис COM: HRESULT GetIntersectParameters( VARIANT * CutPoin",
hmPrevLink:"itrimmedcurve_methods.html",
hmNextLink:"iunhistoredcurve3d.html",
hmParentLink:"itrimmedcurve_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a> &gt; <a href=\"itrimmedcurve.html\">Интерфейс ITrimmedCurve&nbsp;<\/a> &gt; <a href=\"itrimmedcurve_methods.html\">ITrimmedCurve - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс ITrimmedCurve  > ITrimmedCurve - методы  > GetIntersectParameters - Получить массивы точек пересечения кривой с секущими объектами ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetIntersectParameters - Получить массивы точек пересечения кривой с секущими объектами <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2087847\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"itrimmedcurve.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL GetIntersectParameters( VARIANT * CutPoints1, VARIANT * CutPoints2 );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT GetIntersectParameters( VARIANT * CutPoints1, VARIANT * CutPoints2, BOOL * Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Выходные параметры<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">CutPoints1 - Массив VT_ARRAY | VT_R8 параметров в точках пересечения с первым секущим объектом.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">CutPoints2 - Массив VT_ARRAY | VT_R8 параметров в точках пересечения со вторым секущим объектом.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
