hmLoadTopic({
hmKeywords:"",
hmTitle:"Convert - Создает кривую без истории по кривой",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH Convert( IModelObject * Curve, BOOL DeleteSource ); Синтаксис COM: HRESULT Convert( IModelObject * Curve, BOOL DeleteSource, IUn",
hmPrevLink:"iunhistoredcurves3d_add.html",
hmNextLink:"iunhistoredcurves3d_load.html",
hmParentLink:"iunhistoredcurves3d_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bc1473974.html\">Документ 3D&nbsp;<\/a> &gt; <a href=\"bc1711351.html\">Вспомогательные объекты, 3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"bc2014000.html\">3D-кривые и элементы тела&nbsp;<\/a> &gt; <a href=\"imodelobjects.html\">Интерфейс IModelObjects&nbsp;<\/a> &gt; <a href=\"imodelobjects_props.html\">IModelObjects - свойства&nbsp;<\/a> &gt; <a href=\"iunhistoredcurves3d.html\">Интерфейс IUnhistoredCurves3D&nbsp;<\/a> &gt; <a href=\"iunhistoredcurves3d_methods.html\">IUnhistoredCurves3D - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 3D  > Вспомогательные объекты, 3D-кривые и элементы тела  > 3D-кривые и элементы тела  > Интерфейс IModelObjects  > IModelObjects - свойства  > Интерфейс IUnhistoredCurves3D  > IUnhistoredCurves3D - методы  > Convert - Создает кривую без истории по кривой ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Convert - Создает кривую без истории по кривой <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbc2249858\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iunhistoredcurves3d.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH Convert( IModelObject * Curve, BOOL DeleteSource );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT Convert( IModelObject * Curve, BOOL DeleteSource, IUnhistoredCurve3D ** Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">указатель на интерфейс кривой без истории <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"iunhistoredcurve3d.html\" class=\"topiclink\">IUnhistoredCurve3D<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Curve<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на исходную кривую,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">DeleteSource<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- удалить исходную кривую.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
