hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс IUnitNumber",
hmDescription:"Интерфейс номера узла. Иерархия: IKompasAPIObject IDrawingObject IUnitNumber Описание: Интерфейс позволяет получать и изменять свойства номеров узлов на чертеже. Примечани",
hmPrevLink:"iremoteelement_autozone.html",
hmNextLink:"iunitnumber_props.html",
hmParentLink:"bb2362006.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"bb2325661.html\">Документ 2D&nbsp;<\/a> &gt; <a href=\"bb2362006.html\">Обозначения для строительства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Документ 2D  > Обозначения для строительства  > Интерфейс IUnitNumber ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс IUnitNumber <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbb2368889\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс номера узла<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Иерархия<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Hier_0_GREEN\"><span class=\"f_Hier_0_GREEN\"><a href=\"ikompasapiobject.html\" class=\"topiclink\">IKompasAPIObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_1_BLUE\"><span class=\"f_Hier_1_BLUE\"><a href=\"idrawingobject.html\" class=\"topiclink\">IDrawingObject<\/a><\/span><\/p>\n\r<p class=\"p_Hier_2_BLUE\"><span class=\"f_Hier_2_BLUE\"><a href=\"iunitnumber.html\" class=\"topiclink\">IUnitNumber<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет получать и изменять свойства номеров узлов на чертеже.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс можно получить с помощью метода коллекции номеров узла <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iunitnumbers_add.html\" class=\"topiclink\">IUnitNumbers::Add<\/a><\/span><span class=\"f_bodytext\"> или свойства <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iunitnumbers_unitnumber.html\" class=\"topiclink\">IUnitNumbers::UnitNumber<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"iunitnumber_props.html\" class=\"topiclink hmlinklistitem\">IUnitNumber - свойства <\/a><\/span><\/p>\n\r"
})
