hmLoadTopic({
hmKeywords:"",
hmTitle:"AddZone - Добавить зону",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH AddZone( ksZoneTypeEnum ZoneType ); Синтаксис COM : HRESULT AddZone( ksZoneTypeEnum ZoneType, IZone ** Result ); Возвращаемое з",
hmPrevLink:"izonesmanager_methods.html",
hmNextLink:"izonesmanager_addzonedivision.html",
hmParentLink:"izonesmanager_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"service.html\">Сервисные функции&nbsp;<\/a> &gt; <a href=\"cu1735335.html\">Зоны&nbsp;<\/a> &gt; <a href=\"izonesmanager.html\">Интерфейс IZonesManager&nbsp;<\/a> &gt; <a href=\"izonesmanager_methods.html\">IZonesManager - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Сервисные функции  > Зоны  > Интерфейс IZonesManager  > IZonesManager - методы  > AddZone - Добавить зону ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">AddZone - Добавить зону <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcu1733505\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"izonesmanager.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH AddZone( ksZoneTypeEnum ZoneType );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\"> :<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">HRESULT AddZone( ksZoneTypeEnum ZoneType, IZone ** Result );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Указатель на интерфейс <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"izone.html\" class=\"topiclink\">IZone<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ZoneType<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- cпособ создания зоны из перечисления <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"kszonetypeenum.html\" class=\"topiclink\">ksZoneTypeEnum<\/a><\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
