hmLoadTopic({
hmKeywords:"",
hmTitle:"ksResultNULL - Обнулить результат работы библиотеки, если ошибка не фатальная",
hmDescription:"Интерфейс.... Аналог данного метода при использовании API экспортных функций - ResultNULL. Синтаксис Automation: long ksResultNULL(); Возвращаемое значение: 0 - если ошибок",
hmPrevLink:"kompasobject_ksremoveuniquefile.html",
hmNextLink:"kompasobject_kssetcriticalprocess.html",
hmParentLink:"ag92071.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"kompasobject.html\">KompasObject - Интерфейс API КОМПАС&nbsp;<\/a> &gt; <a href=\"kompasobject_methods.html\">KompasObject - методы&nbsp;<\/a> &gt; <a href=\"ag92071.html\">Сервисные функции&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > KompasObject - Интерфейс API КОМПАС  > KompasObject - методы  > Сервисные функции  > ksResultNULL - Обнулить результат работы библиотеки, если ошибка не фатальная ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksResultNULL - Обнулить результат работы библиотеки, если ошибка не фатальная <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xag160190\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данного метода при использовании API экспортных функций - <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"resultnull.html\" class=\"topiclink\">ResultNULL<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">long ksResultNULL();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">0<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- если ошибок не обнаружено,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">1<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- если ошибка была обнулена.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
