hmLoadTopic({
hmKeywords:"",
hmTitle:"IAdditionFormatParam - методы",
hmDescription:"Подразделы: Init - Инициализировать параметры  GetObjectsOptions - Получить признак чтения\\записи объектов модели  GetPlacement - Получить систему координат позиционирования мод",
hmPrevLink:"ksadditionformatparam_topolgyincluded.html",
hmNextLink:"ksadditionformatparam_init.html",
hmParentLink:"ksadditionformatparam.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"ksadditionformatparam.html\">Конвертация в дополнительные форматы (Интерфейсы ksAdditionFormatParam, IAdditionFormatParam)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Конвертация в дополнительные форматы (Интерфейсы ksAdditionFormatParam, IAdditionFormatParam)  > IAdditionFormatParam - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IAdditionFormatParam - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_init.html\" class=\"topiclink hmlinklistitem\">Init - Инициализировать параметры <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_getobjectsoptions.html\" class=\"topiclink hmlinklistitem\">GetObjectsOptions - Получить признак чтения\\записи объектов модели <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_getplacement.html\" class=\"topiclink hmlinklistitem\">GetPlacement - Получить систему координат позиционирования модели <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_loadconfigurationfile.html\" class=\"topiclink hmlinklistitem\">LoadConfigurationFile - Загрузить конфигурацию из файла <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_saveconfigurationfile.html\" class=\"topiclink hmlinklistitem\">SaveConfigurationFile - Сохранить конфигурацию в файл <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_setplacement.html\" class=\"topiclink hmlinklistitem\">SetPlacement - Установить систему координат позиционирования модели <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksadditionformatparam_setobjectsoptions.html\" class=\"topiclink hmlinklistitem\">SetObjectsOptions - Установить признак чтения\\записи объектов модели <\/a><\/span><\/p>\n\r"
})
