hmLoadTopic({
hmKeywords:"",
hmTitle:"GetViewParam - Получить указатель на интерфейс параметров обычного вида",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH GetViewParam(); Возвращаемое значение:   - Указатель на интерфейс ksViewParam. Примечание: Свойство используется только для в",
hmPrevLink:"ksassociationviewparam_gethatchparam.html",
hmNextLink:"ksassociationviewparam_init.html",
hmParentLink:"ksassociationviewparam_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ce1717197.html\">Интерфейсы параметров формата и компоновки чертежа&nbsp;<\/a> &gt; <a href=\"ksassociationviewparam.html\">Интерфейс параметров ассоциативного вида (Интерфейс ksAssociationViewParam)&nbsp;<\/a> &gt; <a href=\"ksassociationviewparam_methods.html\">ksAssociationViewParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров формата и компоновки чертежа  > Интерфейс параметров ассоциативного вида (Интерфейс ksAssociationViewParam)  > ksAssociationViewParam - методы  > GetViewParam - Получить указатель на интерфейс параметров обычного вида ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetViewParam - Получить указатель на интерфейс параметров обычного вида <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xce1801533\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksassociationviewparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH GetViewParam();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Указатель на интерфейс <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksviewparam.html\" class=\"topiclink\">ksViewParam<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Свойство используется только для видов типа разрез или сечение.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
