hmLoadTopic({
hmKeywords:"",
hmTitle:"IAttribute3DCollection - методы",
hmDescription:"Подразделы: FindIt - Получить индекс элемента массива  First - Получить указатель на интерфейс первого атрибута  GetCount - Получить количество элементов массива атрибутов  Get",
hmPrevLink:"ksattribute3dcollection.html",
hmNextLink:"ksattribute3dcollection_findit.html",
hmParentLink:"ksattribute3dcollection.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"ksfeature.html\">Объект Дерева построения (Интерфейсы ksFeature, IFeature)&nbsp;<\/a> &gt; <a href=\"ksattribute3dcollection.html\">Интерфейс массива атрибутов объектов модели (Интерфейсы ksAttribute3DCollection, IAttribute3DCollection)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект Дерева построения (Интерфейсы ksFeature, IFeature)  > Интерфейс массива атрибутов объектов модели (Интерфейсы ksAttribute3DCollection, IAttribute3DCollection)  > IAttribute3DCollection - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IAttribute3DCollection - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_findit.html\" class=\"topiclink hmlinklistitem\">FindIt - Получить индекс элемента массива <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_first.html\" class=\"topiclink hmlinklistitem\">First - Получить указатель на интерфейс первого атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_getcount.html\" class=\"topiclink hmlinklistitem\">GetCount - Получить количество элементов массива атрибутов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_getbyindex.html\" class=\"topiclink hmlinklistitem\">GetByIndex - Получить указатель на интерфейс атрибута по индексу <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_last.html\" class=\"topiclink hmlinklistitem\">Last - Получить указатель на интерфейс последнего атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_next.html\" class=\"topiclink hmlinklistitem\">Next - Получить указатель на интерфейс следующего атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_prev.html\" class=\"topiclink hmlinklistitem\">Prev - Получить указатель на интерфейс предыдущего атрибута <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_refresh.html\" class=\"topiclink hmlinklistitem\">Refresh - Обновить массив атрибутов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksattribute3dcollection_select.html\" class=\"topiclink hmlinklistitem\">Select - Выделить атрибуты данного типа или с данными ключами <\/a><\/span><\/p>\n\r"
})
