hmLoadTopic({
hmKeywords:"",
hmTitle:"ksAxis2PointsDefinition - методы",
hmDescription:"Подразделы: GetCurve3D - Получить указатель на интерфейс математической кривой  GetPoint - Получить указатель на интерфейс точки с указанным номером  SetPoint - Изменить указате",
hmPrevLink:"ksaxis2pointsdefinition.html",
hmNextLink:"ksaxis2pointsdefinition_getcurve3d.html",
hmParentLink:"ksaxis2pointsdefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_geometry.html\">Интерфейсы вспомогательной геометрии&nbsp;<\/a> &gt; <a href=\"ksaxis2pointsdefinition.html\">Ось через две точки (Интерфейсы ksAxis2PointsDefinition,IAxis2PointsDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы вспомогательной геометрии  > Ось через две точки (Интерфейсы ksAxis2PointsDefinition,IAxis2PointsDefinition)  > ksAxis2PointsDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksAxis2PointsDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksaxis2pointsdefinition_getcurve3d.html\" class=\"topiclink hmlinklistitem\">GetCurve3D - Получить указатель на интерфейс математической кривой <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksaxis2pointsdefinition_getpoint.html\" class=\"topiclink hmlinklistitem\">GetPoint - Получить указатель на интерфейс точки с указанным номером <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksaxis2pointsdefinition_setpoint.html\" class=\"topiclink hmlinklistitem\">SetPoint - Изменить указатель на интерфейс точки с указанным номером <\/a><\/span><\/p>\n\r"
})
