hmLoadTopic({
hmKeywords:"",
hmTitle:"GetEndPoint - Получить указатель на интерфейс параметров конечной точки",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH GetEndPoint(); Возвращаемое значение:   - указатель на интерфейс ksMathPointParam. Подразделы: (отсутствуют)",
hmPrevLink:"ksaxislineparam_getbegpoint.html",
hmNextLink:"ksaxislineparam_init.html",
hmParentLink:"ksaxislineparam_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cd1743949.html\">Интерфейсы параметров графических примитивов&nbsp;<\/a> &gt; <a href=\"ksaxislineparam.html\">Интерфейс параметров осевой линии (Интерфейс ksAxisLineParam)&nbsp;<\/a> &gt; <a href=\"ksaxislineparam_methods.html\">ksAxisLineParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров графических примитивов  > Интерфейс параметров осевой линии (Интерфейс ksAxisLineParam)  > ksAxisLineParam - методы  > GetEndPoint - Получить указатель на интерфейс параметров конечной точки ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetEndPoint - Получить указатель на интерфейс параметров конечной точки <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcd1763412\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksaxislineparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH GetEndPoint();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksmathpointparam.html\" class=\"topiclink\">ksMathPointParam<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
