hmLoadTopic({
hmKeywords:"",
hmTitle:"ksBaseExtrusionDefinition - методы",
hmDescription:"Подразделы: ExtrusionParam - Получить указатель на интерфейс параметров элемента выдавливания  GetDepthObject - Получить объект, задающий глубину выдавливания  GetSketch - Получ",
hmPrevLink:"ksbaseextrusiondefinition_directiontype.html",
hmNextLink:"ksbaseextrusiondefinition_extrusionparam.html",
hmParentLink:"ksbaseextrusiondefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_operation.html\">Интерфейсы формообразующих операций&nbsp;<\/a> &gt; <a href=\"ksbaseextrusiondefinition.html\">Основание — элемент выдавливания (Интерфейс ksBaseExtrusionDefinition, IBaseExtrusionDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы формообразующих операций  > Основание — элемент выдавливания (Интерфейс ksBaseExtrusionDefinition, IBaseExtrusionDefinition)  > ksBaseExtrusionDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksBaseExtrusionDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_extrusionparam.html\" class=\"topiclink hmlinklistitem\">ExtrusionParam - Получить указатель на интерфейс параметров элемента выдавливания <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_getdepthobject.html\" class=\"topiclink hmlinklistitem\">GetDepthObject - Получить объект, задающий глубину выдавливания <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_getsketch.html\" class=\"topiclink hmlinklistitem\">GetSketch - Получить указатель на интерфейс эскиза элемента <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_getsideparam.html\" class=\"topiclink hmlinklistitem\">GetSideParam - Получить параметры выдавливания в одном направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_getthinparam.html\" class=\"topiclink hmlinklistitem\">GetThinParam - Получить параметры тонкой стенки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_resetdepthobject.html\" class=\"topiclink hmlinklistitem\">ResetDepthObject - Отказаться от установленного методом SetDepthObject объекта, задающего глубину выдавливания <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_setdepthobject.html\" class=\"topiclink hmlinklistitem\">SetDepthObject - Установить объект, задающий глубину выдавливания <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_setsideparam.html\" class=\"topiclink hmlinklistitem\">SetSideParam - Установить параметры выдавливания в одном направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_setsketch.html\" class=\"topiclink hmlinklistitem\">SetSketch - Задать указатель на интерфейс эскиза элемента <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_setthinparam.html\" class=\"topiclink hmlinklistitem\">SetThinParam - Изменить параметры тонкой стенки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbaseextrusiondefinition_thinparam.html\" class=\"topiclink hmlinklistitem\">ThinParam - Получить указатель на интерфейс параметров тонкой стенки <\/a><\/span><\/p>\n\r"
})
