hmLoadTopic({
hmKeywords:"",
hmTitle:"SetMathPointArr - Установить динамический массив параметров математических точек сплайна ksDynamicArray типа POINT_ARR",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL SetMathPointArr (LPDISPATCH pMathPoint); Входной параметр: pMathPoint - указатель на интерфейс динамического массива ksDynamicArray п",
hmPrevLink:"ksbezierparam_init.html",
hmNextLink:"ksconicarcparam.html",
hmParentLink:"ksbezierparam_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cd1743949.html\">Интерфейсы параметров графических примитивов&nbsp;<\/a> &gt; <a href=\"cd1752151.html\">Кривая Безье&nbsp;<\/a> &gt; <a href=\"ksbezierparam.html\">Кривая Безье (Интерфейс ksBezierParam)&nbsp;<\/a> &gt; <a href=\"ksbezierparam_methods.html\">ksBezierParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров графических примитивов  > Кривая Безье  > Кривая Безье (Интерфейс ksBezierParam)  > ksBezierParam - методы  > SetMathPointArr - Установить динамический массив параметров математических точек сплайна ksDynamicArray типа POINT_ARR ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">SetMathPointArr - Установить динамический массив параметров математических точек сплайна ksDynamicArray типа POINT_ARR <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcd1762577\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksbezierparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL SetMathPointArr (LPDISPATCH pMathPoint);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входной параметр<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">pMathPoint<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс динамического массива <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksdynamicarray.html\" class=\"topiclink\">ksDynamicArray<\/a><\/span><span class=\"f_Table_Cell\"> параметров математических точек типа POINT_ARR.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае удачного завершения,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">FALSE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае неудачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также: <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksmathpointparam.html\" class=\"topiclink\">ksMathPointParam<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
