hmLoadTopic({
hmKeywords:"",
hmTitle:"IBossLoftDefinition - методы",
hmDescription:"Подразделы: ChooseBodies - Получить указатель на интерфейс области применения для тел в операции  ChooseParts - Получить указатель на интерфейс области применения для...",
hmPrevLink:"ksbossloftdefinition_choosetype.html",
hmNextLink:"ksbossloftdefinition_choosebodies.html",
hmParentLink:"ksbossloftdefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_operation.html\">Интерфейсы формообразующих операций&nbsp;<\/a> &gt; <a href=\"ksbossloftdefinition.html\">Приклеенный элемент по сечениям (Интерфейсы ksBossLoftDefinition, IBossLoftDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы формообразующих операций  > Приклеенный элемент по сечениям (Интерфейсы ksBossLoftDefinition, IBossLoftDefinition)  > IBossLoftDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IBossLoftDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_choosebodies.html\" class=\"topiclink hmlinklistitem\">ChooseBodies - Получить указатель на интерфейс области применения для тел в операции <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_chooseparts.html\" class=\"topiclink hmlinklistitem\">ChooseParts - Получить указатель на интерфейс области применения для компонентов сборки в сборочной операции <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_getdirectionalline.html\" class=\"topiclink hmlinklistitem\">GetDirectionalLine - Получить направляющую линию. Эскиз, в котором лежит кривая <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_getloftparam.html\" class=\"topiclink hmlinklistitem\">GetLoftParam - Получить параметры приклеенного элемента по сечениям <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_getthinparam.html\" class=\"topiclink hmlinklistitem\">GetThinParam - Получить параметры тонкой стенки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_setdirectionalline.html\" class=\"topiclink hmlinklistitem\">SetDirectionalLine - Установить направляющую линию. Эскиз в котором лежит кривая <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_setloftparam.html\" class=\"topiclink hmlinklistitem\">SetLoftParam - Изменить параметры приклеенного элемента по сечениям <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_setthinparam.html\" class=\"topiclink hmlinklistitem\">SetThinParam - Изменить параметры тонкой стенки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_sketches.html\" class=\"topiclink hmlinklistitem\">Sketches - Получить указатель на интерфейс массива эскизов элемента по сечениям <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbossloftdefinition_thinparam.html\" class=\"topiclink hmlinklistitem\">ThinParam - Получить указатель на интерфейс параметров тонкой стенки <\/a><\/span><\/p>\n\r"
})
