hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс массива трехмерных тел (Интерфейсы ksBodyCollection, IBodyCollection)",
hmDescription:"Интерфейс массива трехмерных тел. ksBodyCollection - интерфейс Automation IBodyCollection - интерфейс COM Подразделы: IBodyCollection - методы  Трехмерное тело (Интерфейсы k",
hmPrevLink:"ksorientededge_isstraight.html",
hmNextLink:"ksbodycollection_methods.html",
hmParentLink:"ksentity.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейс массива трехмерных тел (Интерфейсы ksBodyCollection, IBodyCollection) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс массива трехмерных тел (Интерфейсы ksBodyCollection, IBodyCollection) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс массива трехмерных тел<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\" style=\"font-weight: bold;\">ksBodyCollection<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- интерфейс Automation<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\" style=\"font-weight: bold;\">IBodyCollection<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- интерфейс COM<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbodycollection_methods.html\" class=\"topiclink hmlinklistitem\">IBodyCollection - методы <\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbody.html\" class=\"topiclink hmlinklistitem\">Трехмерное тело (Интерфейсы ksBody, Body) <\/a><\/span><\/p>\n\r"
})
