hmLoadTopic({
hmKeywords:"",
hmTitle:"Отрисовка линейных и угловых размеров с обрывом (Интерфейс ksBreakDimDrawing)",
hmDescription:"Интерфейс параметров отрисовки линейного и углового размера с обрывом.",
hmPrevLink:"ksdimdrawingparam_init.html",
hmNextLink:"ksbreakdimdrawing_props.html",
hmParentLink:"cf1715343.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cf1713887.html\">Интерфейсы параметров размеров&nbsp;<\/a> &gt; <a href=\"cf1715343.html\">Линейные и угловые размеры&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров размеров  > Линейные и угловые размеры  > Отрисовка линейных и угловых размеров с обрывом (Интерфейс ksBreakDimDrawing) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Отрисовка линейных и угловых размеров с обрывом (Интерфейс ksBreakDimDrawing) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcf1774930\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров отрисовки линейного и углового размера с обрывом<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данных параметров при использовании API экспортных функций - <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"structbreakdimdrawing.html\" class=\"topiclink\">BreakDimDrawing<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Указатель на интерфейс можно получить при помощи метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject_getparamstruct.html\" class=\"topiclink\">KompasObject::GetParamStruct<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также: <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbreakdimdrawing_props.html\" class=\"topiclink hmlinklistitem\">ksBreakDimDrawing - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksbreakdimdrawing_methods.html\" class=\"topiclink hmlinklistitem\">ksBreakDimDrawing - методы <\/a><\/span><\/p>\n\r"
})
