hmLoadTopic({
hmKeywords:"",
hmTitle:"ksCentreParam - свойства",
hmDescription:"Подразделы: angle - Угол наклона обозначения центра  baseCurve - Указатель на базовую геометрическую кривую (например, окружность)  lenXpTail - Длина изображения полуоси, если о",
hmPrevLink:"kscentreparam.html",
hmNextLink:"kscentreparam_angle.html",
hmParentLink:"kscentreparam.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ch1786244.html\">Интерфейсы параметров обозначений&nbsp;<\/a> &gt; <a href=\"kscentreparam.html\">Обозначение центра (Интерфейс ksCentreParam)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров обозначений  > Обозначение центра (Интерфейс ksCentreParam)  > ksCentreParam - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksCentreParam - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_angle.html\" class=\"topiclink hmlinklistitem\">angle - Угол наклона обозначения центра <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_basecurve.html\" class=\"topiclink hmlinklistitem\">baseCurve - Указатель на базовую геометрическую кривую (например, окружность) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_lenxptail.html\" class=\"topiclink hmlinklistitem\">lenXpTail - Длина изображения полуоси, если оно нестандартное, в положительном направлении оси Х <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_lenxmtail.html\" class=\"topiclink hmlinklistitem\">lenXmTail - Длина изображения полуоси, если оно нестандартное, в отрицательном направлении оси Х <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_lenyptail.html\" class=\"topiclink hmlinklistitem\">lenYpTail - Длина изображения полуоси, если оно нестандартное, в положительном направлении оси Y <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_lenymtail.html\" class=\"topiclink hmlinklistitem\">lenYmTail - Длина изображения полуоси, если оно нестандартное, в отрицательном направлении оси Y <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_standxptail.html\" class=\"topiclink hmlinklistitem\">standXpTail - Признак стандартного изображения полуоси в положительном направлении оси Х <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_standxmtail.html\" class=\"topiclink hmlinklistitem\">standXmTail - Признак стандартного изображения полуоси в отрицательном направлении оси Х <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_standyptail.html\" class=\"topiclink hmlinklistitem\">standYpTail - Признак стандартного изображения полуоси в положительном направлении оси Y <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_standymtail.html\" class=\"topiclink hmlinklistitem\">standYmTail - Признак стандартного изображения полуоси в отрицательном направлении оси Y <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_type.html\" class=\"topiclink hmlinklistitem\">type - Тип обозначения центра <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscentreparam_x.html\" class=\"topiclink hmlinklistitem\">x, y - Координаты точки привязки <\/a><\/span><\/p>\n\r"
})
