hmLoadTopic({
hmKeywords:"",
hmTitle:"IChooseMng- методы",
hmDescription:"Подразделы: Choose - Выбрать (подсветить) объект  First - Получить указатель на интерфейс первого выбранного (подсвеченного) объекта  GetCount - Получить количество выбранных (п",
hmPrevLink:"kschoosemng.html",
hmNextLink:"kschoosemng_choose.html",
hmParentLink:"kschoosemng.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kschoosemng.html\">Менеджер выбора (подсветки) объектов (Интерфейсы ksChooseMng, IChooseMng)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Менеджер выбора (подсветки) объектов (Интерфейсы ksChooseMng, IChooseMng)  > IChooseMng- методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IChooseMng- методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_choose.html\" class=\"topiclink hmlinklistitem\">Choose - Выбрать (подсветить) объект <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_first.html\" class=\"topiclink hmlinklistitem\">First - Получить указатель на интерфейс первого выбранного (подсвеченного) объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_getcount.html\" class=\"topiclink hmlinklistitem\">GetCount - Получить количество выбранных (подсвеченных) объектов <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_getmanagerindex.html\" class=\"topiclink hmlinklistitem\">GetManagerIndex - Получить индекс менеджера по указателю на выбранный объект <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_getobjectbyindex.html\" class=\"topiclink hmlinklistitem\">GetObjectByIndex - Получить указатель на интерфейс выделенного (подсвеченного) объекта по индексу <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_getobjecttype.html\" class=\"topiclink hmlinklistitem\">GetObjectType - Получить тип выделенного (подсвеченного) объекта по индексу <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_ischoosen.html\" class=\"topiclink hmlinklistitem\">IsChoosen - Получить признак подсвеченности (выбора) объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_last.html\" class=\"topiclink hmlinklistitem\">Last - Получить указатель на интерфейс последнего выбранного (подсвеченного) объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_next.html\" class=\"topiclink hmlinklistitem\">Next - Получить указатель на интерфейс следующего выбранного (подсвеченного) объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_prev.html\" class=\"topiclink hmlinklistitem\">Prev - Получить указатель на интерфейс предыдущего выбранного (подсвеченного) объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_unchoose.html\" class=\"topiclink hmlinklistitem\">UnChoose - Снять выбор (подсветку) с объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kschoosemng_unchooseall.html\" class=\"topiclink hmlinklistitem\">UnChooseAll - Снять выбор (подсветку) со всех подсвеченных объектов <\/a><\/span><\/p>\n\r"
})
