hmLoadTopic({
hmKeywords:"",
hmTitle:"ksChoiceAttr3D - Просмотреть атрибуты объекта документа-модели",
hmDescription:"Аналог данной функции при использовании Automation - метод ksAttributeObject::ksChoiceAttr3D.",
hmPrevLink:"ksaddattrroww.html",
hmNextLink:"kscreateattr.html",
hmParentLink:"attribs_fncts_common.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"cn1731963.html\">Функции работы с прикладной библиотекой&nbsp;<\/a> &gt; <a href=\"attribs_fncts_common.html\">Функции работы с атрибутами&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Функции работы с прикладной библиотекой  > Функции работы с атрибутами  > ksChoiceAttr3D - Просмотреть атрибуты объекта документа-модели ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksChoiceAttr3D - Просмотреть атрибуты объекта документа-модели <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcn1915856\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данной функции при использовании Automation - метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksattributeobject_kschoiceattr3d.html\" class=\"topiclink\">ksAttributeObject::ksChoiceAttr3D<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPATTRIBUTE3D ksChoiceAttr3D (LPUNKNOWN pObj);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"pobj.html\" class=\"topiclink\">pObj<\/a><\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на объект.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">указатель на интерфейс атрибута <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksattribute3d.html\" class=\"topiclink\">IAttribute3D<\/a><\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае удачного завершения,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">0<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае неудачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
