hmLoadTopic({
hmKeywords:"",
hmTitle:"ICopyCircularDefinition - свойства",
hmDescription:"Подразделы: count1 - Количество копий в радиальном направлении  count2 - Количество копий в кольцевом направлении  factor1 - Признак полного шага в радиальном направлении  fact",
hmPrevLink:"kscircularcopydefinition.html",
hmNextLink:"kscircularcopydefinition_count1.html",
hmParentLink:"kscircularcopydefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_copy.html\">Интерфейсы копирования&nbsp;<\/a> &gt; <a href=\"kscircularcopydefinition.html\">Копия элементов детали по концентрической сетке (Интерфейсы ksCircularCopyDefinition, ICopyCircularDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы копирования  > Копия элементов детали по концентрической сетке (Интерфейсы ksCircularCopyDefinition, ICopyCircularDefinition)  > ICopyCircularDefinition - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ICopyCircularDefinition - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_count1.html\" class=\"topiclink hmlinklistitem\">count1 - Количество копий в радиальном направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_count2.html\" class=\"topiclink hmlinklistitem\">count2 - Количество копий в кольцевом направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_factor1.html\" class=\"topiclink hmlinklistitem\">factor1 - Признак полного шага в радиальном направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_factor2.html\" class=\"topiclink hmlinklistitem\">factor2 - Признак полного шага в кольцевом направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_geomarray.html\" class=\"topiclink hmlinklistitem\">geomArray - Признак использования геометрического копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_inverce.html\" class=\"topiclink hmlinklistitem\">inverce - Признак направления копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_step1.html\" class=\"topiclink hmlinklistitem\">step1 - Шаг копирования в радиальном направлении <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_step2.html\" class=\"topiclink hmlinklistitem\">step2 - Шаг в кольцевом направлении <\/a><\/span><\/p>\n\r"
})
