hmLoadTopic({
hmKeywords:"",
hmTitle:"ICopyCircularDefinition - методы",
hmDescription:"Подразделы: DeletedCollection - Получить массив индексов удаленных копий  GetAxis - Получить ось копирования  GetCopyParamAlongDir - Получить параметры копирования  GetOperatio",
hmPrevLink:"kscircularcopydefinition_step2.html",
hmNextLink:"kscircularcopydefinition_deletedcollection.html",
hmParentLink:"kscircularcopydefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_copy.html\">Интерфейсы копирования&nbsp;<\/a> &gt; <a href=\"kscircularcopydefinition.html\">Копия элементов детали по концентрической сетке (Интерфейсы ksCircularCopyDefinition, ICopyCircularDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы копирования  > Копия элементов детали по концентрической сетке (Интерфейсы ksCircularCopyDefinition, ICopyCircularDefinition)  > ICopyCircularDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ICopyCircularDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_deletedcollection.html\" class=\"topiclink hmlinklistitem\">DeletedCollection - Получить массив индексов удаленных копий <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_getaxis.html\" class=\"topiclink hmlinklistitem\">GetAxis - Получить ось копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_getcopyparamalongdir.html\" class=\"topiclink hmlinklistitem\">GetCopyParamAlongDir - Получить параметры копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_getoperationarray.html\" class=\"topiclink hmlinklistitem\">GetOperationArray - Получить указатель на массив элементов для копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_setaxis.html\" class=\"topiclink hmlinklistitem\">SetAxis - Установить ось копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularcopydefinition_setcopyparamalongdir.html\" class=\"topiclink hmlinklistitem\">SetCopyParamAlongDir - Установить параметры копирования <\/a><\/span><\/p>\n\r"
})
