hmLoadTopic({
hmKeywords:"",
hmTitle:"ksCircularPartArrayDefinition - методы",
hmDescription:"Подразделы: DeletedCollection - Получить массив индексов удаленных копий  GetAxis - Получить указатель на ось копирования  GetCopyParamAlongDir - Получить параметры копирования",
hmPrevLink:"kscircularpartarraydefinition_step2.html",
hmNextLink:"kscircularpartarraydefinition_deletedcollection.html",
hmParentLink:"kscircularpartarraydefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"nt_copy_asm.html\">Интерфейсы копирования компонентов сборки&nbsp;<\/a> &gt; <a href=\"kscircularpartarraydefinition.html\">Копия компонентов сборки по концентрической сетке (Интерфейсы ksCircularPartArrayDefinition, ICircularPartArrayDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы копирования компонентов сборки  > Копия компонентов сборки по концентрической сетке (Интерфейсы ksCircularPartArrayDefinition, ICircularPartArrayDefinition)  > ksCircularPartArrayDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksCircularPartArrayDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularpartarraydefinition_deletedcollection.html\" class=\"topiclink hmlinklistitem\">DeletedCollection - Получить массив индексов удаленных копий <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularpartarraydefinition_getaxis.html\" class=\"topiclink hmlinklistitem\">GetAxis - Получить указатель на ось копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularpartarraydefinition_getcopyparamalongdir.html\" class=\"topiclink hmlinklistitem\">GetCopyParamAlongDir - Получить параметры копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularpartarraydefinition_partarray.html\" class=\"topiclink hmlinklistitem\">PartArray - Указатель на массив компонентов для копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularpartarraydefinition_setaxis.html\" class=\"topiclink hmlinklistitem\">SetAxis - Установить указатель на ось копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscircularpartarraydefinition_setcopyparamalongdir.html\" class=\"topiclink hmlinklistitem\">SetCopyParamAlongDir - Установить параметры копирования <\/a><\/span><\/p>\n\r"
})
