hmLoadTopic({
hmKeywords:"",
hmTitle:"ksConicSurfaceSideAngleBuildingTypeEnum - Условие построения угла треугольника конической поверхности при построении по грани",
hmDescription:"ksConicSectionSurfaceSideAngleTangent 0 По касательной.  Результирующий угол - угол между касательной к грани и основанием треугольника ksConicSectionSurfaceSideAngleNormal 1",
hmPrevLink:"ksconicsectiontrianglepointenum.html",
hmNextLink:"ksconicsurfacesidebuildingtype.html",
hmParentLink:"cj1473974.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"cj1473974.html\">Константы API версии 7&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Константы API версии 7  > ksConicSurfaceSideAngleBuildingTypeEnum - Условие построения угла треугольника конической поверхности при построении по грани",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksConicSurfaceSideAngleBuildingTypeEnum - Условие построения угла треугольника конической поверхности при построении по грани<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"ksconicsurfacesideanglebuildingtypeenum\" class=\"hmanchor\"><\/a><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksConicSectionSurfaceSideAngleTangent<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">0<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">По касательной. &nbsp;Результирующий угол - угол между касательной к грани и основанием треугольника<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksConicSectionSurfaceSideAngleNormal<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">1<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Перпендикулярно. Результирующий угол - угол между перпендикуляром к грани и основанием треугольника<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
