hmLoadTopic({
hmKeywords:"",
hmTitle:"OperationArray - Получить указатель на массив элементов для копирования",
hmDescription:"Интерфейс... Синтаксис Automation: IDispatch * OperationArray(); Синтаксис COM: LPENTITYCOLLECTION OperationArray(); Возвращаемое значение:   - указатель на интерфейс дина",
hmPrevLink:"kscurvecopydefinition_methods.html",
hmNextLink:"kscurvecopydefinition_curvearray.html",
hmParentLink:"kscurvecopydefinition_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_copy.html\">Интерфейсы копирования&nbsp;<\/a> &gt; <a href=\"kscurvecopydefinition.html\">Копия элементов детали по кривой (Интерфейсы ksCurveCopyDefinition и ICopyCurveDefinition)&nbsp;<\/a> &gt; <a href=\"kscurvecopydefinition_methods.html\">ksCurveCopyDefinition - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы копирования  > Копия элементов детали по кривой (Интерфейсы ksCurveCopyDefinition и ICopyCurveDefinition)  > ksCurveCopyDefinition - методы  > OperationArray - Получить указатель на массив элементов для копирования ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">OperationArray - Получить указатель на массив элементов для копирования <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbw1766917\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kscurvecopydefinition.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">IDispatch * OperationArray();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPENTITYCOLLECTION OperationArray();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс динамического массива операций, подлежащих копированию <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksentitycollection.html\" class=\"topiclink\">ksEntityCollection<\/a><\/span><span class=\"f_Table_Cell\"> или <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksentitycollection.html\" class=\"topiclink\">IEntityCollection<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
