hmLoadTopic({
hmKeywords:"",
hmTitle:"ksCurveCopyDefinition - свойства",
hmDescription:"Подразделы: count - Количество копий  factor - Признак полного шага  fullCurve - Признак распределения копий  geomArray - Признак использования геометрического копирования  ke",
hmPrevLink:"kscurvecopydefinition.html",
hmNextLink:"kscurvecopydefinition_count.html",
hmParentLink:"kscurvecopydefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_copy.html\">Интерфейсы копирования&nbsp;<\/a> &gt; <a href=\"kscurvecopydefinition.html\">Копия элементов детали по кривой (Интерфейсы ksCurveCopyDefinition и ICopyCurveDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы копирования  > Копия элементов детали по кривой (Интерфейсы ksCurveCopyDefinition и ICopyCurveDefinition)  > ksCurveCopyDefinition - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksCurveCopyDefinition - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvecopydefinition_count.html\" class=\"topiclink hmlinklistitem\">count - Количество копий <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvecopydefinition_factor.html\" class=\"topiclink hmlinklistitem\">factor - Признак полного шага <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvecopydefinition_fullcurve.html\" class=\"topiclink hmlinklistitem\">fullCurve - Признак распределения копий <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvecopydefinition_geomarray.html\" class=\"topiclink hmlinklistitem\">geomArray - Признак использования геометрического копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvecopydefinition_keepangle.html\" class=\"topiclink hmlinklistitem\">keepAngle - Признак сохранения угла элементов относительно траектории в начальной точке <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"sence.html\" class=\"topiclink hmlinklistitem\">sence - Направление копирования <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvecopydefinition_step.html\" class=\"topiclink hmlinklistitem\">step - Шаг копирования <\/a><\/span><\/p>\n\r"
})
