hmLoadTopic({
hmKeywords:"",
hmTitle:"ksCurveStyleParam - свойства",
hmDescription:"Подразделы: color - Цвет  curveType - Тип кривой  even - Тип окончания прерывистой кривой  name - Имя стиля  paperWidth - Толщина линии на бумаге  screenWidth -Толщина линии",
hmPrevLink:"kscurvestyleparam.html",
hmNextLink:"kscurvestyleparam_color.html",
hmParentLink:"kscurvestyleparam.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cf1711377.html\">Интерфейсы параметров стилей объектов&nbsp;<\/a> &gt; <a href=\"cf1753270.html\">Стиль линии&nbsp;<\/a> &gt; <a href=\"kscurvestyleparam.html\">Стиль линии (Интерфейс ksCurveStyleParam)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров стилей объектов  > Стиль линии  > Стиль линии (Интерфейс ksCurveStyleParam)  > ksCurveStyleParam - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksCurveStyleParam - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_color.html\" class=\"topiclink hmlinklistitem\">color - Цвет <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_curvetype.html\" class=\"topiclink hmlinklistitem\">curveType - Тип кривой <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_even.html\" class=\"topiclink hmlinklistitem\">even - Тип окончания прерывистой кривой <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_name.html\" class=\"topiclink hmlinklistitem\">name - Имя стиля <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_paperwidth.html\" class=\"topiclink hmlinklistitem\">paperWidth - Толщина линии на бумаге <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_screenwidth.html\" class=\"topiclink hmlinklistitem\">screenWidth -Толщина линии на экране <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscurvestyleparam_widthpen.html\" class=\"topiclink hmlinklistitem\">widthPen - Способ задания толщины линии <\/a><\/span><\/p>\n\r"
})
