hmLoadTopic({
hmKeywords:"",
hmTitle:"ICylindricSpiralDefinition - методы",
hmDescription:"Подразделы: GetCurve3D - Получить указатель на интерфейс математической кривой  GetDiamObject - Получить объект, задающий диаметр  GetLocation- Получить координаты точки привязк",
hmPrevLink:"kscylindricspiraldefinition_turndir.html",
hmNextLink:"kscylindricspiraldefinition_getcurve3d.html",
hmParentLink:"kscylindricspiraldefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_pr_curve.html\">Интерфейсы пространственных кривых&nbsp;<\/a> &gt; <a href=\"kscylindricspiraldefinition.html\">Цилиндрическая спираль (Интерфейсы ksCylindricSpiralDefinition и CylindricSpiralDefinition&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы пространственных кривых  > Цилиндрическая спираль (Интерфейсы ksCylindricSpiralDefinition и CylindricSpiralDefinition  > ICylindricSpiralDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ICylindricSpiralDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_getcurve3d.html\" class=\"topiclink hmlinklistitem\">GetCurve3D - Получить указатель на интерфейс математической кривой <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_getdiamobject.html\" class=\"topiclink hmlinklistitem\">GetDiamObject - Получить объект, задающий диаметр <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_getlocation.html\" class=\"topiclink hmlinklistitem\">GetLocation- Получить координаты точки привязки спирали на базовой плоскости (точку пересечения оси спирали с базовой плоскостью) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_getheightobject.html\" class=\"topiclink hmlinklistitem\">GetHeightObject - Получить объект, задающий высоту <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_getplane.html\" class=\"topiclink hmlinklistitem\">GetPlane - Получить базовую плоскость спирали <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_getsketch.html\" class=\"topiclink hmlinklistitem\">GetSketch - Получить указатель на интерфейс эскиза элемента <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_setdiamobject.html\" class=\"topiclink hmlinklistitem\">SetDiamObject - Установить объект, задающий диаметр <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_setheightobject.html\" class=\"topiclink hmlinklistitem\">SetHeightObject - Установить объект, задающий высоту <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_setlocation.html\" class=\"topiclink hmlinklistitem\">SetLocation - Установить точку привязки спирали на базовой плоскости (точку пересечения оси спирали с базовой плоскостью) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kscylindricspiraldefinition_setplane.html\" class=\"topiclink hmlinklistitem\">SetPlane - Установить базовую плоскость спирали <\/a><\/span><\/p>\n\r"
})
