hmLoadTopic({
hmKeywords:"",
hmTitle:"ksDimensionsOptions - свойства",
hmDescription:"Подразделы: anglePrecisionLevel - Точность углового размера  arrowLength - Длина стрелки  decimalsCount - Количество знаков после запятой (от 0 до 9)  dimLineExtension - Выход",
hmPrevLink:"ksdimensionsoptions.html",
hmNextLink:"ksdimensionsoptions_angleprecisionlevel.html",
hmParentLink:"ksdimensionsoptions.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cf1713887.html\">Интерфейсы параметров размеров&nbsp;<\/a> &gt; <a href=\"ksdimensionsoptions.html\">Настройки размеров (Интерфейс ksDimensionsOptions)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров размеров  > Настройки размеров (Интерфейс ksDimensionsOptions)  > ksDimensionsOptions - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksDimensionsOptions - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_angleprecisionlevel.html\" class=\"topiclink hmlinklistitem\">anglePrecisionLevel - Точность углового размера <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_arrowlength.html\" class=\"topiclink hmlinklistitem\">arrowLength - Длина стрелки <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_decimalscount.html\" class=\"topiclink hmlinklistitem\">decimalsCount - Количество знаков после запятой (от 0 до 9) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_dimlineextension.html\" class=\"topiclink hmlinklistitem\">dimLineExtension - Выход размерной линии за текст <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_hiddentolerancenumber.html\" class=\"topiclink hmlinklistitem\">hiddenToleranceNumber - Квалитет <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_prolineextension.html\" class=\"topiclink hmlinklistitem\">proLineExtension - Выход выносных линий за размерную линию <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_textdistancefromdimline.html\" class=\"topiclink hmlinklistitem\">textDistanceFromDimLine - Расстояние от размерной линии до текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_textdistancefromproline.html\" class=\"topiclink hmlinklistitem\">textDistanceFromProLine - Расстояние от выносных линий до текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdimensionsoptions_style.html\" class=\"topiclink hmlinklistitem\">style - Стиль текста <\/a><\/span><\/p>\n\r"
})
