hmLoadTopic({
hmKeywords:"",
hmTitle:"ChoiceProperty - Закончен выбор свойства",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL ChoiceProperty(long objRef, double propID); Синтаксис COM: BOOL СhoiceProperty(long objRef, double propID); Возвращаемое значение:",
hmPrevLink:"ksdocument2dnotify_choicematerial.html",
hmNextLink:"ksdocument2dnotify_localfragmentedit.html",
hmParentLink:"ksdocument2dnotify_events.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"af1881424.html\">Интерфейсы событий API5&nbsp;<\/a> &gt; <a href=\"eventscommon.html\">События в КОМПАС Общие сведения&nbsp;<\/a> &gt; <a href=\"ksdocument2dnotify.html\">Интерфейсы событий графического документа ksDocument2DNotify\/ IDocument2DNotify&nbsp;<\/a> &gt; <a href=\"ksdocument2dnotify_events.html\">IDocument2DNotify - события&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Интерфейсы событий API5  > События в КОМПАС Общие сведения  > Интерфейсы событий графического документа ksDocument2DNotify\/ IDocument2DNotify  > IDocument2DNotify - события  > ChoiceProperty - Закончен выбор свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ChoiceProperty - Закончен выбор свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xaf1868949\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2dnotify.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL ChoiceProperty(long objRef, double propID);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL СhoiceProperty(long objRef, double propID);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- не используется.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Индекс метода задан в <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2dnotifyenum.html\" class=\"topiclink\">перечислении событий графического документа..<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
