hmLoadTopic({
hmKeywords:"",
hmTitle:"Данные типа DOUBLE (Интерфейс ksDoubleValue)",
hmDescription:"Интерфейс для типа double. Примечания: 1. Данный интерфейс используется в качестве параметров узла NURBS и в динамическом массиве ksDynamicArray типа DOUBLE_ARR. 2. Указатель на",
hmPrevLink:"ksuserparam_setuserarray.html",
hmNextLink:"ksdoublevalue_props.html",
hmParentLink:"ksdocument2d.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Данные типа DOUBLE (Интерфейс ksDoubleValue) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Данные типа DOUBLE (Интерфейс ksDoubleValue) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xch1827527\" class=\"hmanchor\"><\/a><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс для типа double<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечания<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Данный интерфейс используется в качестве параметров узла NURBS и в динамическом массиве <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"ksdynamicarray.html\" class=\"topiclink\">ksDynamicArray<\/a><\/span><span class=\"f_Numbered\"> типа DOUBLE_ARR.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Указатель на интерфейс можно получить при помощи метода <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"kompasobject_getparamstruct.html\" class=\"topiclink\">KompasObject::GetParamStruct<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также: <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdoublevalue_props.html\" class=\"topiclink hmlinklistitem\">ksDoubleValue - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksdoublevalue_methods.html\" class=\"topiclink hmlinklistitem\">ksDoubleValue - методы <\/a><\/span><\/p>\n\r"
})
