hmLoadTopic({
hmKeywords:"",
hmTitle:"BeginChoiceProperty - Начало выбора свойства",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL BeginChoiceProperty( LPDISPATCH obj, double propID ); Синтаксис COM: BOOL BeginChoiceProperty( LPUNKNOWN obj, double propID ); Возвра",
hmPrevLink:"ksdocument3dnotify_beginchoicematerial.html",
hmNextLink:"ksdocument3dnotify_begincreatepartfromfile.html",
hmParentLink:"ksdocument3dnotify_events.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"af1881424.html\">Интерфейсы событий API5&nbsp;<\/a> &gt; <a href=\"eventscommon.html\">События в КОМПАС Общие сведения&nbsp;<\/a> &gt; <a href=\"ksdocument3dnotify.html\">Интерфейс событий документа - модели ksDocument3DNotify\/IDocument3DNotify&nbsp;<\/a> &gt; <a href=\"ksdocument3dnotify_events.html\">IDocument3DNotify - события&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Интерфейсы событий API5  > События в КОМПАС Общие сведения  > Интерфейс событий документа - модели ksDocument3DNotify\/IDocument3DNotify  > IDocument3DNotify - события  > BeginChoiceProperty - Начало выбора свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">BeginChoiceProperty - Начало выбора свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xaf1870069\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument3dnotify.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL BeginChoiceProperty( LPDISPATCH obj, double propID );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL BeginChoiceProperty( LPUNKNOWN obj, double propID );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Разрешить стандартную процедуру выбора свойства,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">FALSE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Запретить стандартную процедуру выбора свойства (библиотека самостоятельно обработала выбор свойства).<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
