hmLoadTopic({
hmKeywords:"",
hmTitle:"Reference - Указатель на графический документ системы КОМПАС",
hmDescription:"Интерфейс... Тип данных: long Синтаксис Automation: ref = iDocument2D.reference Получить свойство (* ) iDocument2D.reference = ref Установить свойство (* ) ref = iDocument",
hmPrevLink:"ksdocument2d_orthomode.html",
hmNextLink:"ksdocument2d_methods.html",
hmParentLink:"ksdocument2d_props.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ksdocument2d_props.html\">ksDocument2D - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > ksDocument2D - свойства  > Reference - Указатель на графический документ системы КОМПАС ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Reference - Указатель на графический документ системы КОМПАС <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbt1766427\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2d.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Тип данных: long<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ref = iDocument2D.reference<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">iDocument2D.reference = ref<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Установить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ref = iDocument2D.GetReference()<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">iDocument2D.SetReference(ref)<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Установить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
