hmLoadTopic({
hmKeywords:"",
hmTitle:"GetNotifyObjectType - Получить тип объекта",
hmDescription:"Интерфейс... Синтаксис Automation: long GetNotifyObjectType(); Синтаксис COM: long GetNotifyObjectType(); Возвращаемое значение:   - Тип объекта из перечисления ksObj3dTyp",
hmPrevLink:"ksdocument3dnotifyresult_getnotifyobject.html",
hmNextLink:"ksdocument3dnotifyresult_getnotifytype.html",
hmParentLink:"ksdocument3dnotifyresult_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"af1881424.html\">Интерфейсы событий API5&nbsp;<\/a> &gt; <a href=\"eventscommon.html\">События в КОМПАС Общие сведения&nbsp;<\/a> &gt; <a href=\"ksdocument3dnotifyresult.html\">Интерфейс дополнительных параметров для событий документа-модели ksDocument3DNotifyResult\/IDocument3DNotifyResult&nbsp;<\/a> &gt; <a href=\"ksdocument3dnotifyresult_methods.html\">ksDocument3DNotifyResult - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Интерфейсы событий API5  > События в КОМПАС Общие сведения  > Интерфейс дополнительных параметров для событий документа-модели ksDocument3DNotifyResult\/IDocument3DNotifyResult  > ksDocument3DNotifyResult - методы  > GetNotifyObjectType - Получить тип объекта ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetNotifyObjectType - Получить тип объекта <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xaf1857196\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument3dnotifyresult.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">long GetNotifyObjectType();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">long GetNotifyObjectType();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- Тип объекта из перечисления <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"obj3dtype.html\" class=\"topiclink\">ksObj3dTypeEnum<\/a><\/span><span class=\"f_Table_Cell\">. Допустимыми значениями являются o3d_part, o3d_body или o3d_uknown.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
