hmLoadTopic({
hmKeywords:"",
hmTitle:"ksGetArrayCount - Получить количество элементов в массиве",
hmDescription:"Интерфейс... Аналог данного метода при использовании API экспортных функций - GetArrayCount. Синтаксис Automation: long ksGetArrayCount(); Возвращаемое значение:   - количе",
hmPrevLink:"ksdynamicarray_ksexcludearrayitem.html",
hmNextLink:"ksdynamicarray_ksgetarrayitem.html",
hmParentLink:"ksdynamicarray_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdynamicarray.html\">Динамический массив (Интерфейс ksDynamicArray)&nbsp;<\/a> &gt; <a href=\"ksdynamicarray_methods.html\">ksDynamicArray - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Динамический массив (Интерфейс ksDynamicArray)  > ksDynamicArray - методы  > ksGetArrayCount - Получить количество элементов в массиве ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksGetArrayCount - Получить количество элементов в массиве <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xck1902704\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdynamicarray.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данного метода при использовании API экспортных функций - <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"getarraycount.html\" class=\"topiclink\">GetArrayCount<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">long ksGetArrayCount();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- количество элементов в массиве.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
