hmLoadTopic({
hmKeywords:"",
hmTitle:"IsPlanar - Является ли ребро плоским",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL IsPlanar(); Синтаксис COM: BOOL IsPlanar(); Возвращаемое значение: TRUE - ребро является плоским, FALSE - ребро не является плоск",
hmPrevLink:"ksedgedefinition_isperiodic.html",
hmNextLink:"ksfacecollection.html",
hmParentLink:"ksedgedefinition_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_additional.html\">Интерфейсы дополнительных элементов&nbsp;<\/a> &gt; <a href=\"ksedgedefinition.html\">Ребро (Интерфейсы ksEdgeDefinition, IEdgeDefinition)&nbsp;<\/a> &gt; <a href=\"ksedgedefinition_methods.html\">IEdgeDefinition - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы дополнительных элементов  > Ребро (Интерфейсы ksEdgeDefinition, IEdgeDefinition)  > IEdgeDefinition - методы  > IsPlanar - Является ли ребро плоским",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IsPlanar - Является ли ребро плоским<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"isplanar\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksedgedefinition.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL IsPlanar();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL IsPlanar();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- ребро является плоским,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">FALSE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- ребро не является плоским.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Версия КОМПАС v22<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
