hmLoadTopic({
hmKeywords:"",
hmTitle:"ksGetParametrizationParam - Получить интерфейс параметров параметризации объектов",
hmDescription:"Аналог данной функции при использовании Automation - метод KompasObject::GetParamStruct. В метод необходимо передать константу ko_ParametrizationParam.",
hmPrevLink:"ksgetorthomode.html",
hmNextLink:"ksgetsnapinfo.html",
hmParentLink:"draft_edit_fncts_common.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"cn1712096.html\">Редактирование графических объектов&nbsp;<\/a> &gt; <a href=\"draft_edit_fncts_common.html\">Функции редактирования объектов чертежа&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Редактирование графических объектов  > Функции редактирования объектов чертежа  > ksGetParametrizationParam - Получить интерфейс параметров параметризации объектов ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksGetParametrizationParam - Получить интерфейс параметров параметризации объектов <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcn1992026\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данной функции при использовании Automation - метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject_getparamstruct.html\" class=\"topiclink\">KompasObject::GetParamStruct<\/a><\/span><span class=\"f_bodytext\">. В метод необходимо передать константу ko_ParametrizationParam.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">IParametrizationParam * ksGetParametrizationParam();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Указатель на интерфейс параметров параметризации объектов <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksparametrizationparam.html\" class=\"topiclink\">IParametrizationParam<\/a><\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае успешного завершения,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">NULL<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае неудачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Данная функция используется совместно с ksParametrizeObjects. Объявление интерфейса IParametrizationParam дано в библиотеке типов kAPI2D5COM.tlb.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
