hmLoadTopic({
hmKeywords:"",
hmTitle:"ksGetSpcSheetSB, ksSetSpcSheetSB - пример использования",
hmDescription:"\/\/откроем спецификацию reference pDoc = OpenDocument (\"d:\\\\0\\\\4.spw\", 0); if (pDoc) { \/\/заполним массив листов сборки, которые нужно подключить к спецификации reference arr",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"compiling_libraries.html",
hmBreadCrumbs:"",
hmTitlePath:"Компиляция библиотек > Использование библиотек типов интерфейсов Системы КОМПАС-3D",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksGetSpcSheetSB, ksSetSpcSheetSB - пример использования <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcg1728349\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/откроем спецификацию<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">reference pDoc = OpenDocument (&quot;d:\\\\0\\\\4.spw&quot;, 0);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">if (pDoc)<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">{<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/заполним массив листов сборки, которые нужно подключить к спецификации<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">reference arr = CreateArray(CHAR_STR_ARR, 0);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">char buf [255];<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">strcpy (buf, &quot;d:\\\\0\\\\1.cdw&quot;);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">AddArrayItem (arr, -1, buf, strlen(buf)1);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">strcpy (buf, &quot;d:\\\\0\\\\2.cdw&quot;);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">AddArrayItem (arr, -1, buf, strlen(buf)1);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/подключим листы сборочного чертежа к спецификации<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">ksSetSpcSheetSB (pDoc , arr);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">DeleteArray (arr);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/просмотрим листы сборки, подключенные к спецификации<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">reference p = ksGetSpcSheetSB (pDoc);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">if (p)<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">{<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">for (uint i=0, count = GetArrayCount( p); i &lt; count; i)<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">{<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">char buf1[255];<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">GetArrayItem(p, i, buf1, 255);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Message(buf1);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">}<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">}<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">SaveDocument(pDoc, 0);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">CloseDocument(pDoc);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">}<\/span><\/p>\n\r"
})
