hmLoadTopic({
hmKeywords:"",
hmTitle:"ksGetDocVariableArray - Получить массив параметрических переменных графического документа или вставки фрагмента",
hmDescription:"Пример... Аналог данной функции при использовании Automation - метод ksDocument2D::ksGetDocVariableArray. Синтаксис: reference ksGetDocVariableArray (reference p); Входной па",
hmPrevLink:"ksgetdimensionvariablename.html",
hmNextLink:"ksgetobjconstraints.html",
hmParentLink:"parametrization_fncts_common.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"cm1726661.html\">Функции работы с графическим документом&nbsp;<\/a> &gt; <a href=\"cm1746868.html\">Функции работы с параметрическими переменными и связями&nbsp;<\/a> &gt; <a href=\"parametrization_fncts_common.html\">Функции параметризации и ограничений&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Функции работы с графическим документом  > Функции работы с параметрическими переменными и связями  > Функции параметризации и ограничений  > ksGetDocVariableArray - Получить массив параметрических переменных графического документа или вставки фрагмента ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksGetDocVariableArray - Получить массив параметрических переменных графического документа или вставки фрагмента <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcm1839395\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksgetdocvariablearray_example.html\" class=\"topiclink\">Пример...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данной функции при использовании Automation - метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2d_ksgetdocvariablearray.html\" class=\"topiclink\">ksDocument2D::ksGetDocVariableArray<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">reference ksGetDocVariableArray (reference p);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входной параметр<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">p<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на документ или вставку фрагмента.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">указатель на динамический массив структур <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\">VariableParam<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае успеха,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\"><a href=\"structvariableparam.html\" class=\"topiclink\">0<\/a><\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае неудачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
