hmLoadTopic({
hmKeywords:"",
hmTitle:"ksGetSpcObjectNumber - Получить уникальный номер объекта спецификации",
hmDescription:"Пример... Аналог данной функции при использовании Automation - метод ksSpecification::ksGetSpcObjectNumber. Синтаксис: double ksGetSpcObjectNumber (reference spcObj); Входной",
hmPrevLink:"ksgetspcobjectcolumnvalues.html",
hmNextLink:"ksgetspcobjectsummarycounttext.html",
hmParentLink:"spc_fncts_common.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"spc_fncts_common.html\">Функции работы с документом-спецификацией&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Функции работы с документом-спецификацией  > ksGetSpcObjectNumber - Получить уникальный номер объекта спецификации ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksGetSpcObjectNumber - Получить уникальный номер объекта спецификации <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcn2002813\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksspcobjectcreate_example.html\" class=\"topiclink\">Пример...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данной функции при использовании Automation - метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksspecification_ksgetspcobjectnumber.html\" class=\"topiclink\">ksSpecification::ksGetSpcObjectNumber<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">double ksGetSpcObjectNumber (reference spcObj);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входной параметр<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">spcObj<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на объект спецификации.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- уникальный номер объекта спецификации.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
