hmLoadTopic({
hmKeywords:"",
hmTitle:"GetRefPoint - Получить указатель на интерфейс базовой точки",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH GetRefPoint(); Возвращаемое значение:   - указатель на интерфейс базовой точки ksMathPointParam. Подразделы: (отсутствуют)",
hmPrevLink:"kshatchstyleparam_getarrlineparam.html",
hmNextLink:"kshatchstyleparam_init.html",
hmParentLink:"kshatchstyleparam_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cf1711377.html\">Интерфейсы параметров стилей объектов&nbsp;<\/a> &gt; <a href=\"cf1754358.html\">Стиль штриховки&nbsp;<\/a> &gt; <a href=\"kshatchstyleparam.html\">Стиль штриховки (Интерфейс ksHatchStyleParam)&nbsp;<\/a> &gt; <a href=\"kshatchstyleparam_methods.html\">ksHatchStyleParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров стилей объектов  > Стиль штриховки  > Стиль штриховки (Интерфейс ksHatchStyleParam)  > ksHatchStyleParam - методы  > GetRefPoint - Получить указатель на интерфейс базовой точки ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetRefPoint - Получить указатель на интерфейс базовой точки <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcf1795725\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kshatchstyleparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH GetRefPoint();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс базовой точки <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksmathpointparam.html\" class=\"topiclink\">ksMathPointParam<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
