hmLoadTopic({
hmKeywords:"",
hmTitle:"LibInterfaceNotifyEntry - Инициализация библиотеки, подписка на события",
hmDescription:"Интерфейс... Синтаксис: VARIANT_BOOL LibInterfaceNotifyEntry( LPDISPATCH ApplicationInterface ); Входные параметры: ApplicationInterface - интерфейс приложения Компас 3D. В",
hmPrevLink:"kskompaslibrary_isonapplication7.html",
hmNextLink:"kskompaslibrary_libinterfacenotifydisconnect.html",
hmParentLink:"kskompaslibrary_methods.html",
hmBreadCrumbs:"<a href=\"libraries_create.html\">Создание прикладных библиотек&nbsp;<\/a> &gt; <a href=\"cr119224.html\">Оформление прикладных библиотек типа ActiveX&nbsp;<\/a> &gt; <a href=\"kskompaslibrary.html\">Интерфейс ksKompasLibrary&nbsp;<\/a> &gt; <a href=\"kskompaslibrary_methods.html\">ksKompasLibrary - методы&nbsp;<\/a>",
hmTitlePath:"Создание прикладных библиотек  > Оформление прикладных библиотек типа ActiveX  > Интерфейс ksKompasLibrary  > ksKompasLibrary - методы  > LibInterfaceNotifyEntry - Инициализация библиотеки, подписка на события ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">LibInterfaceNotifyEntry - Инициализация библиотеки, подписка на события <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcr146365\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kskompaslibrary.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">VARIANT_BOOL LibInterfaceNotifyEntry( LPDISPATCH ApplicationInterface );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ApplicationInterface<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- интерфейс приложения Компас 3D.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Не используется.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Параметр ApplicationInterface может быть указателем на интерфейс <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iapplication.html\" class=\"topiclink\">IApplication<\/a><\/span><span class=\"f_bodytext\">, если в приложении реализован метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kskompaslibrary_isonapplication7.html\" class=\"topiclink\">ksKompasLibrary::IsOnApplication7<\/a><\/span><span class=\"f_bodytext\">, и этот метод вернул значение TRUE, т.е. библиотека работает на API версии 7. Во всех остальных случаях параметр ApplicationInterface будет указателем на интерфейс <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
