hmLoadTopic({
hmKeywords:"",
hmTitle:"IsOnApplication7 - Получить тип версии API, используемого библиотекой",
hmDescription:"Интерфейс... Синтаксис: VARIANT_BOOL IsOnApplication7(); Примечание: Если библиотека поддерживает данный метод и возвращает TRUE, в функцию ksKompasLibrary::ExternalRunComman",
hmPrevLink:"kskompaslibrary_externalruncommand.html",
hmNextLink:"kskompaslibrary_libinterfacenotifyentry.html",
hmParentLink:"kskompaslibrary_methods.html",
hmBreadCrumbs:"<a href=\"libraries_create.html\">Создание прикладных библиотек&nbsp;<\/a> &gt; <a href=\"cr119224.html\">Оформление прикладных библиотек типа ActiveX&nbsp;<\/a> &gt; <a href=\"kskompaslibrary.html\">Интерфейс ksKompasLibrary&nbsp;<\/a> &gt; <a href=\"kskompaslibrary_methods.html\">ksKompasLibrary - методы&nbsp;<\/a>",
hmTitlePath:"Создание прикладных библиотек  > Оформление прикладных библиотек типа ActiveX  > Интерфейс ksKompasLibrary  > ksKompasLibrary - методы  > IsOnApplication7 - Получить тип версии API, используемого библиотекой ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IsOnApplication7 - Получить тип версии API, используемого библиотекой <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcr146360\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kskompaslibrary.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">VARIANT_BOOL IsOnApplication7();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Если библиотека поддерживает данный метод и возвращает TRUE, в функцию <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kskompaslibrary_externalruncommand.html\" class=\"topiclink\">ksKompasLibrary::ExternalRunCommand<\/a><\/span><span class=\"f_bodytext\"> и <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kskompaslibrary_libinterfacenotifyentry.html\" class=\"topiclink\">ksKompasLibrary::LibInterfaceNotifyEntry<\/a><\/span><span class=\"f_bodytext\"> передается интерфейс <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"iapplication.html\" class=\"topiclink\">IApplication<\/a><\/span><span class=\"f_bodytext\"> иначе передается интерфейс <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject.<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
