hmLoadTopic({
hmKeywords:"",
hmTitle:"ksLeaderParam - свойства",
hmDescription:"Подразделы: around - Признак наличия на линии-выноске знака обработки по контуру  arrowType - Тип указателя линии-выноски  dirX - Направление полки линии-выноски  cText0 - Коли",
hmPrevLink:"ksleaderparam.html",
hmNextLink:"ksleaderparam_around.html",
hmParentLink:"ksleaderparam.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ch1786244.html\">Интерфейсы параметров обозначений&nbsp;<\/a> &gt; <a href=\"ch1767016.html\">Линия - выноска&nbsp;<\/a> &gt; <a href=\"ksleaderparam.html\">Линия - выноска (Интерфейс ksLeaderParam)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров обозначений  > Линия - выноска  > Линия - выноска (Интерфейс ksLeaderParam)  > ksLeaderParam - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksLeaderParam - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_around.html\" class=\"topiclink hmlinklistitem\">around - Признак наличия на линии-выноске знака обработки по контуру <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_arrowtype.html\" class=\"topiclink hmlinklistitem\">arrowType - Тип указателя линии-выноски <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_dirx.html\" class=\"topiclink hmlinklistitem\">dirX - Направление полки линии-выноски <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_ctext0.html\" class=\"topiclink hmlinklistitem\">cText0 - Количество строк текста над полкой линии-выноски <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_ctext1.html\" class=\"topiclink hmlinklistitem\">cText1 - Количество строк текста под полкой <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_ctext2.html\" class=\"topiclink hmlinklistitem\">cText2 - Количество строк текста над &quot;ножкой&quot; линии-выноски (не более одной строки) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_ctext3.html\" class=\"topiclink hmlinklistitem\">cText3 - Количество строк текста под &quot;ножкой&quot; линии-выноски (не более одной строки) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_signtype.html\" class=\"topiclink hmlinklistitem\">signType - Тип знака на &quot;ножке&quot; линии-выноски <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_x.html\" class=\"topiclink hmlinklistitem\">x, y - Координаты базовой точки линии-выноски <\/a><\/span><\/p>\n\r"
})
