hmLoadTopic({
hmKeywords:"",
hmTitle:"Линия - выноска (Интерфейс ksLeaderParam)",
hmDescription:"Интерфейс параметров линии-выноски. Аналог данных параметров при использовании API экспортных функций - LeaderParam. Примечание: Указатель на интерфейс можно получить при помощи",
hmPrevLink:"ch1767016.html",
hmNextLink:"ksleaderparam_props.html",
hmParentLink:"ch1767016.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ch1786244.html\">Интерфейсы параметров обозначений&nbsp;<\/a> &gt; <a href=\"ch1767016.html\">Линия - выноска&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров обозначений  > Линия - выноска  > Линия - выноска (Интерфейс ksLeaderParam) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Линия - выноска (Интерфейс ksLeaderParam) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xch1829155\" class=\"hmanchor\"><\/a><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров линии-выноски<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данных параметров при использовании API экспортных функций - <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"structleaderparam.html\" class=\"topiclink\">LeaderParam<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Указатель на интерфейс можно получить при помощи метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject_getparamstruct.html\" class=\"topiclink\">KompasObject::GetParamStruct<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также: <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_props.html\" class=\"topiclink hmlinklistitem\">ksLeaderParam - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksleaderparam_methods.html\" class=\"topiclink hmlinklistitem\">ksLeaderParam - методы <\/a><\/span><\/p>\n\r"
})
