hmLoadTopic({
hmKeywords:"",
hmTitle:"Тип атрибута в библиотеке (Интерфейс ksLibraryAttrTypeParam)",
hmDescription:"Интерфейс параметров типа атрибута в библиотеке типов атрибутов.",
hmPrevLink:"kscolumninfoparam_setfieldenum.html",
hmNextLink:"kslibraryattrtypeparam_props.html",
hmParentLink:"ck1769035.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ck1761772.html\">Интерфейсы работы с атрибутами&nbsp;<\/a> &gt; <a href=\"ck1769035.html\">Интерфейсы параметров атрибутов&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Интерфейсы работы с атрибутами  > Интерфейсы параметров атрибутов  > Тип атрибута в библиотеке (Интерфейс ksLibraryAttrTypeParam) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Тип атрибута в библиотеке (Интерфейс ksLibraryAttrTypeParam) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xck1903482\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров типа атрибута в библиотеке типов атрибутов<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данных параметров при использовании API экспортных функций - <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"structlibraryattrtypeparam.html\" class=\"topiclink\">LibraryAttrTypeParam<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Перед использованием указатель на интерфейс должен быть определен с помощью метода <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"kompasobject_getparamstruct.html\" class=\"topiclink\">ompasObject::GetParamStruct<\/a><\/span><span class=\"f_Numbered\"> с параметром ko_LibraryAttrTypeParam.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Параметры интерфейса могут быть получены с помощью метода <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"ksattributeobject_ksgetlibraryattrtypesarray.html\" class=\"topiclink\">ksAttributeObject::ksGetLibraryAttrTypesArray<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">3. Уникальный номер типа атрибута typeid может быть получен с помощью метода <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"ksattributeobject_ksgetattrkeysinfo.html\" class=\"topiclink\">ksAttributeObject::ksGetAttrKeysInfo<\/a><\/span><span class=\"f_Numbered\">. Тип атрибута должен быть предварительно создан, например, с помощью функции <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"ksattributeobject_kscreateattrtype.html\" class=\"topiclink\">ksAttributeObject::ksCreateAttrType<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kompasobject.html\" class=\"topiclink\">KompasObject<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kslibraryattrtypeparam_props.html\" class=\"topiclink hmlinklistitem\">ksLibraryAttrTypeParam - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kslibraryattrtypeparam_methods.html\" class=\"topiclink hmlinklistitem\">ksLibraryAttrTypeParam - методы <\/a><\/span><\/p>\n\r"
})
