hmLoadTopic({
hmKeywords:"",
hmTitle:"ksLockFileCache - Выключить\/включить кеширование поиска файлов",
hmDescription:"Синтаксис: int LIB_FUNC ksLockFileCache( int lock ); Входные параметры: lock - TRUE - запретить кеширование, - FALSE - разрешить кеширование. Возвращаемое значение: Предыд",
hmPrevLink:"ksgetrelativepathfromsystempathw.html",
hmNextLink:"kssavefile.html",
hmParentLink:"work_with_files_common.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"work_with_files_common.html\">Функции работы с файлами документов&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Функции работы с файлами документов  > ksLockFileCache - Выключить\/включить кеширование поиска файлов ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksLockFileCache - Выключить\/включить кеширование поиска файлов <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcn1995006\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">int LIB_FUNC ksLockFileCache( int lock );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">lock<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- TRUE - запретить кеширование,<\/span><\/p>\n\r<p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- FALSE - разрешить кеширование.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Предыдущее значение флага.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Кеширование включается при запуске библиотечной команды.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
