hmLoadTopic({
hmKeywords:"",
hmTitle:"ksMateFixedTypeEnum - Фиксация компонентов при создании сопряжения",
hmDescription:"Неопределено ksMFixedUnknown = 0 Фиксировать первый компонент ksMFixedPart1 = 1 Фиксировать второй компонент ksMFixedPart2 = 2 Подразделы: (отсутствуют)",
hmPrevLink:"mateconstrainttype.html",
hmNextLink:"kstypelookstyle.html",
hmParentLink:"bk1944689.html",
hmBreadCrumbs:"<a href=\"3d_define.html\">Структуры параметров и константы<\/a> &gt; <a href=\"bk1803360.html\">Константы&nbsp;<\/a> &gt; <a href=\"bk1944694.html\">Прочие&nbsp;<\/a> &gt; <a href=\"bk1944689.html\">3D&nbsp;<\/a>",
hmTitlePath:"Структуры параметров и константы > Константы  > Прочие  > 3D  > ksMateFixedTypeEnum - Фиксация компонентов при создании сопряжения ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksMateFixedTypeEnum - Фиксация компонентов при создании сопряжения <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbk1945458\" class=\"hmanchor\"><\/a><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Неопределено<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksMFixedUnknown = 0<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Фиксировать первый компонент<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksMFixedPart1 = 1<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Фиксировать второй компонент<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksMFixedPart2 = 2<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
