hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ksModelObjectNotify",
hmDescription:"Интерфейс событий для объектов документа-модели. Описание: Позволяют контролировать состояние объектов документа - модели. В Automation источником событий для подписки на данн",
hmPrevLink:"kslibrarymanagernotify_tryexecute.html",
hmNextLink:"ksmodelobjectnotify_events.html",
hmParentLink:"sobutiy.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"sobutiy.html\">Интерфейсы событий&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Интерфейсы событий  > Интерфейс ksModelObjectNotify ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ksModelObjectNotify <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbo1880193\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс событий для объектов документа-модели<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Описание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Позволяют контролировать состояние объектов документа - модели.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">В Automation источником событий для подписки на данный интерфейс являются объекты <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelobject.html\" class=\"topiclink\">IModelObject<\/a><\/span><span class=\"f_bodytext\"> (события генерируются только для этого объекта) или коллекции объектов 3D <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelobjects.html\" class=\"topiclink\">IModelObjects<\/a><\/span><span class=\"f_bodytext\"> (события генерируются для всех объектов данной коллекции).<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">В процессе обработки события можно получить дополнительную информацию о редактировании объекта при помощи интерфейса <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"imodelobjectnotifyresult.html\" class=\"topiclink\">IModelObjectNotifyResult<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">В API 5 аналогом является Интерфейс событий объектов документа-модели <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksobject3dnotify.html\" class=\"topiclink\">ksObject3DNotify<\/a><\/span><span class=\"f_bodytext\">, поэтому перечисления событий совпадают с перечислением событий для объектов документа-модели KsObject3DNotifyEnum.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksmodelobjectnotify_events.html\" class=\"topiclink hmlinklistitem\">ksModelObjectNotify - события <\/a><\/span><\/p>\n\r"
})
