hmLoadTopic({
hmKeywords:"",
hmTitle:"SetPPoint - Установить динамический массив точек сплайна ksDynamicArray типа NURBS_POINT_ARR",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL SetPPoint (LPDISPATCH pPoint); Входной параметр: pPoint - указатель на интерфейс динамического массива ksDynamicArray точек сплайна т",
hmPrevLink:"ksnurbsparam_setpknot.html",
hmNextLink:"cd1752151.html",
hmParentLink:"ksnurbsparam_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cd1743949.html\">Интерфейсы параметров графических примитивов&nbsp;<\/a> &gt; <a href=\"cd1751192.html\">NURBS&nbsp;<\/a> &gt; <a href=\"ksnurbsparam.html\">Кривая NURBS (Интерфейс ksNurbsParam)&nbsp;<\/a> &gt; <a href=\"ksnurbsparam_methods.html\">ksNurbsParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров графических примитивов  > NURBS  > Кривая NURBS (Интерфейс ksNurbsParam)  > ksNurbsParam - методы  > SetPPoint - Установить динамический массив точек сплайна ksDynamicArray типа NURBS_POINT_ARR ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">SetPPoint - Установить динамический массив точек сплайна ksDynamicArray типа NURBS_POINT_ARR <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcd1777268\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksnurbsparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL SetPPoint (LPDISPATCH pPoint);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входной параметр<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">pPoint<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс динамического массива <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksdynamicarray.html\" class=\"topiclink\">ksDynamicArray<\/a><\/span><span class=\"f_Table_Cell\"> точек сплайна типа NURBS_POINT_ARR.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае удачного завершения.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Смотрите также: <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksnurbspointparam.html\" class=\"topiclink\">ksNurbsPointParam<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
