hmLoadTopic({
hmKeywords:"",
hmTitle:"IsUndoMode - Признак работы команды Undo",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL IsUndoMode(); Синтаксис COM: BOOL IsUndoMode(); Возвращаемое значение: TRUE - если работает команда Undo. Примечание: Свойство тр",
hmPrevLink:"ksobject2dnotifyresult_isredomode.html",
hmNextLink:"kspropertymanagernotify.html",
hmParentLink:"ksobject2dnotifyresult_methods.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"sobutiy.html\">Интерфейсы событий&nbsp;<\/a> &gt; <a href=\"ksobject2dnotifyresult.html\">Интерфейс ksObject2DNotifyResultIObject2DNotifyResult&nbsp;<\/a> &gt; <a href=\"ksobject2dnotifyresult_methods.html\">ksObject2DNotifyResult - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Интерфейсы событий  > Интерфейс ksObject2DNotifyResultIObject2DNotifyResult  > ksObject2DNotifyResult - методы  > IsUndoMode - Признак работы команды Undo ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IsUndoMode - Признак работы команды Undo <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xce1784564\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksobject2dnotifyresult.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL IsUndoMode();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL IsUndoMode();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- если работает команда Undo.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Свойство требуется проверять в событиях, если необходимо отличать событие, полученное от визуальной работы пользователя, от действий, вызванных командой <\/span><span class=\"f_bodytext\" style=\"font-weight: bold;\">Отменить<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Например, при отмене создания объекта посылается событие удаления объекта.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">При отмене удаления объекта посылается событие создания объекта.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">См. также: <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksobject2dnotifyresult_isredomode.html\" class=\"topiclink\">ksObject2DNotifyResult::IsRedoMode<\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
