hmLoadTopic({
hmKeywords:"",
hmTitle:"GetObject3DNotifyResult - Получить интерфейс результатов редактирования объекта документа-модели",
hmDescription:"Интерфейс... Синтаксис Automation: ksObject3DNotifyResult * GetObject3DNotifyResult(); Синтаксис COM: IObject3DNotifyResult * GetObject3DNotifyResult(); Возвращаемое значени",
hmPrevLink:"kspart_getobject3dnotify.html",
hmNextLink:"kspart_getpart.html",
hmParentLink:"kspart_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"kspart_methods.html\">IPart - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > IPart - методы  > GetObject3DNotifyResult - Получить интерфейс результатов редактирования объекта документа-модели ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetObject3DNotifyResult - Получить интерфейс результатов редактирования объекта документа-модели <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbu1745137\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kspart.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">ksObject3DNotifyResult * GetObject3DNotifyResult();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">IObject3DNotifyResult * GetObject3DNotifyResult();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс источника событий <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksobject3dnotifyresult.html\" class=\"topiclink\">ksObject3DNotifyResult<\/a><\/span><span class=\"f_Table_Cell\"> или <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksobject3dnotifyresult.html\" class=\"topiclink\">IObject3DNotifyResult<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
