hmLoadTopic({
hmKeywords:"",
hmTitle:"rad - Радиус дуги или окружности",
hmDescription:"Интерфейс... Тип данных:double. Синтаксис Automation: rad = iRDimSource.rad Получить свойство (* ) iRDimSource.rad = rad Установить свойство (* ) rad = iRDimSource.GetRad(",
hmPrevLink:"ksrdimsourceparam_props.html",
hmNextLink:"ksrdimsourceparam_xc.html",
hmParentLink:"ksrdimsourceparam_props.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"cf1713887.html\">Интерфейсы параметров размеров&nbsp;<\/a> &gt; <a href=\"cf1717982.html\">Радиальные и диаметральные размеры&nbsp;<\/a> &gt; <a href=\"ksrdimsourceparam.html\">Привязка размера (Интерфейс ksRDimSourceParam)&nbsp;<\/a> &gt; <a href=\"ksrdimsourceparam_props.html\">ksRDimSourceParam - свойства&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров размеров  > Радиальные и диаметральные размеры  > Привязка размера (Интерфейс ksRDimSourceParam)  > ksRDimSourceParam - свойства  > rad - Радиус дуги или окружности ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">rad - Радиус дуги или окружности <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcf1776432\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksrdimsourceparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Тип данных:double.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">rad = iRDimSource.rad<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">iRDimSource.rad = rad<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Установить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"1.html\" class=\"topiclink\">* <\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">rad = iRDimSource.GetRad()<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Получить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">iRDimSource.SetRad( rad )<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Установить свойство (<\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"2.html\" class=\"topiclink\">**<\/a><\/span><span class=\"f_Table_Cell\">)<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
