hmLoadTopic({
hmKeywords:"",
hmTitle:"GetrPar - Получить указатель на интерфейс параметров шероховатости ksRoughPar",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH GetrPar(); Возвращаемое значение:   - указатель на интерфейс параметров знака шероховатости ksRoughPar. Подразделы: (отсутств",
hmPrevLink:"ksroughparam_methods.html",
hmNextLink:"ksroughparam_getshpar.html",
hmParentLink:"ksroughparam_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ch1786244.html\">Интерфейсы параметров обозначений&nbsp;<\/a> &gt; <a href=\"ch1721808.html\">Обозначение шероховатости&nbsp;<\/a> &gt; <a href=\"ksroughparam.html\">Обозначение шероховатости с выносной полкой (Интерфейс ksRoughParam)&nbsp;<\/a> &gt; <a href=\"ksroughparam_methods.html\">ksRoughParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров обозначений  > Обозначение шероховатости  > Обозначение шероховатости с выносной полкой (Интерфейс ksRoughParam)  > ksRoughParam - методы  > GetrPar - Получить указатель на интерфейс параметров шероховатости ksRoughPar ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetrPar - Получить указатель на интерфейс параметров шероховатости ksRoughPar <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xch1787227\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksroughparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH GetrPar();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс параметров знака шероховатости <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksroughpar.html\" class=\"topiclink\">ksRoughPar<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
