hmLoadTopic({
hmKeywords:"",
hmTitle:"GetCurrentOptionValue - Получить текущее значение, выбранное в диалоге параметров конвертации",
hmDescription:"Интерфейс... Синтаксис: BSTR GetCurrentOptionValue( BSTR uniqueID ); Возвращаемое значение:   - текущее значение свойства. Входные параметры: uniqueID - уникальный иденти",
hmPrevLink:"kssavetopreviusparam_addwarning.html",
hmNextLink:"af1881424.html",
hmParentLink:"kssavetopreviusparam.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"isavetopreviusparam.html\">Параметры конвертации при сохранении в предыдущую версию (Интерфейсы ISaveToPreviusParam, ksSaveToPreviusParam )&nbsp;<\/a> &gt; <a href=\"kssavetopreviusparam.html\">ksSaveToPreviusParam - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Параметры конвертации при сохранении в предыдущую версию (Интерфейсы ISaveToPreviusParam, ksSaveToPreviusParam )  > ksSaveToPreviusParam - методы  > GetCurrentOptionValue - Получить текущее значение, выбранное в диалоге параметров конвертации ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">GetCurrentOptionValue - Получить текущее значение, выбранное в диалоге параметров конвертации <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xck1992080\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"isavetopreviusparam.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BSTR GetCurrentOptionValue( BSTR uniqueID );<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- текущее значение свойства.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входные параметры<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">uniqueID<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- уникальный идентификатор.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
