hmLoadTopic({
hmKeywords:"",
hmTitle:"Оформление (Интерфейс ksSheetOptions)",
hmDescription:"Интерфейс параметров оформления листа документа. Аналог данных параметров при использовании API экспортных функций - SheetOptions. Примечание: 1. Указатель на интерфейс можно",
hmPrevLink:"kssheetpar_init.html",
hmNextLink:"kssheetoptions_props.html",
hmParentLink:"ce1717197.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ce1717197.html\">Интерфейсы параметров формата и компоновки чертежа&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров формата и компоновки чертежа  > Оформление (Интерфейс ksSheetOptions) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Оформление (Интерфейс ksSheetOptions) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xce1786590\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс параметров оформления листа документа<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данных параметров при использовании API экспортных функций - <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"sheetoptions.html\" class=\"topiclink\">SheetOptions<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Указатель на интерфейс можно получить при помощи метода <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"kompasobject_getparamstruct.html\" class=\"topiclink\">KompasObject::GetParamStruct<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Данный интерфейс используется при передаче данных методом <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"kompasobject_ksgetdocoptions.html\" class=\"topiclink\">ksGetDocOptions<\/a><\/span><span class=\"f_Numbered\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssheetoptions_props.html\" class=\"topiclink hmlinklistitem\">ksSheetOptions - свойства <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssheetoptions_methods.html\" class=\"topiclink hmlinklistitem\">ksSheetOptions - методы <\/a><\/span><\/p>\n\r"
})
