hmLoadTopic({
hmKeywords:"",
hmTitle:"Init - Инициализировать параметры",
hmDescription:"Интерфейс... Синтаксис Automation: BOOL Init(); Возвращаемое значение: TRUE - в случае удачного завершения. Примечание: Метод обнуляет все параметры. Подразделы: (отсутс",
hmPrevLink:"kssheetoptions_getsheetparam.html",
hmNextLink:"ksinertiaparam.html",
hmParentLink:"kssheetoptions_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ce1717197.html\">Интерфейсы параметров формата и компоновки чертежа&nbsp;<\/a> &gt; <a href=\"kssheetoptions.html\">Оформление (Интерфейс ksSheetOptions)&nbsp;<\/a> &gt; <a href=\"kssheetoptions_methods.html\">ksSheetOptions - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Интерфейсы параметров формата и компоновки чертежа  > Оформление (Интерфейс ksSheetOptions)  > ksSheetOptions - методы  > Init - Инициализировать параметры ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Init - Инициализировать параметры <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xce1786680\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"kssheetoptions.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">BOOL Init();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">TRUE<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае удачного завершения.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Метод обнуляет все параметры.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
