hmLoadTopic({
hmKeywords:"",
hmTitle:"ISketchDefinition - методы",
hmDescription:"Подразделы: AddProjectionOf - Добавить в эскиз проекцию объекта  BeginEdit - Войти в режим редактирования эскиза (ksDocument2D)  EndEdit - Выйти из режима редактирования эскиза",
hmPrevLink:"kssketchdefinition_angle.html",
hmNextLink:"kssketchdefinition_addprojectionof.html",
hmParentLink:"kssketchdefinition.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"bw1897880.html\">Объект модели (Интерфейсы ksEntity и IEntity)&nbsp;<\/a> &gt; <a href=\"ksentity.html\">Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)&nbsp;<\/a> &gt; <a href=\"int_operation.html\">Интерфейсы формообразующих операций&nbsp;<\/a> &gt; <a href=\"kssketchdefinition.html\">Эскиз (Интерфейсы ksSketchDefinition, ISketchDefinition)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект модели (Интерфейсы ksEntity и IEntity)  > Интерфейсы ksEntity и iEntity - Интерфейс элемента модели (оси, плоскости, формообразующего элемента)  > Интерфейсы формообразующих операций  > Эскиз (Интерфейсы ksSketchDefinition, ISketchDefinition)  > ISketchDefinition - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ISketchDefinition - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_addprojectionof.html\" class=\"topiclink hmlinklistitem\">AddProjectionOf - Добавить в эскиз проекцию объекта <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_beginedit.html\" class=\"topiclink hmlinklistitem\">BeginEdit - Войти в режим редактирования эскиза (ksDocument2D) <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_endedit.html\" class=\"topiclink hmlinklistitem\">EndEdit - Выйти из режима редактирования эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_getlocation.html\" class=\"topiclink hmlinklistitem\">GetLocation - Получить смещение системы координат эскиза относительно проекции системы координат модели на плоскость эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_getloftpoint.html\" class=\"topiclink hmlinklistitem\">GetLoftPoint - Получить координаты точки в плоскости эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_getplane.html\" class=\"topiclink hmlinklistitem\">GetPlane - Получить базовую плоскость эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_getsurface.html\" class=\"topiclink hmlinklistitem\">GetSurface - Получить указатель на интерфейс математической поверхности <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_setloftpoint.html\" class=\"topiclink hmlinklistitem\">SetLoftPoint - Изменить координаты точки в плоскости эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_setlocation.html\" class=\"topiclink hmlinklistitem\">SetLocation - Изменить смещение системы координат эскиза относительно проекции системы координат модели на плоскость эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_setplane.html\" class=\"topiclink hmlinklistitem\">SetPlane - Изменить базовую плоскость эскиза <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"kssketchdefinition_usersetplacement.html\" class=\"topiclink hmlinklistitem\">UserSetPlacement - Перейти в режим указания пользователем нового положения эскиза на той же плоскости (или плоской грани), где он был расположен ранее <\/a><\/span><\/p>\n\r"
})
