hmLoadTopic({
hmKeywords:"",
hmTitle:"ksSpcStyleSectionParam - свойства",
hmDescription:"Подразделы: dataType - Способ ввода данных в колонку  number - Номер раздела  sectionName - Имя раздела  sortColumnType - Общий тип колонки, по данным в которой производится со",
hmPrevLink:"ksspcstylesectionparam.html",
hmNextLink:"ksspcstylesectionparam_datatype.html",
hmParentLink:"ksspcstylesectionparam.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksspcdocument.html\">Документ спецификация (Интерфейс ksSpcDocument)&nbsp;<\/a> &gt; <a href=\"ck1881939.html\">ksSpcDocument - методы&nbsp;<\/a> &gt; <a href=\"ck1867913.html\">Раздел спецификации&nbsp;<\/a> &gt; <a href=\"ksspcstylesectionparam.html\">Стиль раздела (Интерфейс ksSpcStyleSectionParam)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ спецификация (Интерфейс ksSpcDocument)  > ksSpcDocument - методы  > Раздел спецификации  > Стиль раздела (Интерфейс ksSpcStyleSectionParam)  > ksSpcStyleSectionParam - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksSpcStyleSectionParam - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksspcstylesectionparam_datatype.html\" class=\"topiclink hmlinklistitem\">dataType - Способ ввода данных в колонку <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksspcstylesectionparam_number.html\" class=\"topiclink hmlinklistitem\">number - Номер раздела <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksspcstylesectionparam_sectionname.html\" class=\"topiclink hmlinklistitem\">sectionName - Имя раздела <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksspcstylesectionparam_sortcolumntype.html\" class=\"topiclink hmlinklistitem\">sortColumnType - Общий тип колонки, по данным в которой производится сортировка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksspcstylesectionparam_sortispoln.html\" class=\"topiclink hmlinklistitem\">sortIspoln - Номер колонки, по данным в которой производится сортировка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksspcstylesectionparam_sorttype.html\" class=\"topiclink hmlinklistitem\">sortType - Тип сортировки объектов в разделе <\/a><\/span><\/p>\n\r"
})
