hmLoadTopic({
hmKeywords:"",
hmTitle:"ksSpiral3DHeightTypeEnum - Способ задания высоты спирали 3D",
hmDescription:"ksSHTByValue 0 По заданному значению высоты ksSHTByObject 1 По объекту ksSHTByCurve 2 По длине плоской кривой Подразделы: (отсутствуют)",
hmPrevLink:"ksspcusedtypeenum.html",
hmNextLink:"kssplinetransitiontypeenum.html",
hmParentLink:"cj1473974.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"cj1473974.html\">Константы API версии 7&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Константы API версии 7  > ksSpiral3DHeightTypeEnum - Способ задания высоты спирали 3D ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksSpiral3DHeightTypeEnum - Способ задания высоты спирали 3D <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcj1811368\" class=\"hmanchor\"><\/a><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksSHTByValue<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">0<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">По заданному значению высоты<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksSHTByObject<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">1<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">По объекту<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">ksSHTByCurve<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">2<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">По длине плоской кривой<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
