hmLoadTopic({
hmKeywords:"",
hmTitle:"ksStamp - методы",
hmDescription:"Подразделы: GetSheetNumb - Получить номер листа  ksClearStamp - Очистить основную надпись  ksCloseStamp - Закрыть основную надпись  ksColumnNumber - Определить номер ячейки осн",
hmPrevLink:"ksstamp_reference.html",
hmNextLink:"ksstamp_getsheetnumb.html",
hmParentLink:"ksstamp.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a> &gt; <a href=\"ksstamp.html\">Основная надпись (Интерфейс ksStamp)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Основная надпись (Интерфейс ksStamp)  > ksStamp - методы ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">ksStamp - методы <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_getsheetnumb.html\" class=\"topiclink hmlinklistitem\">GetSheetNumb - Получить номер листа <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_ksclearstamp.html\" class=\"topiclink hmlinklistitem\">ksClearStamp - Очистить основную надпись <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_ksclosestamp.html\" class=\"topiclink hmlinklistitem\">ksCloseStamp - Закрыть основную надпись <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_kscolumnnumber.html\" class=\"topiclink hmlinklistitem\">ksColumnNumber - Определить номер ячейки основной надписи <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_ksgetstampcolumntext.html\" class=\"topiclink hmlinklistitem\">ksGetStampColumnText - Получить текст ячейки основной надписи <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_ksopenstamp.html\" class=\"topiclink hmlinklistitem\">ksOpenStamp - Открыть основную надпись <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_kssetstampcolumntext.html\" class=\"topiclink hmlinklistitem\">ksSetStampColumnText - Задать текст в ячейке <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_kssettextlinealign.html\" class=\"topiclink hmlinklistitem\">ksSetTextLineAlign - Установить выравнивание текста <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksstamp_kstextline.html\" class=\"topiclink hmlinklistitem\">ksTextLine - Задать компоненту строки текста или строку текста полностью <\/a><\/span><\/p>\n\r"
})
