hmLoadTopic({
hmKeywords:"",
hmTitle:"IVariable - свойства",
hmDescription:"Подразделы: displayName - Отображаемое имя переменной  Expression - Выражение  External - Внешняя переменная  Information - Информационная переменная  linkDocName - Имя докуме",
hmPrevLink:"ksvariable.html",
hmNextLink:"ksvariable_displayname.html",
hmParentLink:"ksvariable.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"kspart.html\">Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart&nbsp;<\/a> &gt; <a href=\"ksfeature.html\">Объект Дерева построения (Интерфейсы ksFeature, IFeature)&nbsp;<\/a> &gt; <a href=\"ksvariablecollection.html\">Массив внешних переменных (Интерфейсы ksVariableCollection, IVariableCollection)&nbsp;<\/a> &gt; <a href=\"ksvariable.html\">Внешняя переменная (Интерфейсы ksVariable, IVariable)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Компонент сборки (деталь или подсборка). Интерфейсы ksPart и IPart  > Объект Дерева построения (Интерфейсы ksFeature, IFeature)  > Массив внешних переменных (Интерфейсы ksVariableCollection, IVariableCollection)  > Внешняя переменная (Интерфейсы ksVariable, IVariable)  > IVariable - свойства ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">IVariable - свойства <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_displayname.html\" class=\"topiclink hmlinklistitem\">displayName - Отображаемое имя переменной <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_expression.html\" class=\"topiclink hmlinklistitem\">Expression - Выражение <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_external.html\" class=\"topiclink hmlinklistitem\">External - Внешняя переменная <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_information.html\" class=\"topiclink hmlinklistitem\">Information - Информационная переменная <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_linkdocname.html\" class=\"topiclink hmlinklistitem\">linkDocName - Имя документа, в котором хранится ссылочная переменная <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_linkvarname.html\" class=\"topiclink hmlinklistitem\">linkVarName - Имя переменной, на которую задана ссылка <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_name.html\" class=\"topiclink hmlinklistitem\">name - Имя переменной <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_note.html\" class=\"topiclink hmlinklistitem\">note - Комментарий к переменной <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_parameternote.html\" class=\"topiclink hmlinklistitem\">parameterNote - Имя параметра переменной <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_pseudonym.html\" class=\"topiclink hmlinklistitem\">Pseudonym - Псевдоним переменной <\/a><\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksvariable_value.html\" class=\"topiclink hmlinklistitem\">value - Значение переменной <\/a><\/span><\/p>\n\r"
})
