hmLoadTopic({
hmKeywords:"",
hmTitle:"Prev - Получить указатель на предыдущий элемент массива",
hmDescription:"Интерфейс... Синтаксис Automation: LPDISPATCH Prev(); Синтаксис COM: LPVIEWPROJECTION Prev(); Возвращаемое значение:   - указатель на интерфейс ksViewProjection или IViewP",
hmPrevLink:"ksviewprojectioncollection_next.html",
hmNextLink:"ksviewprojectioncollection_refresh.html",
hmParentLink:"ksviewprojectioncollection_methods.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument3d.html\">Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )&nbsp;<\/a> &gt; <a href=\"ksviewprojectioncollection.html\">Интерфейс коллекции проекций отображения модели (Интерфейсы ksViewProjectionCollection, IViewProjectionCollection)&nbsp;<\/a> &gt; <a href=\"ksviewprojectioncollection_methods.html\">IViewProjectionCollection - методы&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Документ - модель (Интерфейсы - ksDocument3D, IDocument3D )  > Интерфейс коллекции проекций отображения модели (Интерфейсы ksViewProjectionCollection, IViewProjectionCollection)  > IViewProjectionCollection - методы  > Prev - Получить указатель на предыдущий элемент массива ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Prev - Получить указатель на предыдущий элемент массива <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcb1758399\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksviewprojectioncollection.html\" class=\"topiclink\">Интерфейс...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис Automation<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPDISPATCH Prev();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис COM<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">LPVIEWPROJECTION Prev();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:middle; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">&nbsp;<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- указатель на интерфейс <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksviewprojection.html\" class=\"topiclink\">ksViewProjection<\/a><\/span><span class=\"f_Table_Cell\"> или <\/span><span class=\"f_Table_Cell\" style=\"text-decoration: underline;\"><a href=\"ksviewprojection.html\" class=\"topiclink\">IViewProjection<\/a><\/span><span class=\"f_Table_Cell\">.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
