hmLoadTopic({
hmKeywords:"",
hmTitle:"Интерфейс ksViewsAndLayersManagerNotify\/IViewsAndLayersManagerNotify",
hmDescription:"Интерфейс событий менеджера видов и слоев ksViewsAndLayersManagerNotify - интерфейс Automation IViewsAndLayersManagerNotify - интерфейс COM Позволяют контролировать начало и з",
hmPrevLink:"ksspecificationobjectnotify_updateobject.html",
hmNextLink:"ksviewsandlayersmanagernotify_events.html",
hmParentLink:"sobutiy.html",
hmBreadCrumbs:"<a href=\"applicate.html\">API интерфейсов. Версия 7<\/a> &gt; <a href=\"sobutiy.html\">Интерфейсы событий&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 7 > Интерфейсы событий  > Интерфейс ksViewsAndLayersManagerNotify\/IViewsAndLayersManagerNotify",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Интерфейс ksViewsAndLayersManagerNotify\/IViewsAndLayersManagerNotify<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Интерфейс событий менеджера видов и слоев<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\" style=\"font-weight: bold;\">ksViewsAndLayersManagerNotify<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- интерфейс Automation<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\" style=\"font-weight: bold;\">IViewsAndLayersManagerNotify<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- интерфейс COM<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Позволяют контролировать начало и завершение работы с диалогом менеджера видов и слоев.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Источником событий для подписки на данный интерфейс являются объекты:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\"><a href=\"iviewsandlayersmanager.html\" class=\"topiclink\">IViewsAndLayersManager<\/a> - Менеджер слоев и видов графического документа.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\"><a href=\"ksviewsandlayersmanagernotify_events.html\" class=\"topiclink hmlinklistitem\">ksViewsAndLayersManagerNotify\/IViewsAndLayersManagerNotify - события<\/a><\/span><\/p>\n\r"
})
