hmLoadTopic({
hmKeywords:"",
hmTitle:"LIBRARYENTRY - Головная функция библиотеки",
hmDescription:"Пример... Синтаксис: extern \"C\" void far_export pascal LIBRARYENTRY(UINT Comm) Входной параметр: Сomm - идентификатор выбранной команды. Примечание: 1. При вызове команды",
hmPrevLink:"libisonapplication7.html",
hmNextLink:"libinterfacenotifyentry.html",
hmParentLink:"cr71826.html",
hmBreadCrumbs:"<a href=\"libraries_create.html\">Создание прикладных библиотек&nbsp;<\/a> &gt; <a href=\"cr92212.html\">Оформление прикладных библиотек типа DLL&nbsp;<\/a> &gt; <a href=\"simple_sample.html\">Пример простейшей программы в среде VC++, оформленной в виде библиотеки КОМПАС&nbsp;<\/a> &gt; <a href=\"cr71826.html\">Функции&nbsp;<\/a>",
hmTitlePath:"Создание прикладных библиотек  > Оформление прикладных библиотек типа DLL  > Пример простейшей программы в среде VC++, оформленной в виде библиотеки КОМПАС  > Функции  > LIBRARYENTRY - Головная функция библиотеки ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">LIBRARYENTRY - Головная функция библиотеки <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcr91646\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"libraryentry_example.html\" class=\"topiclink\">Пример...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">extern &quot;C&quot; void far_export pascal LIBRARYENTRY(UINT Comm)<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Входной параметр<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">Сomm<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- идентификатор выбранной команды.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. При вызове команды библиотеки из меню, панели инструментов или при редактировании библиотечного элемента по двойному нажатию кнопки мыши управление передается этой функции с номером выбранной команды.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Библиотека должна обязательно содержать предопределенную функцию LIBRARYENTRY, которая определяет точку входа в приложение или <\/span><span class=\"f_Numbered\" style=\"text-decoration: underline;\"><a href=\"libinterfacenotifyentry.html\" class=\"topiclink\">LibInterfaceNotifyEntry<\/a><\/span><span class=\"f_Numbered\">. При обращении к библиотеке именно ей передается управление. Кроме того, ее наличие позволяет системе КОМПАС идентифицировать произвольный DLL-файл как собственное приложение.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
