hmLoadTopic({
hmKeywords:"",
hmTitle:"NewViewNumber - Определить номер следующего вида",
hmDescription:"Пример... Аналог данной функции при использовании Automation - метод ksDocument2D::ksNewViewNumber. Синтаксис: int NewViewNumber(); Возвращаемое значение: номер следующего в",
hmPrevLink:"kspoint3dtoassociationview.html",
hmNextLink:"openview.html",
hmParentLink:"views_fncts_common.html",
hmBreadCrumbs:"<a href=\"export_function.html\">API экспортных функций<\/a> &gt; <a href=\"cm1726661.html\">Функции работы с графическим документом&nbsp;<\/a> &gt; <a href=\"cm1826821.html\">Работа с видами&nbsp;<\/a> &gt; <a href=\"views_fncts_common.html\">Функции работы с видами&nbsp;<\/a>",
hmTitlePath:"API экспортных функций > Функции работы с графическим документом  > Работа с видами  > Функции работы с видами  > NewViewNumber - Определить номер следующего вида ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">NewViewNumber - Определить номер следующего вида <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcm1890565\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"newviewnumber_example.html\" class=\"topiclink\">Пример...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Аналог данной функции при использовании Automation - метод <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2d_ksnewviewnumber.html\" class=\"topiclink\">ksDocument2D::ksNewViewNumber<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Синтаксис<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">int NewViewNumber();<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Возвращаемое значение<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">номер следующего вида<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае успешного завершения,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">0<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">- в случае неудачи.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
