hmLoadTopic({
hmKeywords:"",
hmTitle:"Источник событий объектов графического документа (Интерфейс Object2DNotify)",
hmDescription:"Источник событий объектов графического документа. В Automation источник событий для графического документа Object2DNotify можно получить при помощи метода ksDocument2D::GetObjec",
hmPrevLink:"selectionmngnotify.html",
hmNextLink:"document2dnotify.html",
hmParentLink:"ksdocument2d.html",
hmBreadCrumbs:"<a href=\"ag57940.html\">API интерфейсов. Версия 5<\/a> &gt; <a href=\"ksdocument2d.html\">Графический документ (Интерфейсы - ksDocument2D и IDocument2D)&nbsp;<\/a>",
hmTitlePath:"API интерфейсов. Версия 5 > Графический документ (Интерфейсы - ksDocument2D и IDocument2D)  > Источник событий объектов графического документа (Интерфейс Object2DNotify) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Источник событий объектов графического документа (Интерфейс Object2DNotify) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xce1784618\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Источник событий объектов графического документа<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">В Automation источник событий для графического документа Object2DNotify можно получить при помощи метода <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksdocument2d_getobject2dnotify.html\" class=\"topiclink\">ksDocument2D::GetObject2DNotify<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">В СOM контейнером для подписки на данный интерфейс является указатель на графический документ или документ-модель.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"ksobject2dnotify.html\" class=\"topiclink\">Интерфейс событий объектов графического документа...<\/a><\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">:<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">Интерфейс позволяет следить и управлять редактированием объектов графического документа.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
