hmLoadTopic({
hmKeywords:"",
hmTitle:"Rough - Пример использования",
hmDescription:"void Rough_Example (void) { reference p; RoughParam roughPar; memset (&roughPar, 0, sizeof (RoughParam));   \/\/заполним параметры шероховатости roughPar.rPar.type=0; \/\/ без",
hmPrevLink:"",
hmNextLink:"",
hmParentLink:"compiling_libraries.html",
hmBreadCrumbs:"",
hmTitlePath:"Компиляция библиотек > Использование библиотек типов интерфейсов Системы КОМПАС-3D",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Rough - Пример использования <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xcg1723656\" class=\"hmanchor\"><\/a><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">void Rough_Example (void)<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">{<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">reference p;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">RoughParam roughPar;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">memset (&amp;roughPar, 0, sizeof (RoughParam));<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/заполним параметры шероховатости<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.type=0; \/\/ без обработки<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.around=0;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.x = 50; roughPar.rPar.y = 50; \/\/ опорная точка<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.ang = 90; \/\/ угол наклона оси знака<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.cText0=1; \/\/ строк над знаком<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.cText1=0; \/\/ строк над полкой<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.cText2=0; \/\/ строк под полкой<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.cText3=0; \/\/ строк под полкой<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/ массив неопределенной длины строк текста<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.rPar.pText =CreateArray (CHAR_STR_ARR ,0);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">AddArrayItem (roughPar.rPar.pText, -1, 6,3, 4);<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">\/\/параметры выносной полки<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.shPar.psh = 0; \/\/ полки нет<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.shPar.ang = 130; \/\/ угол наклона ножки<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">roughPar.shPar.length= 20; \/\/ длина ножки<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">&nbsp;<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">p = Rough (&amp;roughPar); \/\/ шероховатость<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">};<\/span><\/p>\n\r"
})
