hmLoadTopic({
hmKeywords:"",
hmTitle:"VariableParamW - Структура параметров параметрической переменной (Unicode)",
hmDescription:"wchar_t name [MAX_TEXT_LENGTH] имя переменной, double value значение переменной, wchar_t note [MAX_TEXT_LENGTH] комментарий. Примечание. При использовании ANSI следует",
hmPrevLink:"structvariableparam.html",
hmNextLink:"bk1844167.html",
hmParentLink:"bk1803366.html",
hmBreadCrumbs:"<a href=\"3d_define.html\">Структуры параметров и константы<\/a> &gt; <a href=\"bk1803366.html\">Структуры параметров системы&nbsp;<\/a>",
hmTitlePath:"Структуры параметров и константы > Структуры параметров системы  > VariableParamW - Структура параметров параметрической переменной (Unicode) ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">VariableParamW - Структура параметров параметрической переменной (Unicode) <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_bodytext\"><a id=\"xbk1920310\" class=\"hmanchor\"><\/a><\/p>\n\r<div style=\"text-align: left; text-indent: 0; line-height: 1.48; padding: 0 0 0 0; margin: 0.2500rem 0 0 4.1250rem;\"><table style=\"border:none; border-spacing:0;\">\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">wchar_t<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">name [MAX_TEXT_LENGTH]<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">имя переменной,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">double<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">value<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">значение переменной,<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<tr>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">wchar_t<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">note [MAX_TEXT_LENGTH]<\/span><\/p>\n\r<\/td>\n\r<td style=\"vertical-align:top; padding:0; border:none\"><p class=\"p_Table_Cell\"><span class=\"f_Table_Cell\">комментарий.<\/span><\/p>\n\r<\/td>\n\r<\/tr>\n\r<\/table>\n\r<\/div>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание<\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\">При использовании ANSI следует использовать структуру параметров <\/span><span class=\"f_bodytext\" style=\"text-decoration: underline;\"><a href=\"structvariableparam.html\" class=\"topiclink\">VariableParam<\/a><\/span><span class=\"f_bodytext\">.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
