hmLoadTopic({
hmKeywords:"",
hmTitle:"Описание значков на кнопках инструментальных панелей",
hmDescription:"1. Интервалов идентификаторов значков кнопок может быть несколько. Значения идентификаторов должны быть больше 1000, так как интервал от 0 до 1000 предназначен для ID слайдов,...",
hmPrevLink:"libdlltype_library_status.html",
hmNextLink:"cr69365.html",
hmParentLink:"libraries_create.html",
hmBreadCrumbs:"<a href=\"libraries_create.html\">Создание прикладных библиотек&nbsp;<\/a>",
hmTitlePath:"Создание прикладных библиотек  > Описание значков на кнопках инструментальных панелей ",
hmHeader:"<h1 class=\"p_Heading1\"><span class=\"f_Heading1\">Описание значков на кнопках инструментальных панелей <\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Numbered\"><span class=\"f_Numbered\">1. Интервалов идентификаторов значков кнопок может быть несколько. Значения идентификаторов должны быть больше 1000, так как интервал от 0 до 1000 предназначен для ID слайдов, отображающихся в менеджере библиотек.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">2. Поддерживаются следующие размеры значков (в пикселах):<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\">16*16,<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\">24*24,<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\">32*32,<\/span><\/p>\n\r<p class=\"p_bulleted\" style=\"text-indent: 0; padding-left: 0.8125rem; margin-left: 4.5625rem;\"><span class=\"f_bulleted\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:0.8125rem;margin-left:-0.8125rem\">&#8226;<\/span><span class=\"f_bulleted\">48*48.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">3. Глубина цвета значков может составлять 24 бита (TrueColor).<\/span><\/p>\n\r<p class=\"p_bodytext\"><span class=\"f_bodytext\" style=\"font-weight: bold;\">Примечание:<\/span><span class=\"f_bodytext\"> Цвет RGB: 192, 192, 192 считается прозрачным.<\/span><\/p>\n\r<p class=\"p_Numbered\"><span class=\"f_Numbered\">4. Для значка собственно панели команд, отображаемой на компактной панели, достаточно создать файл значка с расширением ico, содержащий значки размеров 12*12, 18*18, 24*24, 36*36 пикселов. Значки должны располагаться в файле в порядке возрастания размера. Глубина цвета значка должна составлять 24 бита (TrueColor). Файл может содержать один значок. В таком случае остальные типоразмеры значка будут получены масштабированием.<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC_Title\" style=\"border-top: none; border-right: none; border-left: none;\"><span class=\"f_Z_LOC_TOC_Title\">Подразделы:<\/span><\/p>\n\r<p class=\"p_Z_LOC_TOC\"><span class=\"f_Z_LOC_TOC\">(отсутствуют)<\/span><\/p>\n\r"
})
