// <auto-generated />
using System;
using Apeiron.Platform.Databases.OrioleKmtDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OrioleKmtDatabaseContext))]
    [Migration("20220404122802_AnalyzedFrame_Add_Fields_for_Processed")]
    partial class AnalyzedFrame_Add_Fields_for_Processed
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.AnalyzedFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("CurvatureAverage")
                        .HasColumnType("float");

                    b.Property<double>("CurvatureMax")
                        .HasColumnType("float");

                    b.Property<double>("CurvatureMin")
                        .HasColumnType("float");

                    b.Property<double>("DurationBraking")
                        .HasColumnType("float");

                    b.Property<double>("DurationParking")
                        .HasColumnType("float");

                    b.Property<double>("DurationRunout")
                        .HasColumnType("float");

                    b.Property<double>("DurationTraction")
                        .HasColumnType("float");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPocessed")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("TractionEffortCount")
                        .HasColumnType("int");

                    b.Property<double>("TractionEffortMax")
                        .HasColumnType("float");

                    b.Property<double>("TractionEffortMin")
                        .HasColumnType("float");

                    b.Property<double>("TractionEffortSquaredSum")
                        .HasColumnType("float");

                    b.Property<double>("TractionEffortSum")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("IsPocessed");

                    b.ToTable("AnalyzedFrames");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.ChannelName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TimeChunkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Index");

                    b.HasIndex("Name");

                    b.HasIndex("TimeChunkId");

                    b.ToTable("ChannelNames");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.RawFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNormalizedTime")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("BeginTime");

                    b.HasIndex("EndTime");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("IsNormalizedTime");

                    b.HasIndex("Time");

                    b.ToTable("RawFrames");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.TimeChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BeginTime");

                    b.HasIndex("EndTime");

                    b.HasIndex("Id");

                    b.ToTable("TimeChunks");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.ChannelName", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.TimeChunk", "TimeChunk")
                        .WithMany("ChannelNames")
                        .HasForeignKey("TimeChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChannelNames_TimeChunk");

                    b.Navigation("TimeChunk");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.TimeChunk", b =>
                {
                    b.Navigation("ChannelNames");
                });
#pragma warning restore 612, 618
        }
    }
}
