// <auto-generated />
using System;
using Apeiron.Platform.Databases.OrioleDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OrioleDatabaseContext))]
    [Migration("20211223122034_Add_Target_Fields_In_Statistics_Table")]
    partial class Add_Target_Fields_In_Statistics_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Amplitude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Frequency")
                        .HasColumnType("float");

                    b.Property<double>("Imaginary")
                        .HasColumnType("float");

                    b.Property<double>("Magnitude")
                        .HasColumnType("float");

                    b.Property<double>("Phase")
                        .HasColumnType("float");

                    b.Property<double>("Real")
                        .HasColumnType("float");

                    b.Property<long>("SpectrumId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Frequency");

                    b.HasIndex("Magnitude");

                    b.HasIndex("SpectrumId");

                    b.ToTable("Amplitudes");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Cutoff");

                    b.HasIndex("Name");

                    b.HasIndex("RegistrarId");

                    b.HasIndex("Sampling");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Filter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Cutoff");

                    b.HasIndex("Id");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Frame", b =>
                {
                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSpectrum")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatistic")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistrarId", "Timestamp");

                    b.HasIndex("IsSpectrum");

                    b.HasIndex("IsStatistic");

                    b.HasIndex("RegistrarId");

                    b.HasIndex("Time");

                    b.HasIndex("Timestamp");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Geolocation", b =>
                {
                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<double?>("Altitude")
                        .HasColumnType("float");

                    b.Property<double?>("Geoidal")
                        .HasColumnType("float");

                    b.Property<double?>("Hdop")
                        .HasColumnType("float");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Knots")
                        .HasColumnType("float");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("float");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("float");

                    b.Property<int?>("Satellites")
                        .HasColumnType("int");

                    b.Property<int?>("Solution")
                        .HasColumnType("int");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<int?>("Station")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("RegistrarId", "Timestamp");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("RegistrarId");

                    b.HasIndex("Speed");

                    b.HasIndex("Time");

                    b.HasIndex("Timestamp");

                    b.ToTable("Geolocations");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.GgaMessage", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<double?>("Altitude")
                        .HasColumnType("float");

                    b.Property<double?>("Geoidal")
                        .HasColumnType("float");

                    b.Property<double?>("Hdop")
                        .HasColumnType("float");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<int?>("Satellites")
                        .HasColumnType("int");

                    b.Property<int?>("Solution")
                        .HasColumnType("int");

                    b.Property<int?>("Station")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.HasKey("RawDirectoryId", "FileTime", "Index");

                    b.HasIndex("FileTime");

                    b.HasIndex("Index");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("RawDirectoryId");

                    b.HasIndex("RegistrarId");

                    b.ToTable("GgaMessages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Altitude")
                        .HasColumnType("float");

                    b.Property<double>("FirstVerticalRadius")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.Property<double>("Z")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Altitude");

                    b.HasIndex("FirstVerticalRadius");

                    b.HasIndex("Id");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("X");

                    b.HasIndex("Y");

                    b.HasIndex("Z");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.NmeaFile", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("bit");

                    b.HasKey("RawDirectoryId", "Time");

                    b.HasIndex("IsLoaded");

                    b.ToTable("NmeaFiles");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Package", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileOffset")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Synchromarker")
                        .HasColumnType("bigint");

                    b.HasKey("RawDirectoryId", "Format", "FileTime", "FileOffset");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("Synchromarker");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.PackageFile", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<long>("FirstSynchromarker")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNormalized")
                        .HasColumnType("bit");

                    b.Property<long>("LastSynchromarker")
                        .HasColumnType("bigint");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("NormalizedBeginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NormalizedEndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<int>("SequentialIndex")
                        .HasColumnType("int");

                    b.HasKey("RawDirectoryId", "Format", "Time");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("IsLoaded");

                    b.HasIndex("IsNormalized");

                    b.HasIndex("LocationType");

                    b.HasIndex("NormalizedBeginTime");

                    b.HasIndex("NormalizedEndTime");

                    b.ToTable("PackageFiles");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RawDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RecordDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RecordDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Registrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RmcMessage", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Knots")
                        .HasColumnType("float");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("float");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("float");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<bool?>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("RawDirectoryId", "FileTime", "Index");

                    b.HasIndex("FileTime");

                    b.HasIndex("Index");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("RawDirectoryId");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RmcMessages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("_Timeout")
                        .HasColumnType("int")
                        .HasColumnName("Timeout");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("Signal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeginTime");

                    b.HasIndex("ChannelId");

                    b.HasIndex("EndTime");

                    b.HasIndex("Format");

                    b.HasIndex("Sampling");

                    b.HasIndex("SensorId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Spectrum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RegistrarId", "Timestamp");

                    b.ToTable("Spectrums");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Statistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double>("Average")
                        .HasColumnType("float");

                    b.Property<double>("AverageModulo")
                        .HasColumnType("float");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.Property<double>("Deviation")
                        .HasColumnType("float");

                    b.Property<double>("DeviationModulo")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<double>("MaxModulo")
                        .HasColumnType("float");

                    b.Property<double>("Min")
                        .HasColumnType("float");

                    b.Property<double>("MinModulo")
                        .HasColumnType("float");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<double>("Speed")
                        .HasColumnType("float");

                    b.Property<double>("SquaresSum")
                        .HasColumnType("float");

                    b.Property<double>("Sum")
                        .HasColumnType("float");

                    b.Property<double>("SumModulo")
                        .HasColumnType("float");

                    b.Property<long>("_Timestamp")
                        .HasColumnType("bigint")
                        .HasColumnName("Timestamp");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChannelId", "RegistrarId", "_Timestamp", "Cutoff");

                    b.HasIndex("Average");

                    b.HasIndex("AverageModulo");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Count");

                    b.HasIndex("Cutoff");

                    b.HasIndex("Deviation");

                    b.HasIndex("DeviationModulo");

                    b.HasIndex("Id");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("Max");

                    b.HasIndex("MaxModulo");

                    b.HasIndex("Min");

                    b.HasIndex("MinModulo");

                    b.HasIndex("RegistrarId");

                    b.HasIndex("Speed");

                    b.HasIndex("SquaresSum");

                    b.HasIndex("Sum");

                    b.HasIndex("SumModulo");

                    b.HasIndex("_Timestamp");

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("RegistrarId", "_Timestamp");

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.VtgMessage", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Knots")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("float");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("float");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.HasKey("RawDirectoryId", "FileTime", "Index");

                    b.HasIndex("FileTime");

                    b.HasIndex("Index");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("RawDirectoryId");

                    b.HasIndex("RegistrarId");

                    b.ToTable("VtgMessages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Amplitude", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Spectrum", "Spectrum")
                        .WithMany("Amplitudes")
                        .HasForeignKey("SpectrumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Amplitudes_Spectrums");

                    b.Navigation("Spectrum");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Channel", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("Channels")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_Channels_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Frame", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("Frames")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_Frames_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Geolocation", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("Geolocations")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_Geolocations_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.GgaMessage", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("GgaMessages")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_GgaMessages_RawDirectories");

                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("GgaMessages")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_GgaMessages_Registrars");

                    b.HasOne("Apeiron.Oriole.Server.Database.NmeaFile", "NmeaFile")
                        .WithMany("GgaMessages")
                        .HasForeignKey("RawDirectoryId", "FileTime")
                        .IsRequired()
                        .HasConstraintName("FK_GgaMessages_NmeaFiles");

                    b.Navigation("NmeaFile");

                    b.Navigation("RawDirectory");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.NmeaFile", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("NmeaFiles")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_NmeaFiles_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Package", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("Packages")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Packages_RawDirectories");

                    b.HasOne("Apeiron.Oriole.Server.Database.PackageFile", "PackageFile")
                        .WithMany("Packages")
                        .HasForeignKey("RawDirectoryId", "Format", "FileTime")
                        .IsRequired()
                        .HasConstraintName("FK_Packages_PackageFiles");

                    b.Navigation("PackageFile");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.PackageFile", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("PackageFiles")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_PackageFiles_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RawDirectories")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RawDirectories_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RecordDirectory", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RecordDirectories")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RecordDirectories_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RmcMessage", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("RmcMessages")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_RmcMessages_RawDirectories");

                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RmcMessages")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RmcMessages_Registrars");

                    b.HasOne("Apeiron.Oriole.Server.Database.NmeaFile", "NmeaFile")
                        .WithMany("RmcMessages")
                        .HasForeignKey("RawDirectoryId", "FileTime")
                        .IsRequired()
                        .HasConstraintName("FK_RmcMessages_NmeaFiles");

                    b.Navigation("NmeaFile");

                    b.Navigation("RawDirectory");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Source", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Channel", "Channel")
                        .WithMany("Sources")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_Sources_Channels");

                    b.HasOne("Apeiron.Oriole.Server.Database.Sensor", "Sensor")
                        .WithMany("Sources")
                        .HasForeignKey("SensorId")
                        .IsRequired()
                        .HasConstraintName("FK_Sources_Sensors");

                    b.Navigation("Channel");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Spectrum", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Channel", "Channel")
                        .WithMany("Spectrums")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_Spectrums_Channels");

                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("Spectrums")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_Spectrums_Registrars");

                    b.HasOne("Apeiron.Oriole.Server.Database.Frame", "Frame")
                        .WithMany("Spectrums")
                        .HasForeignKey("RegistrarId", "Timestamp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Spectrums_Frames");

                    b.Navigation("Channel");

                    b.Navigation("Frame");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Statistic", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Channel", "_Channel")
                        .WithMany("Statistics")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_Statistics_Channels");

                    b.HasOne("Apeiron.Oriole.Server.Database.Filter", "_Filter")
                        .WithMany("Statistics")
                        .HasForeignKey("Cutoff")
                        .HasPrincipalKey("Cutoff")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Statistics_Filters");

                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "_Registrar")
                        .WithMany("Statistics")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_Statistics_Registrars");

                    b.HasOne("Apeiron.Oriole.Server.Database.Location", "_Location")
                        .WithMany("Statistics")
                        .HasForeignKey("Latitude", "Longitude")
                        .HasPrincipalKey("Latitude", "Longitude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Statistics_Locations");

                    b.HasOne("Apeiron.Oriole.Server.Database.Frame", "_Frame")
                        .WithMany("Statistics")
                        .HasForeignKey("RegistrarId", "_Timestamp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Statistics_Frames");

                    b.Navigation("_Channel");

                    b.Navigation("_Filter");

                    b.Navigation("_Frame");

                    b.Navigation("_Location");

                    b.Navigation("_Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.VtgMessage", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("VtgMessages")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_VtgMessages_RawDirectories");

                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("VtgMessages")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_VtgMessages_Registrars");

                    b.HasOne("Apeiron.Oriole.Server.Database.NmeaFile", "NmeaFile")
                        .WithMany("VtgMessages")
                        .HasForeignKey("RawDirectoryId", "FileTime")
                        .IsRequired()
                        .HasConstraintName("FK_VtgMessages_NmeaFiles");

                    b.Navigation("NmeaFile");

                    b.Navigation("RawDirectory");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Channel", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("Spectrums");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Filter", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Frame", b =>
                {
                    b.Navigation("Spectrums");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Location", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.NmeaFile", b =>
                {
                    b.Navigation("GgaMessages");

                    b.Navigation("RmcMessages");

                    b.Navigation("VtgMessages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.PackageFile", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.Navigation("GgaMessages");

                    b.Navigation("NmeaFiles");

                    b.Navigation("PackageFiles");

                    b.Navigation("Packages");

                    b.Navigation("RmcMessages");

                    b.Navigation("VtgMessages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Registrar", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Frames");

                    b.Navigation("Geolocations");

                    b.Navigation("GgaMessages");

                    b.Navigation("RawDirectories");

                    b.Navigation("RecordDirectories");

                    b.Navigation("RmcMessages");

                    b.Navigation("Spectrums");

                    b.Navigation("Statistics");

                    b.Navigation("VtgMessages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Sensor", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Spectrum", b =>
                {
                    b.Navigation("Amplitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
