// <auto-generated />
using System;
using Apeiron.Platform.Databases.OrioleDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OrioleDatabaseContext))]
    [Migration("20211210123637_Add_Length_In_Packages_Table")]
    partial class Add_Length_In_Packages_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Cutoff");

                    b.HasIndex("Name");

                    b.HasIndex("RegistrarId");

                    b.HasIndex("Sampling");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Package", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileOffset")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Synchromarker")
                        .HasColumnType("bigint");

                    b.HasKey("RawDirectoryId", "Format", "FileTime", "FileOffset");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("Synchromarker");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.PackageFile", b =>
                {
                    b.Property<int>("RawDirectoryId")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("bit");

                    b.HasKey("RawDirectoryId", "Format", "Time");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("IsLoaded");

                    b.ToTable("PackageFiles");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RawDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RecordDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RecordDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Registrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<double>("Cutoff")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<int>("Signal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeginTime");

                    b.HasIndex("ChannelId");

                    b.HasIndex("EndTime");

                    b.HasIndex("Format");

                    b.HasIndex("Sampling");

                    b.HasIndex("SensorId");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Channel", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("Channels")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_Channels_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Package", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("Packages")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Packages_RawDirectories");

                    b.HasOne("Apeiron.Oriole.Server.Database.PackageFile", "PackageFile")
                        .WithMany("Packages")
                        .HasForeignKey("RawDirectoryId", "Format", "FileTime")
                        .IsRequired()
                        .HasConstraintName("FK_Packages_PackageFiles");

                    b.Navigation("PackageFile");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.PackageFile", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.RawDirectory", "RawDirectory")
                        .WithMany("PackageFiles")
                        .HasForeignKey("RawDirectoryId")
                        .IsRequired()
                        .HasConstraintName("FK_PackageFiles_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RawDirectories")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RawDirectories_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RecordDirectory", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RecordDirectories")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RecordDirectories_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Source", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Channel", "Channel")
                        .WithMany("Sources")
                        .HasForeignKey("ChannelId")
                        .IsRequired()
                        .HasConstraintName("FK_Sources_Channels");

                    b.HasOne("Apeiron.Oriole.Server.Database.Sensor", "Sensor")
                        .WithMany("Sources")
                        .HasForeignKey("SensorId")
                        .IsRequired()
                        .HasConstraintName("FK_Sources_Sensors");

                    b.Navigation("Channel");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Channel", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.PackageFile", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.Navigation("PackageFiles");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Registrar", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("RawDirectories");

                    b.Navigation("RecordDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Sensor", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
