// <auto-generated />
using System;
using Apeiron.Platform.Databases.OrioleDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OrioleDatabaseContext))]
    [Migration("20211210071713_Add_Sensors_Table")]
    partial class Add_Sensors_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Package", b =>
                {
                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<int>("SensorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileOffset")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Synchromarker")
                        .HasColumnType("bigint");

                    b.HasKey("RegistrarId", "SensorNumber", "FileTime", "FileOffset");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("StartTime");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RawDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RecordDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrarId");

                    b.ToTable("RecordDirectories");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Registrar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registrars");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RawDirectory", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RawDirectories")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RawDirectories_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.RecordDirectory", b =>
                {
                    b.HasOne("Apeiron.Oriole.Server.Database.Registrar", "Registrar")
                        .WithMany("RecordDirectories")
                        .HasForeignKey("RegistrarId")
                        .IsRequired()
                        .HasConstraintName("FK_RecordDirectories_Registrars");

                    b.Navigation("Registrar");
                });

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Registrar", b =>
                {
                    b.Navigation("RawDirectories");

                    b.Navigation("RecordDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
