// <auto-generated />
using System;
using Apeiron.Platform.Databases.OrioleDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OrioleDatabaseContext))]
    [Migration("20211209133459_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Oriole.Server.Database.Package", b =>
                {
                    b.Property<int>("RegistrarId")
                        .HasColumnType("int");

                    b.Property<int>("SensorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileOffset")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double>("Sampling")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("Synchromarker")
                        .HasColumnType("bigint");

                    b.HasKey("RegistrarId", "SensorNumber", "FileTime", "FileOffset");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("StartTime");

                    b.ToTable("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
