//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apeiron.Platform.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apeiron.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная контрольная сумма пакета данных Adxl..
        /// </summary>
        internal static string AdxlInvalidChecksum {
            get {
                return ResourceManager.GetString("AdxlInvalidChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат пакета данных Adxl..
        /// </summary>
        internal static string AdxlInvalidFormat {
            get {
                return ResourceManager.GetString("AdxlInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная сигнатура пакета данных Adxl..
        /// </summary>
        internal static string AdxlInvalidSignature {
            get {
                return ResourceManager.GetString("AdxlInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано значение, которое уже содержится коллекции..
        /// </summary>
        internal static string ArgumentAlreadyContainedInCollection {
            get {
                return ResourceManager.GetString("ArgumentAlreadyContainedInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан массив, размер которого больше максимально допустимого..
        /// </summary>
        internal static string ArgumentArrayLargerMax {
            get {
                return ResourceManager.GetString("ArgumentArrayLargerMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан массив, размер которого меньше минимально допустимого..
        /// </summary>
        internal static string ArgumentArrayLessMin {
            get {
                return ResourceManager.GetString("ArgumentArrayLessMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан пустой массив..
        /// </summary>
        internal static string ArgumentEmptyArray {
            get {
                return ResourceManager.GetString("ArgumentEmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передана пустая коллекция..
        /// </summary>
        internal static string ArgumentEmptyCollection {
            get {
                return ResourceManager.GetString("ArgumentEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передана пустая строка..
        /// </summary>
        internal static string ArgumentEmptyString {
            get {
                return ResourceManager.GetString("ArgumentEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан пустой вектор..
        /// </summary>
        internal static string ArgumentEmptyVector {
            get {
                return ResourceManager.GetString("ArgumentEmptyVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано бесконечное значение..
        /// </summary>
        internal static string ArgumentInfinity {
            get {
                return ResourceManager.GetString("ArgumentInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан недопустимый таймаут..
        /// </summary>
        internal static string ArgumentInvalidTimeout {
            get {
                return ResourceManager.GetString("ArgumentInvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан объект недопустимого типа..
        /// </summary>
        internal static string ArgumentInvalidType {
            get {
                return ResourceManager.GetString("ArgumentInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан многомерный массив..
        /// </summary>
        internal static string ArgumentMultidimensionalArray {
            get {
                return ResourceManager.GetString("ArgumentMultidimensionalArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано нечисловое значение..
        /// </summary>
        internal static string ArgumentNaN {
            get {
                return ResourceManager.GetString("ArgumentNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано отрицательное значение..
        /// </summary>
        internal static string ArgumentNegativeValue {
            get {
                return ResourceManager.GetString("ArgumentNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано значение, которое не содержится в коллекции..
        /// </summary>
        internal static string ArgumentNotContainedInCollection {
            get {
                return ResourceManager.GetString("ArgumentNotContainedInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано значение, которое не содержится в перечислении {1}..
        /// </summary>
        internal static string ArgumentNotContainedInEnumeration {
            get {
                return ResourceManager.GetString("ArgumentNotContainedInEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано значение, которое не является степенью двух..
        /// </summary>
        internal static string ArgumentNotPowerOfTwo {
            get {
                return ResourceManager.GetString("ArgumentNotPowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передана пустая ссылка..
        /// </summary>
        internal static string ArgumentNullReference {
            get {
                return ResourceManager.GetString("ArgumentNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано значение, которое не соответствует допустимому диапазону значений..
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан диапазон, в котором начальный индекс превышает допустимое значение..
        /// </summary>
        internal static string ArgumentRangeLargeIndex {
            get {
                return ResourceManager.GetString("ArgumentRangeLargeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан диапазон, в котором начальный индекс отрицательный..
        /// </summary>
        internal static string ArgumentRangeNegativeIndex {
            get {
                return ResourceManager.GetString("ArgumentRangeNegativeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан диапазон, в котором отрицательная длина..
        /// </summary>
        internal static string ArgumentRangeNegativeLength {
            get {
                return ResourceManager.GetString("ArgumentRangeNegativeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передан диапазон, который выходит за пределы коллекции..
        /// </summary>
        internal static string ArgumentRangeNotBelong {
            get {
                return ResourceManager.GetString("ArgumentRangeNotBelong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передана строка, которая содержит недопустимый символ..
        /// </summary>
        internal static string ArgumentStringContainInvalidChar {
            get {
                return ResourceManager.GetString("ArgumentStringContainInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передана строка, длина которой больше максимально допустимого..
        /// </summary>
        internal static string ArgumentStringLargerMax {
            get {
                return ResourceManager.GetString("ArgumentStringLargerMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передана строка, длина которой меньше минимально допустимого..
        /// </summary>
        internal static string ArgumentStringLessMin {
            get {
                return ResourceManager.GetString("ArgumentStringLessMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В параметре {0} передано нулевое значение..
        /// </summary>
        internal static string ArgumentZeroValue {
            get {
                return ResourceManager.GetString("ArgumentZeroValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные базы данных не загружены..
        /// </summary>
        internal static string DatabaseDataNotLoaded {
            get {
                return ResourceManager.GetString("DatabaseDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица базы данных не найдена..
        /// </summary>
        internal static string DatabaseTableNotFound {
            get {
                return ResourceManager.GetString("DatabaseTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размеры данных не совпадают..
        /// </summary>
        internal static string DataSizesDoNotMatch {
            get {
                return ResourceManager.GetString("DataSizesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат кадра..
        /// </summary>
        internal static string FrameInvalidFormat {
            get {
                return ResourceManager.GetString("FrameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная сигнатура кадра..
        /// </summary>
        internal static string FrameInvalidSignature {
            get {
                return ResourceManager.GetString("FrameInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Член {0} не найден..
        /// </summary>
        internal static string MarshalMemberNotFound {
            get {
                return ResourceManager.GetString("MarshalMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект {0} не найден..
        /// </summary>
        internal static string MarshalObjectNotFound {
            get {
                return ResourceManager.GetString("MarshalObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная контрольная сумма строки в формате NMEA..
        /// </summary>
        internal static string NmeaInvalidChecksum {
            get {
                return ResourceManager.GetString("NmeaInvalidChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат строки в формате NMEA..
        /// </summary>
        internal static string NmeaInvalidFormat {
            get {
                return ResourceManager.GetString("NmeaInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная сигнатура строки в формате NMEA..
        /// </summary>
        internal static string NmeaInvalidSignature {
            get {
                return ResourceManager.GetString("NmeaInvalidSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция отменена..
        /// </summary>
        internal static string OperationCanceled {
            get {
                return ResourceManager.GetString("OperationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на После создания перечислителя семейство было изменено..
        /// </summary>
        internal static string OperationEnumerationChanged {
            get {
                return ResourceManager.GetString("OperationEnumerationChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимая операция..
        /// </summary>
        internal static string OperationInvalid {
            get {
                return ResourceManager.GetString("OperationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое преобразование.
        /// </summary>
        internal static string OperationInvalidConversion {
            get {
                return ResourceManager.GetString("OperationInvalidConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция не поддерживается..
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В результате операции произошло обращение к разрушенному объекту..
        /// </summary>
        internal static string OperationObjectDisposed {
            get {
                return ResourceManager.GetString("OperationObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция привела к переполнению..
        /// </summary>
        internal static string OperationOverflow {
            get {
                return ResourceManager.GetString("OperationOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время ожидания операции истекло..
        /// </summary>
        internal static string OperationTimeout {
            get {
                return ResourceManager.GetString("OperationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Достигнут конец потока..
        /// </summary>
        internal static string StreamEnd {
            get {
                return ResourceManager.GetString("StreamEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат потока..
        /// </summary>
        internal static string StreamInvalidFormat {
            get {
                return ResourceManager.GetString("StreamInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток не поддерживает чтение..
        /// </summary>
        internal static string StreamNotReadable {
            get {
                return ResourceManager.GetString("StreamNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток не поддерживает поиск..
        /// </summary>
        internal static string StreamNotSearchable {
            get {
                return ResourceManager.GetString("StreamNotSearchable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поток не поддерживает запись..
        /// </summary>
        internal static string StreamNotWritable {
            get {
                return ResourceManager.GetString("StreamNotWritable", resourceCulture);
            }
        }
    }
}
