// <auto-generated />
using Apeiron.Platform.Demo.AdxlDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Demo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221206090228_Update_ChannelInfos_Table")]
    partial class Update_ChannelInfos_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Apeiron.Platform.Demo.AdxlDemo.Channels.ChannelInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cutoff")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Sampling")
                        .HasColumnType("REAL");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChannelInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
