// <auto-generated />
using Apeiron.Platform.Databases.OsmDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(OsmDatabaseContext))]
    [Migration("20220411140537_Add_OsmWayNodes_Table")]
    partial class Add_OsmWayNodes_Table
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNodeTagsLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNodesLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWayTagsLoad")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWaysLoad")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("IsAnalyzed");

                    b.HasIndex("IsEmpty");

                    b.HasIndex("IsNodeTagsLoad");

                    b.HasIndex("IsNodesLoad");

                    b.HasIndex("IsWayTagsLoad");

                    b.HasIndex("IsWaysLoad");

                    b.ToTable("OsmFiles");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNode", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<long>("OsmFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Latitude");

                    b.HasIndex("Longitude");

                    b.HasIndex("OsmFileId");

                    b.ToTable("OsmNodes");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNodeTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Key");

                    b.HasIndex("OsmNodeId");

                    b.HasIndex("Value");

                    b.ToTable("OsmNodeTags");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWay", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("OsmFileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OsmFileId");

                    b.ToTable("OsmWays");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWayNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("OsmNodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("OsmWayId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("OsmNodeId");

                    b.HasIndex("OsmWayId");

                    b.ToTable("OsmWayNodes", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWayTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("OsmWayId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Key");

                    b.HasIndex("OsmWayId");

                    b.HasIndex("Value");

                    b.ToTable("OsmWayTags");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNode", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmFile", "OsmFile")
                        .WithMany("OsmNodes")
                        .HasForeignKey("OsmFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OsmNodes_OsmFile");

                    b.Navigation("OsmFile");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNodeTag", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNode", "OsmNode")
                        .WithMany("OsmNodeTags")
                        .HasForeignKey("OsmNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OsmNodeTags_OsmNode");

                    b.Navigation("OsmNode");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWay", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmFile", "OsmFile")
                        .WithMany("OsmWays")
                        .HasForeignKey("OsmFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OsmWays_OsmFile");

                    b.Navigation("OsmFile");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWayNode", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNode", "OsmNode")
                        .WithMany("OsmWayNodes")
                        .HasForeignKey("OsmNodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OsmWayNode_OsmNode");

                    b.HasOne("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWay", "OsmWay")
                        .WithMany("OsmWayNodes")
                        .HasForeignKey("OsmWayId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OsmWayNode_OsmWay");

                    b.Navigation("OsmNode");

                    b.Navigation("OsmWay");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWayTag", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWay", "OsmWay")
                        .WithMany("OsmWayTags")
                        .HasForeignKey("OsmWayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OsmWayTags_OsmWay");

                    b.Navigation("OsmWay");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmFile", b =>
                {
                    b.Navigation("OsmNodes");

                    b.Navigation("OsmWays");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmNode", b =>
                {
                    b.Navigation("OsmNodeTags");

                    b.Navigation("OsmWayNodes");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OsmDatabase.Entities.OsmWay", b =>
                {
                    b.Navigation("OsmWayNodes");

                    b.Navigation("OsmWayTags");
                });
#pragma warning restore 612, 618
        }
    }
}
