// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simargl.Border.Storage;

#nullable disable

namespace Simargl.Border.Storage.Migrations
{
    [DbContext(typeof(BorderStorageContext))]
    [Migration("20260216144814_Add_Main_Tables")]
    partial class Add_Main_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Simargl.Border.Storage.Entities.AxisData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<long>("PassageKey")
                        .HasColumnType("bigint");

                    b.HasKey("Key");

                    b.HasIndex("PassageKey");

                    b.ToTable("Axes");
                });

            modelBuilder.Entity("Simargl.Border.Storage.Entities.AxisInteractionData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<long>("AxisKey")
                        .HasColumnType("bigint");

                    b.Property<double>("LeftAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("LeftDeviation")
                        .HasColumnType("double precision");

                    b.Property<double>("LeftMax")
                        .HasColumnType("double precision");

                    b.Property<double>("LeftSquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("LeftSum")
                        .HasColumnType("double precision");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<double>("Position")
                        .HasColumnType("double precision");

                    b.Property<double>("RightAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("RightDeviation")
                        .HasColumnType("double precision");

                    b.Property<double>("RightMax")
                        .HasColumnType("double precision");

                    b.Property<double>("RightSquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("RightSum")
                        .HasColumnType("double precision");

                    b.Property<int>("Section")
                        .HasColumnType("integer");

                    b.Property<double>("Speed")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedDeviation")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedSquaresSum")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedSum")
                        .HasColumnType("double precision");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.HasKey("Key");

                    b.HasIndex("AxisKey");

                    b.ToTable("AxisInteractions");
                });

            modelBuilder.Entity("Simargl.Border.Storage.Entities.PassageData", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<int>("AxesCommits")
                        .HasColumnType("integer");

                    b.Property<int>("AxesCount")
                        .HasColumnType("integer");

                    b.Property<long>("EndTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("StartTimestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("State");

                    b.ToTable("Passages");
                });

            modelBuilder.Entity("Simargl.Border.Storage.Entities.AxisData", b =>
                {
                    b.HasOne("Simargl.Border.Storage.Entities.PassageData", "Passage")
                        .WithMany("Axes")
                        .HasForeignKey("PassageKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Passages_Axes");

                    b.Navigation("Passage");
                });

            modelBuilder.Entity("Simargl.Border.Storage.Entities.AxisInteractionData", b =>
                {
                    b.HasOne("Simargl.Border.Storage.Entities.AxisData", "Axis")
                        .WithMany("Interactions")
                        .HasForeignKey("AxisKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Axes_Interactions");

                    b.Navigation("Axis");
                });

            modelBuilder.Entity("Simargl.Border.Storage.Entities.AxisData", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Simargl.Border.Storage.Entities.PassageData", b =>
                {
                    b.Navigation("Axes");
                });
#pragma warning restore 612, 618
        }
    }
}
