// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(CentralDatabaseContext))]
    [Migration("20220106094625_Add_HostComputerInfos_Table")]
    partial class Add_HostComputerInfos_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.DatabaseTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("DatabaseTables", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.DatabaseTableCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("DatabaseTableCategories", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Direction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Directions", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("FileStorages", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileStorageConnector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("Id");

                    b.HasIndex("Priority");

                    b.ToTable("FileStorageConnectors", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.GeneralDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("GeneralDirectories", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.HostComputerInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("HostComputerInfos", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.InternalDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<long>("GeneralDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ParentDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("FileStorageId", "GeneralDirectoryId", "Path");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("GeneralDirectoryId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("Path");

                    b.ToTable("InternalDirectories", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.InternalFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<long>("GeneralDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ParentDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("FileStorageId", "GeneralDirectoryId", "Path");

                    b.HasIndex("Extension");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("GeneralDirectoryId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("Path");

                    b.HasIndex("RegistrationTime");

                    b.ToTable("InternalFiles", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Jobs", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.MicroserviceInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NextStepDelay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("MicroserviceInfos", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.MicroserviceInt32Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MicroserviceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("MicroserviceId", "Name");

                    b.HasIndex("Id");

                    b.HasIndex("MicroserviceId");

                    b.HasIndex("Name");

                    b.ToTable("MicroserviceInt32Settings", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Recorder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TransferDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<int>("TransferIdentificator")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TransferDirectoryId");

                    b.HasIndex("TransferIdentificator");

                    b.ToTable("Recorders", (string)null);
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.DatabaseTable", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.DatabaseTableCategory", "Category")
                        .WithMany("Tables")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DatabaseTables_DatabaseTableCategories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileStorageConnector", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileStorage", "FileStorage")
                        .WithMany("Connectors")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FileStorageConnectors_FileStorages");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.GeneralDirectory", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileStorage", "FileStorage")
                        .WithMany("GeneralDirectories")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GeneralDirectories_FileStorages");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.InternalDirectory", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileStorage", "FileStorage")
                        .WithMany("InternalDirectories")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InternalDirectories_FileStorages");

                    b.HasOne("Apeiron.Platform.Server.Database.Entities.GeneralDirectory", "GeneralDirectory")
                        .WithMany("InternalDirectories")
                        .HasForeignKey("GeneralDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InternalDirectories_GeneralDirectories");

                    b.HasOne("Apeiron.Platform.Server.Database.Entities.InternalDirectory", "ParentDirectory")
                        .WithMany("InternalDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_InternalDirectories_InternalDirectories");

                    b.Navigation("FileStorage");

                    b.Navigation("GeneralDirectory");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.InternalFile", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileStorage", "FileStorage")
                        .WithMany("InternalFiles")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InternalFiles_FileStorages");

                    b.HasOne("Apeiron.Platform.Server.Database.Entities.GeneralDirectory", "GeneralDirectory")
                        .WithMany("InternalFiles")
                        .HasForeignKey("GeneralDirectoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InternalFiles_GeneralDirectories");

                    b.HasOne("Apeiron.Platform.Server.Database.Entities.InternalDirectory", "ParentDirectory")
                        .WithMany("InternalFiles")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InternalFiles_InternalDirectories");

                    b.Navigation("FileStorage");

                    b.Navigation("GeneralDirectory");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.MicroserviceInt32Setting", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.MicroserviceInfo", "Microservice")
                        .WithMany("Int32Settings")
                        .HasForeignKey("MicroserviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MicroserviceInt32Settings_MicroserviceInfos");

                    b.Navigation("Microservice");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Recorder", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.InternalDirectory", "TransferDirectory")
                        .WithMany("Recorders")
                        .HasForeignKey("TransferDirectoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Recorders_InternalDirectories");

                    b.Navigation("TransferDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.DatabaseTableCategory", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileStorage", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("GeneralDirectories");

                    b.Navigation("InternalDirectories");

                    b.Navigation("InternalFiles");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.GeneralDirectory", b =>
                {
                    b.Navigation("InternalDirectories");

                    b.Navigation("InternalFiles");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.InternalDirectory", b =>
                {
                    b.Navigation("InternalDirectories");

                    b.Navigation("InternalFiles");

                    b.Navigation("Recorders");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.MicroserviceInfo", b =>
                {
                    b.Navigation("Int32Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
