// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(CentralDatabaseContext))]
    [Migration("20211230141248_Add_InternalDirectories_Table")]
    partial class Add_InternalDirectories_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Economic.Direction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Economic.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.Economic.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.FileStorage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("FileStorages");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.FileStorageConnector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("Id");

                    b.HasIndex("Priority");

                    b.ToTable("FileStorageConnectors");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.GeneralDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("FileStorageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("FileStorageId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.ToTable("GeneralDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.InternalDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("GeneralDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ParentDirectoryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GeneralDirectoryId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentDirectoryId");

                    b.ToTable("InternalDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.FileStorageConnector", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileSystem.FileStorage", "FileStorage")
                        .WithMany("Connectors")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FileStorageConnectors_FileStorages");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.GeneralDirectory", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileSystem.FileStorage", "FileStorage")
                        .WithMany("GeneralDirectories")
                        .HasForeignKey("FileStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GeneralDirectories_FileStorages");

                    b.Navigation("FileStorage");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.InternalDirectory", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileSystem.GeneralDirectory", "GeneralDirectory")
                        .WithMany("InternalDirectories")
                        .HasForeignKey("GeneralDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InternalDirectories_GeneralDirectories");

                    b.HasOne("Apeiron.Platform.Server.Database.Entities.FileSystem.InternalDirectory", "ParentDirectory")
                        .WithMany("InternalDirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_InternalDirectories_InternalDirectories");

                    b.Navigation("GeneralDirectory");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.FileStorage", b =>
                {
                    b.Navigation("Connectors");

                    b.Navigation("GeneralDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.GeneralDirectory", b =>
                {
                    b.Navigation("InternalDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Database.Entities.FileSystem.InternalDirectory", b =>
                {
                    b.Navigation("InternalDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
