// <auto-generated />
using Apeiron.Platform.Databases.Ra2Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(Ra2DatabaseContext))]
    [Migration("20220203122034_AddFields_IsAnalized")]
    partial class AddFields_IsAnalized
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Ra2.Server.Database.Entities.RawFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("IsAnalyzed");

                    b.ToTable("RawFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
