// <auto-generated />
using System;
using Apeiron.Platform.Databases.Ape90Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(Ape90DatabaseContext))]
    [Migration("20220223073449_Add_RawFileMetrics")]
    partial class Add_RawFileMetrics
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawFrames");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawGeolocations");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawPower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawPowers");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawFrame", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", "RawDirectory")
                        .WithMany("RawFrames")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawFrames_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", "RawDirectory")
                        .WithMany("RawGeolocations")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawGeolocations_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawPower", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", "RawDirectory")
                        .WithMany("RawPowers")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawPowers_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", b =>
                {
                    b.Navigation("RawFrames");

                    b.Navigation("RawGeolocations");

                    b.Navigation("RawPowers");
                });
#pragma warning restore 612, 618
        }
    }
}
