// <auto-generated />
using System;
using Apeiron.Platform.Databases.Ape90Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    [DbContext(typeof(Ape90DatabaseContext))]
    [Migration("20220223104006_Add_Geolocation_Tables")]
    partial class Add_Geolocation_Tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.GgaMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<double?>("Age")
                        .HasColumnType("float");

                    b.Property<double?>("Altitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Geoidal")
                        .HasColumnType("float");

                    b.Property<double?>("Hdop")
                        .HasColumnType("float");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<long>("RawGeolocationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Satellites")
                        .HasColumnType("int");

                    b.Property<int?>("Solution")
                        .HasColumnType("int");

                    b.Property<int?>("Station")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasAlternateKey("RawGeolocationId", "Index");

                    b.ToTable("GgaMessages");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("FrameDuration")
                        .HasColumnType("float");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawDirectories");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNormalizedTime")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("BeginTime");

                    b.HasIndex("EndTime");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawFrames");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawGeolocations");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawPower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMetrics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWriteTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NameTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("RawDirectoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path");

                    b.HasIndex("RawDirectoryId");

                    b.ToTable("RawPowers");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RmcMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Knots")
                        .HasColumnType("float");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticVariation")
                        .HasColumnType("float");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("float");

                    b.Property<long>("RawGeolocationId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("time");

                    b.Property<bool?>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasAlternateKey("RawGeolocationId", "Index");

                    b.ToTable("RmcMessages");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.VtgMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("FileTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("bit");

                    b.Property<double?>("Knots")
                        .HasColumnType("float");

                    b.Property<double?>("MagneticCourse")
                        .HasColumnType("float");

                    b.Property<int?>("Mode")
                        .HasColumnType("int");

                    b.Property<double?>("PoleCourse")
                        .HasColumnType("float");

                    b.Property<long>("RawGeolocationId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("RawGeolocationId", "Index");

                    b.ToTable("VtgMessages");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.GgaMessage", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", "RawGeolocation")
                        .WithMany("GgaMessages")
                        .HasForeignKey("RawGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GgaMessages_RawGeolocations");

                    b.Navigation("RawGeolocation");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawFrame", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", "RawDirectory")
                        .WithMany("RawFrames")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawFrames_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", "RawDirectory")
                        .WithMany("RawGeolocations")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawGeolocations_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawPower", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", "RawDirectory")
                        .WithMany("RawPowers")
                        .HasForeignKey("RawDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RawPowers_RawDirectories");

                    b.Navigation("RawDirectory");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RmcMessage", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", "RawGeolocation")
                        .WithMany("RmcMessages")
                        .HasForeignKey("RawGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RmcMessages_RawGeolocations");

                    b.Navigation("RawGeolocation");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.VtgMessage", b =>
                {
                    b.HasOne("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", "RawGeolocation")
                        .WithMany("VtgMessages")
                        .HasForeignKey("RawGeolocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VtgMessages_RawGeolocations");

                    b.Navigation("RawGeolocation");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawDirectory", b =>
                {
                    b.Navigation("RawFrames");

                    b.Navigation("RawGeolocations");

                    b.Navigation("RawPowers");
                });

            modelBuilder.Entity("Apeiron.Platform.Server.Services.Specialized.Ape90.Database.RawGeolocation", b =>
                {
                    b.Navigation("GgaMessages");

                    b.Navigation("RmcMessages");

                    b.Navigation("VtgMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
