// <auto-generated />
using System;
using Apeiron.Platform.Demo.AdxlDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Demo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Apeiron.Platform.Demo.AdxlDemo.Channels.ChannelFragmentInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Average")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChannelInfoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cutoff")
                        .HasColumnType("REAL");

                    b.Property<double>("Deviation")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Sampling")
                        .HasColumnType("REAL");

                    b.Property<double>("Sum")
                        .HasColumnType("REAL");

                    b.Property<double>("SumSquares")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("BeginTime");

                    b.HasIndex("ChannelInfoID");

                    b.HasIndex("EndTime");

                    b.ToTable("ChannelFragmentInfos");
                });

            modelBuilder.Entity("Apeiron.Platform.Demo.AdxlDemo.Channels.ChannelInfo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cutoff")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Sampling")
                        .HasColumnType("REAL");

                    b.Property<long>("SerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SignalNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChannelInfos");
                });

            modelBuilder.Entity("Apeiron.Platform.Demo.AdxlDemo.Channels.ChannelFragmentInfo", b =>
                {
                    b.HasOne("Apeiron.Platform.Demo.AdxlDemo.Channels.ChannelInfo", "ChannelInfo")
                        .WithMany("ChannelFragmentInfos")
                        .HasForeignKey("ChannelInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChannelFragmentInfos_ChannelInfos");

                    b.Navigation("ChannelInfo");
                });

            modelBuilder.Entity("Apeiron.Platform.Demo.AdxlDemo.Channels.ChannelInfo", b =>
                {
                    b.Navigation("ChannelFragmentInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
