// <auto-generated />
using System;
using Apeiron.Platform.Databases.OrioleKmtDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apeiron.Platform.Databases.Migrations
{
    /// <summary>
    /// 
    /// </summary>
    [CLSCompliant(false)]
    [DbContext(typeof(OrioleKmtDatabaseContext))]
    [Migration("20220325120335_AddTimeChunks_and_ChannelNames_Tables")]
    partial class AddTimeChunks_and_ChannelNames_Tables
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.ChannelName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TimeChunkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("Index");

                    b.HasIndex("Name");

                    b.HasIndex("TimeChunkId");

                    b.ToTable("ChannelNames");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.RawFrame", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasAlternateKey("FilePath");

                    b.HasIndex("FilePath");

                    b.HasIndex("Id");

                    b.HasIndex("Time");

                    b.ToTable("RawFrames");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.TimeChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BeginTime");

                    b.HasIndex("EndTime");

                    b.HasIndex("Id");

                    b.ToTable("TimeChunks");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.ChannelName", b =>
                {
                    b.HasOne("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.TimeChunk", "TimeChunk")
                        .WithMany("ChannelNames")
                        .HasForeignKey("TimeChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChannelNames_TimeChunk");

                    b.Navigation("TimeChunk");
                });

            modelBuilder.Entity("Apeiron.Platform.Databases.OrioleKmtDatabase.Entities.TimeChunk", b =>
                {
                    b.Navigation("ChannelNames");
                });
#pragma warning restore 612, 618
        }
    }
}
